### ISSUE TITLE
Pypi release

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#100]
Hey !
Not knowing if intended or not, but Pypi releases are not in sync with git release since `0.9.16` :)
Cheers,

**Comment by mittagessen** [comment]
Ahh damnit, I guess the Travis auto-release broke with the new pypi infrastructure. I'll deal with it but it isn't urgent right now as we're waiting on the next pytorch stable release to tag the 1.0 release of kraken.

**Comment by PonteIneptique** [comment]
Yeah, I assume the kraken.re website update is also broken potentially ?

**Comment by mittagessen** [comment]
That one was always manual as I sometimes added new documentation between versions. The website isn't broken it's just documenting the current stable version. Up-to-date docs for master are in the [docs](https://github.com/mittagessen/kraken/tree/master/docs) directory.

**Comment by mittagessen** [comment]
solved...
