### ISSUE TITLE
Direct PDF input

### ISSUE THREAD

**Issue by mittagessen** [mittagessen/kraken#103]
People keep badgering me me about kraken accepting PDFs directly. Let's adapt [this](https://github.com/mstamy2/PyPDF2/blob/master/Scripts/pdf-image-extractor.py) code to do a substitution like for the batch input.

**Comment by mrocr** [comment]
@mittagessen Kindly close this topic.
You can perhaps add this in `readme`, simple few commands would do the trick, perhaps:
 `pdftk input.pdf burst output input_%02d.pdf`
`for i in *.pdf ; do pdftoppm "$i" "${i%}" -png -rx 300 -ry 300; done`

**Comment by xaiki** [comment]
my 2cts i tend to use: 
`convert -density 300 -trim -colorspace sRGB input.pdf -quality 100 -sharpen 0x1.0 -alpha off   +adjoin output/pdf-%05d.png`

normally i use `-crop` and `-rotate` to get best first-pass simplification.

**Comment by mittagessen** [comment]
4f3223f30624f6ab6d75b54e27e5754de55aea74 adds PDF input through pyvips/libvips. It's fairly fast and doesn't gobble up ridiculous memory in contrast to the imagemagick options I tried.
