### ISSUE TITLE
Kraken installation issue

### ISSUE THREAD

**Issue by skynet147** [mittagessen/kraken#104]
hi , i m installing kraken to my windows 7 laptop ,running on docker.I was  able to install all packages except clstm . Can you help me if there is wheel to install clstm on windows platform?.Attached is the error message .

![error](https://user-images.githubusercontent.com/33216611/48967922-62526280-f001-11e8-9513-749e4613845f.png)

**Comment by mittagessen** [comment]
Kraken isn't supported on windows and I have minimal desire to ensure compatibility with an operating system that I can't check regressions for. Nevertheless you can try to install the current master branch through anaconda. That might or might not work.
