### ISSUE TITLE
Ability to `--lines` with a suffix for `-I`

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#105]
The idea would be to be able to run segmentation once and then be able to run different models using a globlike input with a suffix for segmentation.

Right now, I deal with this with like that

```python
    if lines and lines.startswith('suffix:'):
        lines = base_image+lines.split("suffix:")[-1]
```

**Comment by PonteIneptique** [comment]
The first to do the second later :)

**Comment by mittagessen** [comment]
Ah, to do the second use the `ketos test` command if you want to just compare the accuracy of multiple models. It will be fairly slow though because it re-encodes/re-normalizes the complete dataset for each model.

If you want to create a pull request of your code I can merge it. Ideally following a similar format to [extract](https://github.com/mittagessen/kraken/blob/9700f4078adf25f531ac040a5026d7b4f4038e16/kraken/ketos.py#L542), we've got way too much slightly different behavior anyway.

**Comment by PonteIneptique** [comment]
I'll PR ASAP.
For my precise usecase, it's not testing per se : I actually have a manuscript that has a free interpretation of spaces, which makes it difficult even for human reader to decide. Some time, space were inserted in the transcription data where it should not have, sometime it did not. For further quantitative research, we created two models : one with space character, one without ; hence the need to run both models later (and not go through segmentation twice).

**Comment by mittagessen** [comment]
I assume it's something in scripta continua or simlar?

> For further quantitative research, we created two models : one with space character, one without ; hence the need to run both models later (and not go through segmentation twice).

The segmentation is deterministic so it running it twice doesn't really hurt except being an additional expenditure of CPU cycles.

**Comment by PonteIneptique** [comment]
> Being an additional expenditure of CPU cycles.
That's what I am trying to avoid. :) Better not run it every time I update my model. :)

> I assume it's something in scripta continua or similar?
More or less, yes. There is space, but not always.

**Comment by mrocr** [comment]
@mittagessen Kindly close the topic

**Comment by mittagessen** [comment]
With the region code of the new segmenter we've got the ability to input multiple ALTO/PageXML files to supply existing segmentations to the ocr submodule.
