### ISSUE TITLE
Arabic Models

### ISSUE THREAD

**Issue by skynet147** [mittagessen/kraken#106]
Hi ,

Today,i installed kraken on ubuntu platform without issues. I hit below issues ,i think you already know the answers ,this might be simple - but i am new on ubuntu

1-When i use command ' kraken -i image.tif image.txt binarize segment ocr'' to binarize , i am getting below error message for .txt file ;
''ValueError: unknown file extension'
can't generate text file from photo

2-When i use command '' kraken get arabic-amiri' , i am not able pull arabic models , how can i download and run those models ?

**Comment by mittagessen** [comment]
1 -> this works for me if provided with a recognition model

2 -> same here, although it will fetch an older clstm model.

**Comment by mrocr** [comment]
@mittagessen kindly close this topic
