### ISSUE TITLE
Install using Conda problem

### ISSUE THREAD

**Issue by lequocgiom** [mittagessen/kraken#108]
Hi, I encountered a problem while installing kraken via conda.
After running two 2 scripts: 
$ wget https://raw.githubusercontent.com/mittagessen/kraken/master/environment.yml
$ conda env create -f environment.yml

The console shows the message below 

>  Could not find a version that satisfies the requirement coremltools (from -r C:\Users\Trung Le Dep Trai\condaenv.zp0wc9yw.requirements.txt (line 1)) (from versions: )
> No matching distribution found for coremltools (from -r C:\Users\Trung Le Dep Trai\condaenv.zp0wc9yw.requirements.txt (line 1))
> 
> CondaValueError: pip returned an error

![image](https://user-images.githubusercontent.com/44612846/49949508-5c78de80-ff28-11e8-9293-c4a9c790f279.png)

Can anyone help me solve this problem, I am a newbie and cannot find how to solve it. Thanks so much.

**Comment by mittagessen** [comment]
Uhhhm, sorry Windows isn't supported. Mac OS X and Linux only at this point. Even if we were to get it running there is just no way we could keep it from continuously breaking as nobody around here uses Windows. That might change if somebody decides to write really really extensive tests so we can catch regressions automatically but I doubt it.
