### ISSUE TITLE
Using pretrained Arabic models on arbitrary samples

### ISSUE THREAD

**Issue by Mr-DDDAlKilanny** [mittagessen/kraken#109]
The arabic models when tested on simple images yield 0% accuracy, not only a single model but all.

**Comment by mittagessen** [comment]
Sorry, I'm in the process of reorganizing the model repository and haven't retrained the models there for the new backend. There is a generalized model at http://homer.dh.uni-leipzig.de/arabic_generalized.mlmodel that produces fairly high accuracy across different fonts.
