### ISSUE TITLE
Training Kraken, is it possible to train with my own data ?

### ISSUE THREAD

**Issue by lequocgiom** [mittagessen/kraken#112]
I am trying to train Kraken on my own data which are pairs of images and text files. A pair is like 0.png and 0.gt.txt which contains the text in the image 0.png, and a manifest.txt containing all the lines from all the images. 

But when I run the script ketos train *.png in the folder containing the data, it said that "Training from scratch not yet supported." 

Here is my data, is it possible to train Kraken on this kind of data ? This just a test data with 100 lines, my team have already crawled 20000 lines. Thanks for any help, I would be very grateful. Sorry if this question is silly or something, I'm a newbie and trying to learn.

[test.zip](https://github.com/mittagessen/kraken/files/2724081/test.zip)

**Comment by mittagessen** [comment]
It is completely possible to train from your own data. Apparently, you haven't installed the last stable version which does support training from scratch. Even with 100 lines you can get quite a good model (in our experience >90%) especially when training from an existing model.
