### ISSUE TITLE
Binarization/segmentation does not work on empty pages

### ISSUE THREAD

**Issue by wrznr** [mittagessen/kraken#113]
Consider http://digital.slub-dresden.de/fileadmin/data/284175080/284175080_tif/jpegs/00000002.tif.original.jpg, using
```shell
kraken -i 00000002.tif.original.jpg segment.json binarize segment
```
results in 968 text lines. This is most likely due to the low contrast on this image which leads to a defective binarization.

**Comment by mittagessen** [comment]
The combination of the bad binarization with the low number of lines in the image results in a particular aberrant segmentation, as the standard deviation of the filters is scaled by a factor determined through a line count estimator. There is no way to reliably auto-fix this with the current algorithms and in our manuscript work we usually run an ad-hoc binarizer that solves this problem to a large extent.

**Comment by wrznr** [comment]
What kind of "ad-hoc" binarizer? Is it that you choose manually from a set of available tools/algorithms the one which works best?

**Comment by mittagessen** [comment]
It functions somewhat similarly to the implemented binarizer but skips all the automatisms, i.e. you need to manually set half a dozen parameters. Even then there is some really ... interesting ... stuff that it doesn't deal well with and people fall back to other algorithms. It sucks but quite a bit of the data is weird and rare enough that a general binarizer doesn't work and nobody's going to produce enough annotated images for a trainable binarizer.
