### ISSUE TITLE
Chomp / rstrip input lines ?

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [mittagessen/kraken#114]
When training on a set of text lines obtained from outside tools (i.e., not from `ketos extract`), I kept encountering a very frequent errors in predictions, in the form:

    Errors	Correct-Generated
    2459	{ 0xa } - {  }

There were no line breaks in data that I could see, until I searched for them with a Python script. In the end, I add to clean all the lines using `re.sub(r'[\u000A\u001A\n]', "", data)`, but, if ever I modify them with a tool like Gedit, I have to rerun the cleaning script.

Could it not be built into Kraken to strip line endings by default, since each `.gt.txt` file always equals a line ?

**Comment by mittagessen** [comment]
OK, the straightforward way is to add the normalize whitespace switch from the `extract` subcommand to `train` and have it also strip on the right/left to remove the superfluous whitespace. As `ketos extract` already behaves that way I also have no qualms to have this option enabled per default.

I can do that reasonably soon or you can create a pull request.
