### ISSUE TITLE
[Might be helpful] XSL for HOCR to Kraken Transcribing Env

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#115]
Hey there.
I know I still have to add the function we spoke about but got derailed. Today I was looking at training data or models to transcribe Loeb and did not find much in the area. This led me to wanting to correct annotations and making training more efficient... But impossible, or not easy, with Tesseract.

This is why I have written an XSL that transforms HOCR (at least from Tesseract) to the same transcribing template you have : https://gist.github.com/PonteIneptique/c866c3387f7a5709dbd17b86123b37c5

Just in case it might help someone

**Comment by mittagessen** [comment]
Ah nice. With regard to Loeb training data, I know that Bruce Robertson has some although convincing him to share it might be a challenge.

**Comment by PonteIneptique** [comment]
To be fair, the tesseract output is in a good shape. I'll see what pocoto gives and then share the data if it helps

**Comment by PonteIneptique** [comment]
I can confirm that Tesseract prefill into Kraken speed things up when Tesseract does weird things ;)

**Comment by PonteIneptique** [comment]
To have an idea, files named .hocr.html are based on this conversion : https://github.com/lascivaroma/lexical/tree/master/ocr-training/anthologia-latina
