### ISSUE TITLE
Error trying to get hOCR output

### ISSUE THREAD

**Issue by whatda** [mittagessen/kraken#12]
Hi,

After getting kraken to work on my machine, I tried to get hOCR output, sadly without any success.

A normal call to kraken works and looks like this:

`kraken -i 1.tiff test.txt`

No problem so far.

But when I try to call for hOCR output as follows, it doesn't work:

`kraken -i 1.tiff test.hocr ocr -h`

I get the following error:

    File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 132, in process_pipeline
        task(base_image=base_image, input=input, output=output)
      File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 83, in recognizer
        in csv.reader(fp)]
    _csv.Error: line contains NULL byte

The usage help says `Usage: kraken [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...`, so I don't get what I'm doing wrong.

Any help is appreciated. Thank you.

**Comment by mittagessen** [comment]
You have to feed it a page segmentation file, i.e the recognition part (ocr) operates on a segmentation for the input image. The correct call chains a segmentation and recognition step like this:

   $ kraken -i 1.tiff test.hocr segment ocr -h

The default invocation:

    $ kraken -i 1.tiff test.txt

is basically the same as:

    $ kraken -i 1.tiff test.txt binarize segment ocr

only that you don't get all the parameters of each subcommand when running the default.
