### ISSUE TITLE
Error: Invalid value: No model for default found

### ISSUE THREAD

**Issue by Manal-Almodala** [mittagessen/kraken#120]
![error](https://user-images.githubusercontent.com/18753819/52530872-8f1f3780-2d1d-11e9-93c9-58ca1a27d2ff.png)

Hi 

I use ubuntu 18 , and setup Kraken but when I try to run the commend I face this problem 

How can I solve it !!

**Comment by mzeidhassan** [comment]
I am having the same problem. Although I did 'kraken get default'.

**Comment by nshaud** [comment]
Same. It looks like `kraken get default` does not save anything to the disk.

**Comment by mittagessen** [comment]
Apologies, the model repository is in the process of being migrated away from Zenodo and the old one hasn't been updated with kraken 1.0 models, yet. The "new" English default model is [here](http://homer.dh.uni-leipzig.de/en_best.mlmodel) for now. Sorry for the inconvenience.

**Comment by nshaud** [comment]
@mittagessen Where should I store the file so that the kraken binary sees it?

**Comment by mittagessen** [comment]
Anywhere is fine, you can use an explicit path with the `-m` argument. If the model can't be found under the path, there is a user-global directory (usually `.config/kraken/`) that is also searched.

**Comment by Mangosteen-Yang** [comment]
> Anywhere is fine, you can use an explicit path with the `-m` argument. If the model can't be found under the path, there is a user-global directory (usually `.config/kraken/`) that is also searched.

I got 'no such option: -m'

**Comment by mzeidhassan** [comment]
> Apologies, the model repository is in the process of being migrated away from Zenodo and the old one hasn't been updated with kraken 1.0 models, yet.

@mittagessen any update on this? I have problems when I try to download arabic-amiri model as well. It looks like it has been downloaded, but when I use -m arabic-amiri, I get an error message that it doesn't exist. 

Another question: from where can I download all available models?

**Comment by mittagessen** [comment]
The new repository is online although I haven't pushed the new models except the default one as I'm swamped by a series of workshops and article deadlines right now. I can get around to it sometime next week probably.

**Comment by mzeidhassan** [comment]
Thanks @mittagessen ! Good luck with all your current tasks! May I ask you please to update this issue when all models are pushed? Thanks again for your support!

**Comment by johann-petrak** [comment]
This still does not seem to work with the current release.

**Comment by minjungkim85** [comment]
Having the same issue with the current release.

**Comment by LilyG98** [comment]
I am having the same issue with the latest conda version

**Comment by diegosiqueir4** [comment]
[A generalized model for English printed text
](https://zenodo.org/record/2577813)

**Comment by nraw** [comment]
Still same issue with version 2.0.8.

**Comment by Saritakarki** [comment]
You can pass the model path after "ocr"
Example: _kraken -i image.tif image.txt binarize segment ocr -m "model path"_
Default model path is:  "~/.config/kraken/en_best.mlmodel"
