### ISSUE TITLE
Which Arabic model do you recommend?

### ISSUE THREAD

**Issue by mzeidhassan** [mittagessen/kraken#121]
Hi Kraken team,

First, thank you so much for Kraken OCR. 

I downloaded Kraken and I would like to use it with Modern Standard Arabic (MSA) text. When I use "kraken list", I see a couple of Arabic models that are basically for classical text.

I have 2 questions:
1) What do you mean exactly by 'classical'? Are you referring to the old Arabic manuscripts centuries ago?
2) If I am going to choose one to scan some MSA documents, which one do you recommend? What are the differences between these models? 

1. arabic-yacqubi (clstm)
2. arabic-beirut-200 (clstm)
3. arabic-buldan (clstm)
4. arabic-qutayba (clstm)
5. arabic-hayawan (clstm)
6. arabic-beirut (clstm)
7. arabic-muntazam (clstm)
8. arabic-amiri (clstm)
9. arabic-kamil (clstm)

Thanks in advance for your support!

**Comment by mittagessen** [comment]
The current best generalized model is [here](https://github.com/OpenITI/OCR_GS_Data/blob/master/ara/abhath/arabic_generalized.mlmodel). That has also been trained with modern typefaces that are more aligned with the ones in current use than the older ones.

With classical Arabic we meant texts written in classical Arabic not necessarily the time of the printing. Most of them were printed after 1900 but they've got characteristics like extensive diacritization that you wouldn't encounter in your use case.

**Comment by mzeidhassan** [comment]
Thank you so much @mittagessen!

What do I need to use the "arabic_generalized.mlmodel"?

I download the model at ~/Downloads

Tried this command:

`kraken -i ara.tif arabic.txt binarize segment ocr -m ~/Downloads/arabic_generalized.mlmodel`, but I get the following error. Please note that I am using a VirtualBox image with Ubuntu 16.04 and I installed kraken using pip install.

> Loading RNN default	✓
Binarizing	✓
Traceback (most recent call last):
  File "/home/mzeid/.local/bin/kraken", line 11, in <module>
    sys.exit(cli())
  File "/home/mzeid/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mzeid/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mzeid/.local/lib/python3.5/site-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/home/mzeid/.local/lib/python3.5/site-packages/click/core.py", line 1102, in _process_result
    **ctx.params)
  File "/home/mzeid/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mzeid/.local/lib/python3.5/site-packages/kraken/kraken.py", line 220, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/home/mzeid/.local/lib/python3.5/site-packages/kraken/kraken.py", line 78, in segmenter
    from kraken import pageseg
  File "/home/mzeid/.local/lib/python3.5/site-packages/kraken/pageseg.py", line 39, in <module>
    from kraken.rpred import rpred
  File "/home/mzeid/.local/lib/python3.5/site-packages/kraken/rpred.py", line 31, in <module>
    from kraken.lib.dataset import generate_input_transforms
  File "/home/mzeid/.local/lib/python3.5/site-packages/kraken/lib/dataset.py", line 153
    algn1: List[Any] = []
         ^
SyntaxError: invalid syntax

if I use this command:

`kraken -i ara.tif ara.txt binarize segment ocr`

I get this error message:

> Error: Invalid value: No model for default found

While I was able to do 'kraken list' before, now I get this error when I do it again:

`kraken.lib.exceptions.KrakenRepoException: 403: API rate limit exceeded for '100.00.000.12'. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)`

Not sure what this is? 

It usually shows me the following list:

> kraken list
Retrieving model list ........................✓
arabic-muntazam (clstm) - An experimental model for Classical Arabic texts.
migne (pyrnn) - A classifier for polytonic Greek for Migne texts
goodell (pyrnn) - A classifier for polytonic Greek for Goodell fonts
fraktur (pyrnn) - A converted version of fraktur.pyrnn.gz
arabic-beirut (clstm) - An experimental model for Classical Arabic texts.
arabic-amiri (clstm) - An experimental model for Arabic texts typeset in the Amiri font.
teubner-serif (pyrnn) - A classifier for polytonic Greek for serif Teubner types
porson (pyrnn) - A classifier for polytonic Greek typeset using Porson
arabic-buldan (clstm) - An experimental model for Classical Arabic texts.
rahlfs (pyrnn) - A classifier for polytonic Greek for Rahlfs texts
arabic-kamil (clstm) - An experimental model for Classical Arabic texts.
syriac-monotype (clstm) - A model for classical Syriac
arabic-qutayba (clstm) - An experimental model for Classical Arabic texts.
migne-njp (pyrnn) - A converted version of en-default.pyrnn.gz
script-detection (clstm) - A model for script classification
non-teubner-german-serif (pyrnn) - A polytonic Greek classifiers for non-teubner serif fonts
default (pyrnn) - A converted version of en-default.pyrnn.gz
toy (clstm) - A toy model trained on 400 lines of the UW3 data set.
loeb (pyrnn) - A classifier for polytonic Greek for Loebs
arabic-yacqubi (clstm) - An experimental model for Classical Arabic texts.
arabic-beirut-200 (clstm) - An experimental model for Classical Arabic texts.
arabic-hayawan (clstm) - An experimental model for Classical Arabic texts.
omnibus (pyrnn) - An attempt at an universal classifier for polytonic Greek


I am new to Kraken. I appreciate your support.

**Comment by mzeidhassan** [comment]
Following the advice at the end of this [issue](https://github.com/mittagessen/kraken/issues/111), I installed Python 3.6.7 and updated its configuration to make the default python, but I am still getting the same error. 

How can I resolve this and how can I use the downloaded model "arabic_generalized.mlmodel"? I tried it with -m flag and added the path to the model as:

`-m ~/Downloads/arabic_generalized.mlmodel`

but still nothing works?

**Comment by mittagessen** [comment]
Could you show me the error output? If you're seeing an syntax error for `algn1: List[Any] = []` you're not running kraken under python 3.6.

**Comment by mzeidhassan** [comment]
I removed Python 3.5 from my machine and I can use Kraken now with the arabic_generalized.mlmodel, but the quality is not good at all.

Any idea on how to improve the quality? Are there guidelines on how to prepare Arabic images for Kraken OCR? I tested it on different images that I downloaded from the web, but the output is not good.

**Comment by mittagessen** [comment]
There are three things I can imagine causing bad output right now. The model is primarily trained on Naskh typefaces so anything else will result in worse accuracy, you're downloading JPEG files that have already been binarized (encoding a binarized with JPEG will result in a grayscale image that has to be binarized again, reducing accuracy considerably), or the layout of the images is too complex and the segmenter breaks down.

**Comment by mzeidhassan** [comment]
Thanks @mittagessen for your advice. 

One last question:

What is the best approach to OCR a page that contains both English and Arabic? Something like a dictionary file that has 2 columns; English terms -> Arabic terms?

Can you combine 2 models to do this or do you need to segment/split the columns first?

**Comment by mzeidhassan** [comment]
Hi @mittagessen ,

Welcome back! I see that you closed the issue, but I had a question above. Any chance you have some free time to answer it? Here it's again, just in case

"What is the best approach to OCR a page that contains both English or German and Arabic? Something like a dictionary file that has 2 columns; German terms -> Arabic terms?

Can you combine 2 models to do this or do you need to segment/split the columns first?"

Thanks in advance for your support!

**Comment by AK-ContinuousL** [comment]
HELLO!!

Thank you so much for Kraken+ Escriptorium.

I downloaded both and would like to use them on Historical manuscripts (Mainly Arabic texts). When I used a few Arabic models, I didn't really succeed in uploading the best generalized model. I got this message: 'Invalid model'. Could you please provide a good model that works on historical Arabic manuscripts?  

Thank you in advance for your help !
