### ISSUE TITLE
How can I use a Kraken model in a Python Application ?

### ISSUE THREAD

**Issue by lequocgiom** [mittagessen/kraken#123]
Hi, is there a way to integrate a trained Kraken model in my python application instead of using command line ? 

Thanks so much.

**Comment by mittagessen** [comment]
Yes, there is. In fact, kraken has been designed to be easily integrated into other systems. Have a look at the [API](http://kraken.re/api.html) docs. Depending on which parts you need, the sequence of functions to call is `nlbin.binarize() -> pageseg.segment() -> rpred.rpred()`. Models are loaded with `lib.models.load_any()`.
