### ISSUE TITLE
RuntimeError with `ketos transcribe`

### ISSUE THREAD

**Issue by alix-tz** [mittagessen/kraken#125]
I want to generate a transcription interface to create training data but everytime I run `ketos transcribe ...`, I end up on a RuntimeError, as you can see in the exemple bellow: 

![ketos_transcribe_rterror](https://user-images.githubusercontent.com/33317799/52952903-4c490980-3386-11e9-9b47-9fd8202fd106.png)

I don't believe I missed something in the documentation on installing and training Kraken. Do you see any way to solve this problem?

**Comment by mittagessen** [comment]
Resolved in d867d867cd0d458599f532197e349866c58670a6
