### ISSUE TITLE
metadata for custom model

### ISSUE THREAD

**Issue by hlapin** [mittagessen/kraken#127]
Did not see this in existing issues. Having successfully created a custom model (thank you!), how to add metadata to the model along the following from the docs:

``` 
name: arabic-alam-al-kutub.clstm
An experimental model for Classical Arabic texts.
Network trained on 889 lines of [0] ...

**Comment by mittagessen** [comment]
For the newest kraken version 2.0.1 you can publish the model to the repository yourself with the `ketos publish` command. You need a [Zenodo](https://www.zenodo.org/) account and have to create an access token. The command line utility will ask for all the relevant fields. I haven't written the documentation for the new repository yet but the prompts are fairly obvious.

**Comment by hlapin** [comment]
Thanks, I'll give it a try.
