### ISSUE TITLE
MUFI characters and ligatures disappears

### ISSUE THREAD

**Issue by gabays** [mittagessen/kraken#132]
When I transcribe in the browser and I save the page, many characters disappear. They usually are unusual characters, such as ligatures (long s + t, unicode and MUFI). Is there something to deactivate or a recommendation? I've tried both with firefox and Chrome…

Thx!

**Comment by mittagessen** [comment]
Interesting. It works for me just copying and pasting stuff out of the MUFI PDF. I assume you're using Max OSX? Do you have some sample text?
