### ISSUE TITLE
Ketos has undocumented version dependency Python >= 3.6.x (was "ketos runtime error")

### ISSUE THREAD

**Issue by pseudomonas** [mittagessen/kraken#133]
Running `ketos`, whether with command-line arguments or not, gives the following error:

```
$ ~/.local/bin/ketos
Traceback (most recent call last):
  File "/home/me/.local/bin/ketos", line 7, in <module>
    from kraken.ketos import cli
  File "/home/me/.local/lib/python3.5/site-packages/kraken/ketos.py", line 459
    algn_gt: List[str] = []
           ^
SyntaxError: invalid syntax
```

Ubuntu; Python 3.5.2; kraken 2.0.1 installed with `pip3 install --user kraken`

**Comment by pseudomonas** [comment]
Issue persists in release `kraken-2.0.2.dev11` although the line number there is 462.
```
Traceback (most recent call last):
  File "/home/me/.local/bin/ketos", line 6, in <module>
    from kraken.ketos import cli
  File "/home/me/.local/lib/python3.5/site-packages/kraken/ketos.py", line 462
    algn_gt: List[str] = []
           ^
SyntaxError: invalid syntax
```

**Comment by pseudomonas** [comment]
ah, looks like the typing hints here might be a feature that needs a newer Python than 3.5; in which case Kraken ought to be enforcing this with its requirements.

**Comment by mittagessen** [comment]
Enforcing a specific version of the python interpreter with pip is impossible on your distribution (presumable ubuntu 14.04). The package metadata specifies that kraken only runs on python 3.6 and upwards, if you insist on installing it on unsupported configurations I can't keep you from it.

I just saw that there's a new setuptools metadata field for fixing that but it won't work for pip<=9.0.
