### ISSUE TITLE
Kraken Installation issues - tried everything.

### ISSUE THREAD

**Issue by usag1r** [mittagessen/kraken#134]
Hello,

I have tried to install kraken library for 3-4 hours now with no avail. Could someone kindly suggest what might be wrong? Thank you.

pip install kraken / I get this error:
ERROR: No matching distribution found for coremltools (from kraken)

conda install -c mittagessen kraken / I get this error:
PackagesNotFoundError: The following packages are not available from current channels:
  - kraken

**Comment by mittagessen** [comment]
Can you run the `pip install kraken` under python 3.6? Alternatively download the environment file from [here](https://raw.githubusercontent.com/mittagessen/kraken/master/environment.yml) and run `conda env create -f environment.yml`. I think the auto-upload to the channel might be broken (again), so that's why the direct conda installation doesn't work.

**Comment by usag1r** [comment]
Hi! Thanks for the response.
Okay. I just created a fresh kraken env with your file. I confirmed python -V is 3.6.6
And I ran `pip install kraken` I get the corem1tools error as below: (last 3 lines)





(kraken) C:\Users\USA>python -V
Python 3.6.6

(kraken) C:\Users\USA>pip install kraken
Collecting kraken
  Using cached https://files.pythonhosted.org/packages/f3/69/3fbb4372a591381dc223faac73b8993670e414d1b975129d07bc745b29bc/kraken-2.0.1-py2.py3-none-any.whl
Requirement already satisfied: lxml in c:\users\usa\anaconda3\envs\kraken\lib\site-packages (from kraken) (4.3.3)
Requirement already satisfied: requests in c:\users\usa\anaconda3\envs\kraken\lib\site-packages (from kraken) (2.21.0)
Requirement already satisfied: regex in c:\users\usa\anaconda3\envs\kraken\lib\site-packages (from kraken) (2019.4.14)
Requirement already satisfied: Pillow in c:\users\usa\anaconda3\envs\kraken\lib\site-packages (from kraken) (6.0.0)
Requirement already satisfied: scipy in c:\users\usa\anaconda3\envs\kraken\lib\site-packages (from kraken) (1.2.1)
Requirement already satisfied: python-bidi in c:\users\usa\anaconda3\envs\kraken\lib\site-packages (from kraken) (0.4.0)
Requirement already satisfied: future in c:\users\usa\anaconda3\envs\kraken\lib\site-packages (from kraken) (0.17.1)
Requirement already satisfied: protobuf>=3.0.0 in c:\users\usa\anaconda3\envs\kraken\lib\site-packages (from kraken) (3.7.1)
Requirement already satisfied: jinja2 in c:\users\usa\anaconda3\envs\kraken\lib\site-packages (from kraken) (2.10.1)
Requirement already satisfied: torch>=1.0.0 in c:\users\usa\anaconda3\envs\kraken\lib\site-packages (from kraken) (1.1.0)
Requirement already satisfied: torchvision in c:\users\usa\anaconda3\envs\kraken\lib\site-packages (from kraken) (0.2.2)
Collecting coremltools (from kraken)
  **ERROR: Could not find a version that satisfies the requirement coremltools (from kraken) (from versions: none)
ERROR: No matching distribution found for coremltools (from kraken)**

**Comment by mittagessen** [comment]
Ah I see where to issue lies. Kraken only runs on Linux and Mac OS X. As quite a few dependencies aren't packaged for Windows and nobody has the time nor inclination to maintain Windows compatibility, it's unlikely it will ever be supported on there.

**Comment by usag1r** [comment]
Ah! Okay Sir. Well thanks for the explanations. The situation is more clear for me now :)
Have a nice day.
