### ISSUE TITLE
how to ocr an image cropped in opencv

### ISSUE THREAD

**Issue by MittalNeha** [mittagessen/kraken#135]
I am using opencv to text detection and want to experiment with using kraken for recognition. How can I call kraken on a cropped image, without saving it as a tif?

All the examples I see here are for running ocr on .tif file

**Comment by mittagessen** [comment]
When you use the CLI you can tell the ocr subcommand that each input file should be treated as a single line with the `-s/--no-segmentation` switch but you'll still have to save them into files. If you want to use python directly you can use the [API](http://kraken.re/api.html). Load the recognition model with `kraken.lib.models.load_any` and hand that object with a PIL Image and a segmentation to `kraken.rpred.rpred`. You'll have to repackage the opencv array to something PIL can digest though.
