### ISSUE TITLE
Error: Invalid value: cannot identify image file 'test.tiff'

### ISSUE THREAD

**Issue by Juanfree** [mittagessen/kraken#136]
Hi,

I am trying to get the OCR from an TIFF file, but always receive this error. Exist some parameter in kraken in order to show which is the problem that I am having processing this file?

Thanks.

**Comment by mittagessen** [comment]
Are you sure your input is an image? That error is thrown by PIL if it can't recognize the image format. Can you show me the actual command you're running and the output of `identify test.tiff`?
