### ISSUE TITLE
Syntax Errors in dataset.py 

### ISSUE THREAD

**Issue by AllynWaller** [mittagessen/kraken#137]
Hello. I keep receiving syntax errors when I attempt to segment a binarized image. 

File "/home/tuftscs/.local/lib/python3.5/site-packages/kraken/lib/dataset.py", line 187
    counts: Dict[Tuple[str, str], int] = Counter()

This line (and others like it) seem more like Scala syntax than Python syntax to me, although I'm not terribly familiar with either. 

Is this a Python 2 vs Python 3 issue? I'm running Python 3.5 in a Lubuntu VM. 

Thanks for any help you can provide.

**Comment by kba** [comment]
These are type hints, introduced in Python 3.5. The line you mention defines a class attribute `counts` that is a Dictonary mapping a two-string tuple to an integer number.

I think type hints on class attributes has only been introduced in Python 3.6 though.

Best to upgrade to Python 3.6+.

**Comment by mittagessen** [comment]
Yes, the minimum supported version is python 3.6, as the type hints aren't supported on 3.5. Unfortunately, you can't really force python to not install on unsupported python 3 versions. Sorry for the confusion.
