### ISSUE TITLE
Color spec raises warping error

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#138]
Hey @mittagessen , 

Running with --spec '[1,48,0,3 Cr3,3,32 Do0.1,2 Mp2,2 Cr3,3,64 Do0.1,2 Mp2,2 S1(1x12)1,3 Lbx100 Do]' from #117 raises the error :

`Error: Invalid mode RGB for line dewarping`

Any idea if I am missing a parameter ?

**Comment by mittagessen** [comment]
There's a bug in https://github.com/mittagessen/kraken/blob/eaa9f4290db5425ddf80d0aebfa3944713558ab5/kraken/lib/dataset.py#L90

that doesn't just disable the centerline normalization if the input is a 3 channel image. I've fixed it in the refactorization of the `generate_image_transforms` function as part of the new segmenter inclusion but that won't be merged until sometime next week.

**Comment by PonteIneptique** [comment]
Is there a quick fix that can be applied in the meantime ?

**Comment by mittagessen** [comment]
You can use the [dataset.py](https://github.com/mittagessen/kraken/blob/blla/kraken/lib/dataset.py) from the `blla` branch. If I didn't screw up anything (it hasn't been thoroughly tested yet) that should fix the issue.

**Comment by mittagessen** [comment]
Alternatively, you can run the head of the blla branch. It might break in the next few days as I flesh out the new segmenter but currently it works.

**Comment by PonteIneptique** [comment]
Worked like a charm with `blla`.

**Comment by amitdo** [comment]
>Alternative use a summarizing LSTM layer that doesn't need the input scaling in the first place. You really want a GPU for one of those though.

Hi,

For b/w and grayscale, what do you recommend, using the line normalizer or adding a summarizing LSTM layer?

**Comment by mittagessen** [comment]
I couldn't find any difference in accuracy between the summarizing layer and the line normalizer. Both are abysmally slow, although the summarizing layer needs an inordinately longer training time (less of a concern on GPU). As part of trying to get rid of the recurrent layers for dilated convolutions I did some preliminary tests with spatial transformer layers that could potentially replace both but the results are less than consistent.
