### ISSUE TITLE
How do you get a page bbox from segment

### ISSUE THREAD

**Issue by datavistics** [mittagessen/kraken#140]
When running kraken segment I get some high quality bounding boxes. I am using a separate ocr to process these. Im trying to create an HOCR compatible page and the last piece of information is the page level bounding box. 

What is the best way to figure this out?

Thanks!

**Comment by datavistics** [comment]
Welp, it seems its just 4 pixels greater than the original image dimensions.

**Comment by mittagessen** [comment]
The `bbox` attribute in `div[@ocr_class]` should be just the dimensions of the original image. This isn't contained in the segmenter output as the segmentation is intrinsically linked to the original image file so you should keep track externally in some way until combining the text, bounding boxes, and image in the end.
