### ISSUE TITLE
Could not find a version that satisfies the requirement coremltools.But I have installed coremltools.

### ISSUE THREAD

**Issue by InstantWindy** [mittagessen/kraken#141]
Environment : Windows 7 system, Python3.6
Version: kraken-2.0.5
Install : offline install , download 'whl' file from pypi
Error:  'Could not find a version that satisfies the requirement coremltools'. But I have installed coremltools.

Thanks!

**Comment by QuLogic** [comment]
kraken is not supported on Windows...

**Comment by InstantWindy** [comment]
Thanks!
