### ISSUE TITLE
pip3 install kraken seems to leave Kraken in a non-working state in Ubuntu

### ISSUE THREAD

**Issue by Cloudmersive** [mittagessen/kraken#142]
After running pip3 install kraken and then attempting to run this command:

kraken: Must specify DB with either --db or $KRAKEN_DEFAULT_DB

Yields this result:

kraken: Must specify DB with either --db or $KRAKEN_DEFAULT_DB

Any idea what might be happening here?

**Comment by Cloudmersive** [comment]
Any ideas on this?

**Comment by mittagessen** [comment]
Uhhm you seem to have installed a [taxonomic sequence classifier](https://ccb.jhu.edu/software/kraken/) through some other means that has a namespace clash with kraken. If you just run `ketos` without any parameters and get a short message that would confirm it. It's probably best to run separate installations.

**Comment by Cloudmersive** [comment]
Thanks, that fixed it
