### ISSUE TITLE
kraken list only showing one model and kraken not installing through conda

### ISSUE THREAD

**Issue by memorial231** [mittagessen/kraken#143]
I'm not sure if I should break these into two issues or not. My apologies for my bad etiquette if they should have been divided. I'm new to Anaconda, Python, and programming. I'm on Kubuntu 19.04.

1. I created a conda environment through `conda create --name kraken2 python=3.6.6`, activated the environment through `conda activate kraken2`, and then installed kraken into it through `pip install kraken`. Using `conda list` shows I have kraken 2.0.5 Build pypi_0 Channel pypi installed. It seemed to install normally, but when I ran `kraken list` the only model retured was `10.5281/zenodo.2577813 (pytorch) - A generalized model for English printed text`. Is there a. a way to get additional models through the Terminal and b. if not where can I download them, where should they be installed, and how can I then use them on text? 

2. I had previously tried to install kraken by downloading the environment.yml and then running `conda env create -f environment.yml`, which seemed to install fine. Running `conda list`revealed I had installed kraken 2.0.3 Build 0 Channel mittagessen. Yet when I tried to run `kraken list` all that would return would be: `Command 'kraken' not found, but can be installed with: sudo apt install kraken`
I had assumed that the problem was due to some error in my PATH (not that I'd know how to fix that), but considering my success at installing through pip in another environment, I am now not so sure.

If there is any more information that I can give, I would gladly give it.

**Comment by mittagessen** [comment]
Sorry for not responding earlier. As the model repository requires metadata that I have to get from other people first I haven't uploaded as much as I should have. There's a collection of some models at http://br.unchti.me/best.tar. The prefixes indicate what those models where trained on (cyr -> cyrillic, syr -> syriac, en -> english, everything with a proper names prefix is Arabic). You can place them whereever you want and just point kraken with the `-m` option to the `ocr` subcommand to them.

For the second issue. The envs should install directly from the git master. I tried packaging it through conda a while ago but after spending way too much time on it I gave up. So you might just have tried it during the few days when those experiments happened.

**Comment by alix-tz** [comment]
Hi @mittagessen , 

I encounter the same issue concerning installing kraken with conda. Once I ran  `conda env create -f environment.yml` (getting no error) and activated kraken's environment, I get the following message if I try a kraken command:

```
$ kraken --version

Command 'kraken' not found, but can be installed with:

sudo apt install kraken
 ```

I'm not sure how to understand your previous response: should it work or should we also give up on conda for kraken?

Many thanks!

**Comment by mrocr** [comment]
@memorial231 @alix-tz This is a working Conda environment [environment_stable.zip](https://github.com/mittagessen/kraken/files/3496842/environment_stable.zip)

**Comment by vlesu** [comment]
> There's a collection of some models at http://br.unchti.me/best.tar
Sorry url not availabe now
curl: (7) Failed to connect to br.unchti.me port 80: Connection refused

**Comment by agnagay** [comment]
> .... You can place them whereever you want and just point kraken with the `-m` option to the `ocr` subcommand to them.

Hello, first thank you for all the efforts. I´m new to kraken ( with some experience with tesseract 3.0 on windows). after a successful  installation with conda, I have installed the default model exactely as indicated in the wiki. 
next, I was looking to install the experimental [openiti](https://github.com/OpenITI) model for arabic script. I thought that doing :  `kraken get 10.5281/zenodo.3365797 `  will make it, but it gives :

```
Retrieving model .Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/kraken", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/kraken/kraken.py", line 445, in get
    partial(message, '.', nl=False))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/kraken/repo.py", line 120, in get_model
    model_url = [x['links']['self'] for x in metadata['files'] if x['type'] == 'mlmodel'][0]
IndexError: list index out of range
```
I´m on a ubuntu under WSL2. is it a correct command ? or i completely missed it and need only point the model file wereever it is as mentionned above ?

**Comment by mittagessen** [comment]
There was a small downtime but it should work again.
