### ISSUE TITLE
set_num_threads() in ketos fails

### ISSUE THREAD

**Issue by alix-tz** [mittagessen/kraken#151]
Hi,

I can't use ketos lately without getting the followong error message. Pedro and I tried to dig a bit but we couldn't find what went wrong. Do you see a way to fix this? 

![image](https://user-images.githubusercontent.com/33317799/64708880-9fff7980-d4b5-11e9-9d75-f195bfde506c.png)

Thanks!

**Comment by mittagessen** [comment]
You most likely updated to pytorch 1.2. In best python fashion they changed the API without warning or mentioning it in the changelog and setting to 0 threads doesn't work anymore. I just pushed a hotfix and tagged it as 2.0.6. It will take a few minutes until the new build is published to pypi by travis. Alternatively just downgrade pytorch to 1.1.
