### ISSUE TITLE
Using tesseract trained data in kraken

### ISSUE THREAD

**Issue by yarafatin** [mittagessen/kraken#152]
I really like kraken especially its speed and ease of setup compared to other opensource OCR tools. I am trying to use kraken to OCR a wide range of image types with varying fonts. These images could have been created from anywhere in the world, so I have no control over that. Kraken does a good job with just one default model. I tried to train and generate models but I keep getting surprises due to varying input files. One example is this file - http://www.fileformat.info/format/tiff/sample/0919217f712c4b4385c91d11b8e0e5b8/download. The quotes were not accurate in the final output. Tesseract's accuracy is slightly better probably due to the amount of trained data they have. Tesseract is too slow and I dont want to use it. I tried to the best of my ability and couldnt get it to perform better. 

My question is - Is there a way to use tesseract's trained data in kraken? I can develop some code to do the conversion but need some inputs or ideas to proceed with that.

**Comment by mittagessen** [comment]
Theoretically you should be able to use tesseract models with kraken as the primitives are the same, although in practice there might be some slight numerical differences between the hand-crafted kernels they use and our pytorch ones. Also tesseract decodes the output matrix of the network differently than kraken so there can still be differences, although they shouldn't major if no dictionary/LM is used.

The easiest way is probably decoding the serialization format of tesseract and just dumping it into an mlmodel file using something akin to the serializers in `kraken/lib/layers.py` although I've got no idea what they use. It's probably something custom as the container format itself it quite old.

**Comment by mrocr** [comment]
@yarafatin close this topic

**Comment by yarafatin** [comment]
I found the data that tesseract (https://github.com/tesseract-ocr/langdata) uses to create models. Although I didnt get a chance to train kraken with that, I think it should be good enough to get started.

**Comment by amitdo** [comment]
The right repo is https://github.com/tesseract-ocr/langdata_lstm
