### ISSUE TITLE
Line detector question: straight rectangles or polygone?

### ISSUE THREAD

**Issue by mrocr** [mittagessen/kraken#153]
@mittagessen Thank you for your hard good work,
Regarding the line extractor that you've been working on:
- Is it rectangle based, that focuses on printed documents?
- Or is it polygon based, that focuses on handwritten documents?

Because I have read the "[OCR4all](https://arxiv.org/abs/1909.04032)" Paper, and it's not clear what your final goal is.

**Comment by mittagessen** [comment]
I don't know when they have written this, so it's entirely possible that that assessment was written before the new segmenter was integrated.

The new segmenter uses a trainable baseline segmenter with traditional CV voodoo postprocessing to extend them to polygons. The current code in `blla` is stable and works but there are some issues with the polygonization for highly diacritized scripts and material with unclean binarization. There's an alternative method in the works. If you want to you can use the model trained on cBAD (Latin manuscripts) from [here](http://homer.dh.uni-leipzig.de/cbad.mlmodel) to experiment a bit. It performs quite well on other material (printed Latin and Hebrew, handwritten Arabic sucks).

**Comment by deepseek** [comment]
Though how does is perform on printed arabic text?

**Comment by mrocr** [comment]
- Though how does it perform for printed arabic text?
- Other than the ones you've mentioned, what other limitations does it have?

**Comment by mittagessen** [comment]
I haven't gotten around to train a model on printed Arabic although there's a large dataset in the works that requires me to find a quiet minute to actually validate it (it's autogenerated from existing archive.org PDF files). If you've got the inclination you could take ~100 printed Arabic pages and annotate them yourself and train a segmentation model (`ketos segtrain` in the blla branch). It shouldn't take more than a minute a page for book-type printing for the annotation.

There's a fundamental issue with crossing (base-)lines that this method (or any other baseline method out there) can't deal with and right now it assumes that lines aren't written in their head but there's a fairly easy fix that's going to get implemented as soon as the new polygonizer is finished.
