### ISSUE TITLE
No blla.mlmodel for kraken segment

### ISSUE THREAD

**Issue by alix-tz** [mittagessen/kraken#158]
Hi, 

I'm working on a config based on the `blla` branch. 

I wanted to compare the results given by our model to the results given by the "default" model (assuming `kraken -i img.tif lines.json segment` would do). 

Unfortunately, the command doesn't work unless I input a model file, because the default value points to a .mlmodel file that does not exist.

Is there any default model I could use ?

```
Error: Invalid value for "-i" / "--model": Path "[...]/envs/kraken_blla/lib/python3.6/site-packages/kraken/blla.mlmodel" does not exist.
```

https://github.com/mittagessen/kraken/blob/d3cf5d2a44cabafe7ed035c8bd01ea1f46ffd83a/kraken/kraken.py#L260

**Comment by mrocr** [comment]
@alix-tz 
For CPU Training:
```
ketos segtrain --threads 4 -t ./train/* -o ./models/ 
```

For GPU Training:
The `set_num_threads` value is not changed using `--threads`, therefor below is  workaround:
- In `vgsl.py`change:
```
def set_num_threads(self, num: int) -> 1:
```
```
        torch.set_num_threads(1)
```
and then run the blla training:
```
ketos segtrain --threads 4 -t ./train/* -o ./models/ -d cuda:0
``` 

Ps: you can also change the vgsl values after kraken installation, by going to the environment folders:
`/home/home/anaconda3/envs/yourenvironment/lib/python3.6/site-packages/kraken/lib`


For Detecting using the trained model:
```
kraken -i 1.png lines.json binarize segment -i ./best.mlmodel
```

For Visualizing the detected baselines:
```
python heatmap_overlay.py best.mlmodel image.png
```

For visualizing the detected boundary you need to convert the point to a labelme format.

@mittagessen  close this issue

**Comment by mittagessen** [comment]
* Alix Chagué :: 2019-11-05 16:16 Tue:
> Hi, 
> 
> I'm working on a config based on the `blla` branch. 
> 
> I wanted to compare the results given by our model to the results given by the "default" model (assuming `kraken -i img.tif lines.json segment` would do). 
> 
> Unfortunately, the command doesn't work unless I input a model file, because the default value points to a .mlmodel file that does not exist.
> 
> Is there any default model I could use ?

Sorry I haven't trained one yet that produces decent resuts across a
wide range of scripts. For Latin you could use
http://br.unchti.me/offsplit.mlmodel, trained on cbad 2017.

**Comment by mrocr** [comment]
@alix-tz Is this issue solved?
