### ISSUE TITLE
Visualizing & Extracting the detected lines [blla] 

### ISSUE THREAD

**Issue by mrocr** [mittagessen/kraken#159]
@mittagessen 
How to visualize & extract the detected lines?
The `boundary` boxes

**Comment by mittagessen** [comment]
* mrocr :: 2019-11-08 16:50 Fri:
> @mittagessen 
> How to visualize & extract the detected lines?
> The `boundary` boxes

Use the kraken code. There's an overlay script in kraken/contrib/.

**Comment by mrocr** [comment]
The `heatmap_overlay.py` outputs the `baseline` map, but how to visualize the `boundary` the final detected boxes?

```
kraken -i 1.png lines.json binarize segment -i ./best.mlmodel
```

**Comment by mrocr** [comment]
solved using an icdar to labelme converter

**Comment by mryolanda** [comment]
> solved using an icdar to labelme converter

@mrocr Could you please describe me how you have solved this ? Thanks !
