### ISSUE TITLE
The Boundary Detector

### ISSUE THREAD

**Issue by mrocr** [mittagessen/kraken#160]
@mittagessen 
What is next for the `boundary` detector? I tested the detector and the results need improvements.
What are your thought about [my baseline](https://github.com/mittagessen/kraken/issues/155#issuecomment-552044566) results and my [boundary](https://github.com/mittagessen/kraken/issues/155#issuecomment-552055222) results?

The dataset is available at [dropbox](https://www.dropbox.com/s/8vwnuzo8pmy0wls/train.zip?dl=0)

**Comment by deepseek** [comment]
@mittagessen After I updated to the latest master as of today, the results for the `boundary` are just Line points, they are not polygons...
so whats going on man?
[boundary lines.zip](https://github.com/mittagessen/kraken/files/3846181/boundary.lines.zip)

**Comment by mrocr** [comment]
@mittagessen After I updated to the latest master as of today, the results for the `boundary` are just Line points, they are not polygons...
so whats going on man?
[boundary lines.zip](https://github.com/mittagessen/kraken/files/3846181/boundary.lines.zip)

**Comment by mittagessen** [comment]
* mrocr :: 2019-11-14 12:22 Thu:
> @mittagessen After I updated to the latest master as of today, the
> results for the `boundary` are just Line points, they are not
> polygons...  so whats going on man?

The old polygonisation by interline distance estimation didn't work
reliably and had certain fundamental issues. I've got something else in
the works.

**Comment by mrocr** [comment]
Keep up the good work.
