### ISSUE TITLE
Blla - boxes and OCR

### ISSUE THREAD

**Issue by mryolanda** [mittagessen/kraken#162]
Hi,

Is there a way to use the `kraken ocr` command in the blla branch ? When I am trying to use a trained model for segmentation, the ocr command fails.

`Traceback (most recent call last):
[...]
ValueError: zero-size array to reduction operation minimum which has no identity`

The json output of the segment command (blla branch) is of course different from the basic json output (master branch), but I don't see any detected boxes in this (only baseline). How could it be possible to extract boxes and process recognition from this json ?
Thanks !

**Comment by deepseek** [comment]
@mryolanda why did you close?
