### ISSUE TITLE
sbb_textline_detector

### ISSUE THREAD

**Issue by mrocr** [mittagessen/kraken#164]
@mittagessen have a look here https://github.com/qurator-spk/sbb_textline_detector
they have an excellent implementation, which is able to polygonize the mask 

which they created using:
https://github.com/vahidrezanezhad/pixelwise_segmentation_SBB
https://github.com/vahidrezanezhad/textline_detector

**Comment by mittagessen** [comment]
* mrocr :: 2019-12-09 23:51 Mon:
> @mittagessen have a look here https://github.com/qurator-spk/sbb_textline_detector
> they have an excellent implementation, which is able to polygonize the mask 

We've got a prototype that produces good polygons from baselines for a
few weeks now (we independently arrived at the bounding env + seam
carving) which will be ported into kraken before christmas. The SBB
detector uses full line masks which are a pain to annotate and don't
really work for manuscripts.

**Comment by mrocr** [comment]
Keep up the good work

**Comment by deepseek** [comment]
@mittagessen 
:)

**Comment by mrocr** [comment]
@mittagessen 
:)
