### ISSUE TITLE
Can't train a model with Ketos

### ISSUE THREAD

**Issue by xuyin666** [mittagessen/kraken#166]
Hello, 

I have an issue with Ketos. 

I tried to train a model as the document shows(kraken.re). 

First I did the transcriptions using the command `ketos transcribe -o output.html image_1.png image_2.png ...` . Then I want to use the `ketos extract --output output_directory --normalization NFD *.html`. The commend executes. The result expected should be a directory filled with line image text pairs NNNNNN.png and NNNNNN.gt.txt and a manifest.txt containing a list of all extracted lines. But the result that I got is only a directory with an empty manifest.txt. 

Because of this problem, i couldn't pass the next step to train un model with the command `ketos train output_dir/*.png`

Could anyone tell me what's the problem?

**Comment by mrocr** [comment]
@xuyin666 
It seems that you didn't save the transcribed html.
What you need to do is export the html, type each line, then `ctrl+s` to save the html.

Close this issue dear

**Comment by xuyin666** [comment]
Thanks a lot !!!!
