### ISSUE TITLE
Add a repolygonization script to contrib

### ISSUE THREAD

**Issue by mittagessen** [mittagessen/kraken#168]
We need a script to read in an existing baseline segmentation with polygons from PAGE/ALTO, repolygonize it using the internal kraken polygonizer, and serialize the new segmentation to one of the supported formats.

**Comment by mrocr** [comment]
@mittagessen 
Correct me if I am wrong, what is needed is:
Dataset input xml files containing baselines **>**  kraken's baselines to lines **>** output xml containing lines
If you can clarify what you want with an image, that would be great.

Questions:
- `existing baseline segmentation` from the input dataset, or detected baseline output by kraken?
- Does the new kraken polygonizer use a trained model? or pure algorithm?
- Are you sure that the kraken polygonizer fully functional? and is able to detect the lines excellently?
- Does the kraken polygonizer detects lines only, or does it also detect regions, pages? no. classes
- What output format is required, and what version? Page-xml version 2013, alto 3.0???
- Send the link to the internal kraken polygonizer file here.

**Comment by mittagessen** [comment]
Solved
