### ISSUE TITLE
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL'

### ISSUE THREAD

**Issue by aps9** [mittagessen/kraken#170]
Error message:
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL'

Steps to repeat:
(1) Install Kraken.
(2) Put a TIFF file (image.tif) in the current path.
(3) Run commands:
conda activate kraken
kraken -i image.tif bw.png binarize
kraken -i bw.png lines.json segment

The issue is described elsewhere:
https://github.com/python-pillow/Pillow/issues/4130
The problem is that Pillow 7.0.0 has deprecated a constant that was used by torchvision, but the issues is fixed in torchvision 0.5.0, which in turn requires pytorch 1.4.0.

It can be fixed in the environment yml file:
(1) by pinning pillow==6.1, or 
(2) by using torchvision 0.5.0 which in turn requires pytorch 1.4.0

I don't know what side effects these changes would have.  Pinning pillow is probably the safest solution for now, but it would be nice to move forward with version numbers eventually.

**Comment by mittagessen** [comment]
* aps9 :: 2020-01-27 23:15 Mon:
> I don't know what side effects these changes would have.  Pinning
> pillow is probably the safest solution for now, but it would be nice
> to move forward with version numbers eventually.

Unfortunately, pytorch deprecates cuda versions relatively aggressively
which can cause problems in cluster setups so I agree pinning pillow
seems to be the best solution to keep compatiblity with pytorch 1.0 for
now. I'll do it sometime over the next few days as I'm travelling right
now.
