### ISSUE TITLE
blla_regions training data structure?

### ISSUE THREAD

**Issue by deepseek** [mittagessen/kraken#172]
@mittagessen 
using the blla_regions branch as of today, and a sample of the badam dataset, I get error at training.
Did you change the groundtruth structure? upload a sample of the accepted data groundtruth.
```
Creating model [1,1200,0,3 Cr3,3,64,2,2 Gn32 Cr3,3,128,2,2 Gn32 Cr3,3,64 Gn32 Lbx32 Lby32 Cr1,1,32 Gn32 Lby32 Lbx32 O2l2] with 2 outputs ✓
Training line types:
Training region types:

.
.
.
  File "/home/home/anaconda3/envs/k2/lib/python3.7/site-packages/kraken/lib/dataset.py", line 784, in __getitem__
    im = Image.open(im)
  File "/home/home/anaconda3/envs/k2/lib/python3.7/site-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file './train/img-1008.plain.path'
```

**Comment by mittagessen** [comment]
The regions thing is still work in progress but that is a bug. In
general it probably won't work with the path-style training data but
ALTO and PageXML files as those have already all the data in there.
Training everything should work but the postprocessing is not tied
together, yet.

**Comment by deepseek** [comment]
keep up the good work
