### ISSUE TITLE
error on ketos train with --augment

### ISSUE THREAD

**Issue by dstoekl** [mittagessen/kraken#174]
There is a complaint about a missing module albumentations in dataset.py line 390 when setting --augment on ketos train. Probably need to add albumentations in requirements.txt

**Comment by mittagessen** [comment]
* Daniel Stoekl :: 2020-02-18 20:22 Tue:
> There is a complaint about a missing module albumentations in
> dataset.py line 390 when setting --augment on ketos train. Probably
> need to add albumentations in requirements.txt

You have to install albumentations. It's required for augmentation but
otherwise optional but it pulls in a few hundred Mb of OpenCV. OpenCV
can be tricky to install on some platforms so I'd prefer not to make it
mandatory.
