### ISSUE TITLE
Ketos options blla

### ISSUE THREAD

**Issue by paulo170** [mittagessen/kraken#179]
Hi,

There is a repolygonize options for the ketos command. I would like to know if it means we can train a char recognizer with xml containing the GT relative to a baseline ?
If yes, is the repolygonize command can be use with a personal blla model ? How to control that the repolygonization is clean ?

Thx !

**Comment by mittagessen** [comment]
> There is a repolygonize options for the ketos command. I would like to
> know if it means we can train a char recognizer with xml containing
> the GT relative to a baseline ?

Yes, you feed in XML files containing at least baseline information and
text to train a text recognition model. If there are line bounding
polygons in the XML they are used to extract the lines during training
per default, the repolygonize option overrides these and uses kraken's
implementation. That's mostly useful if the polygons are erroneous or
have been produced by a software you don't have access to in the OCR
pipeline.

> If yes, is the repolygonize command can be use with a personal blla
> model ? 

I don't understand what you mean with that.

> How to control that the repolygonization is clean ?

There are scripts in contrib/. repolygonize_* and extract_polygons_*.
They are a bit messy right now but can be used to see how the
rectified line patches the network sees look like.

**Comment by paulo170** [comment]
Thx !

> I don't understand what you mean with that.

In fact, I would like to know if there was a way to control the repolygonization (how to make sure that the polygon is correct and the line complete, and correspond well to the text) ?

**Comment by mittagessen** [comment]
> In fact, I would like to know if there was a way to control the
> repolygonization (how to make sure that the polygon is correct and the
> line complete, and correspond well to the text) ? 

As mentioned the easiest way is to run the repolygonize_*.py to replace
the polygons in the ALTO/PageXML and extract them afterwards with the
extract_polygons_*.py.
