### ISSUE TITLE
Is there a pre-trained model sharing location on the web? where can I contribute mine?

### ISSUE THREAD

**Issue by shula** [mittagessen/kraken#181]
1. I want to start training few public domain models.  Where should I put them?
2. I'd like to start from a pre-existing model.  Is there public-domain Hebrew model I can use for  starting-up?

Thanks.

**Comment by mittagessen** [comment]
There's a public repository built into kraken that's hosted on [zenodo](http://zenodo.org). You need an account on there and have to create an access token. Afterwards you can publish models with `ketos publish`.

We've got some specialized Hebrew manuscript models laying around but nothing for print or the like.
