### ISSUE TITLE
@click.option('-i', '--model' requires blla.mlmodel to exist, even if  legacy box segmenter used

### ISSUE THREAD

**Issue by brobertson** [mittagessen/kraken#182]
Because ' type=click.Path(exists=True)' is set on this option, the blla.mlmodel file has to exist, even if --boxes switch is set. 

(Additionally, it seems that a default blla.mlmodel is not currently included in the github repository.)

This can be temporarily obviated by 'touch $SOMEPATH/kraken/lib/python3.7/site-packages/kraken/blla.mlmodel'

**Comment by mittagessen** [comment]
fixed through setting the default to `None`.

**Comment by brobertson** [comment]
Thanks!
