### ISSUE TITLE
noisy file can hang segmenter

### ISSUE THREAD

**Issue by brobertson** [mittagessen/kraken#183]
A noisy file can cause thousands of lines to be identified, and sorting these will take the segmenter a very long time. When batch scanning from sources like archive.org, it is better that the file be skipped. (I've written up a --linelimit/-t option to 'segment' for this purpose, but I'm not sure exactly how to make a pull request against your most current work.)

**Comment by mittagessen** [comment]
* Bruce Robertson :: 2020-03-06 19:49 Fri:
> A noisy file can cause thousands of lines to be identified, and
> sorting these will take the segmenter a very long time. When batch
> scanning from sources like archive.org, it is better that the file be
> skipped. (I've written up a --linelimit/-t option to 'segment' for
> this purpose, but I'm not sure exactly how to make a pull request
> against your most current work.)

I haven't seen that yet but can believe it (the recursive reading order
determination sometimes went over the recursion limit on bad
segmentations). Could you show me one of the images and ideally hand me
the model you tried it on? There might be some easy postprocessing
filtering that will remove enough noise to make it workable again.

**Comment by brobertson** [comment]
Here's two pages from a representative volume, with their corresponding times:
time kraken -i  ~/Slurm-experiments/OCR_Output/nnc1.50178386-1593613693/nnc1.50178386-1593613693-PNG-500/nnc1.50178386-1593613693_0044.png /tmp/out2.html binarize segment --boxes --maxcolseps 0  -w -r ocr -h -m ~/retrain-kraken-clement2/kraken_clement2_best.mlmodel 
Loading ANN default	✓
Binarizing	✓
Segmenting	✓
Processing  [####################################]  100%          
Writing recognition results for /home/brucerob/Slurm-experiments/OCR_Output/nnc1.50178386-1593613693/nnc1.50178386-1593613693-PNG-500/nnc1.50178386-1593613693_0044.png	✓

real	0m9.486s
user	0m9.233s
sys	0m0.229s

 time kraken -i  ~/Slurm-experiments/OCR_Output/nnc1.50178386-1593613693/nnc1.50178386-1593613693-PNG-500/nnc1.50178386-1593613693_0004.png /tmp/out2.html binarize segment --boxes --maxcolseps 0  -w -r ocr -h -m ~/retrain-kraken-clement2/kraken_clement2_best.mlmodel 
Loading ANN default	✓
Binarizing	✓
Segmenting	^C
Aborted!

real	8m16.190s
user	8m15.792s
sys	0m0.245s

![nnc1 50178386-1593613693_0044](https://user-images.githubusercontent.com/34581/89209939-9ed7af00-d595-11ea-913b-380dcab99850.png)
![nnc1 50178386-1593613693_0004](https://user-images.githubusercontent.com/34581/89209959-a434f980-d595-11ea-8fb1-2f32133a5e59.png)

**Comment by brobertson** [comment]
Sorry, you wanted the model, too (though I note that when I cancelled the process above, it was still on the segmentation process) 
[kraken_clement2_best.zip](https://github.com/mittagessen/kraken/files/5017459/kraken_clement2_best.zip)

**Comment by pverkind** [comment]
Hi Bruce, have you tried using pdfimages to extract the image files from such scans made by Microsoft? Each page contains 4 separate layers, of which the last contains only the ink on the page, without background. I think this might be helpful for this specific type of scans.

**Comment by brobertson** [comment]
Thanks, @mittagessen !
