### ISSUE TITLE
Word bboxes in hocr do not comprise entire word

### ISSUE THREAD

**Issue by brobertson** [mittagessen/kraken#184]
The hocr output from kraken 3.0b3 with legacy segmenter creates bounding boxes like this:
![out](https://user-images.githubusercontent.com/34581/76113243-29ea5400-5fba-11ea-8725-8cebf2fcb735.png)

Here, spaces are treated as 'words', and the x1 and x2 limits tend to be within the limits of the word. This makes it difficult to use bbox information to re-recognize or re-train from the hocr output.

I've written a python script for consideration that:
a) removes the words that are spaces
b) evenly assigns all space between words to each of them
c) pushes the edges of left-most and right-most words in a line to their margins
d) converts the output to XHTML
e) optionally generates a more easily-accessible summary of the word accuracy using html 5 'data-' attributes

Its resulting bounding boxes look like this:
![out2](https://user-images.githubusercontent.com/34581/76113257-2f479e80-5fba-11ea-8923-dcd339e42a81.png)

**Comment by mittagessen** [comment]
* Bruce Robertson :: 2020-03-06 19:58 Fri:
> The hocr output from kraken 3.0b3 with legacy segmenter creates bounding boxes like this:
> ![out](https://user-images.githubusercontent.com/34581/76113243-29ea5400-5fba-11ea-8725-8cebf2fcb735.png)
> 
> Here, spaces are treated as 'words', and the x1 and x2 limits tend to
> be within the limits of the word. This makes it difficult to use bbox
> information to re-recognize or re-train from the hocr output.

Yes, currently 'words' are generated by the Unicode word segmentation
algorithm and serialized in a `word - separator - word
- separator ...` fashion. As the separators can be semantically useful
information (especially in non-Latin scripts) they have to be
serialized. Putting them in words was just the easiest way to not have
them floating around outside the normal element hierarchy.

The word bounding boxes being smaller than previously is an artefact of
the CTC training. The old implementation was quite peculiar in producing
drawn out activations for each character while the new one has the
standard peaked activations that do not extent across all of the
grapheme on the page. This is also the reason why the script detection
doesn't work anymore. There are half a dozen reasons why the new
implementation is better.

> I've written a python script for consideration that:
> a) removes the words that are spaces
> b) evenly assigns all space between words to each of them
> c) pushes the edges of left-most and right-most words in a line to their margins
> d) converts the output to XHTML
> e) optionally generates a more easily-accessible summary of the word accuracy using html 5 'data-' attributes

If you want I can put it in the contrib/ directory that contains all the
helper scripts.

**Comment by brobertson** [comment]
Sure, here's the code
[normalize_hocr.zip](https://github.com/mittagessen/kraken/files/5017529/normalize_hocr.zip)

**Comment by Schneipi** [comment]
I have the same problem with a custom trained model: The width of the bounding boxes for individual characters is too small (sometimes 0). That's why it especially shows for single character words. Is there a way too fix this? Thanks in advance.
![example](https://user-images.githubusercontent.com/12519907/95720639-cb810480-0c71-11eb-9ceb-ccd91c48bc4e.png)

**Comment by mittagessen** [comment]
* Schneipi :: 2020-10-12 10:01 Mon:
> I have the same problem with a custom trained model: The width of the bounding boxes for individual characters is too small (sometimes 0). That's why it especially shows for single character words. Is there a way too fix this? Thanks in advance.
> ![example](https://user-images.githubusercontent.com/12519907/95720639-cb810480-0c71-11eb-9ceb-ccd91c48bc4e.png)

Unfortunately, there's not much "algorithmically" wrong with this output
as mentioned above. Locations are an conincidental artifact of the text
prediction of the neural network, so they aren't trained as such. 

You can try Bruce's script above which has makes some assumptions on how
text looks like that most likely hold true for printed French.

**Comment by Schneipi** [comment]
Thanks for the quick response.
