### ISSUE TITLE
repolygonize.py inserts polygons at wrong baselines

### ISSUE THREAD

**Issue by dstoekl** [mittagessen/kraken#189]
The polygon is correctly calculated but inserted at the wrong place in the xml. Please check document 344 part 27430 by clicking on one of the masks of the bottom lines which will activate also the associated baselines which are at completely different locations. I will send you the files by mail, too.
![image](https://user-images.githubusercontent.com/39535215/77475939-e5fca900-6e19-11ea-8b4c-a2b8c64ec0dd.png)

**Comment by dstoekl** [comment]
One test: The current code does not create polygons for baselines without polygons. This is the case for any manually created line in eScriptorium.

**Comment by deepseek** [comment]
- upload the files here.
- which branch of eScriptorium did you use

**Comment by mrocr** [comment]
- upload the files here.
- which branch of eScriptorium did you use

**Comment by mittagessen** [comment]
script has been rewritten.
