### ISSUE TITLE
Bad boundaries on top or bottom line

### ISSUE THREAD

**Issue by dstoekl** [mittagessen/kraken#192]
The current seamcarve is often influenced by the manuscript edge on the top or bottom and includes all the area above the top line or below the bottom line inside the polygon which leads to really bad transcription results for these lines (sometimes around 50%).

**Comment by deepseek** [comment]
post image example and polygon heatmap

**Comment by dstoekl** [comment]
impossible. copyrighted material.

**Comment by deepseek** [comment]
:sunglasses: 
use an example, a similar image that you searched to demonstrate the issue.
