### ISSUE TITLE
Dict not defined and cudnn error

### ISSUE THREAD

**Issue by paulo170** [mittagessen/kraken#194]
Hi,

When using the new Master branch, I get the following error when I am trying to use a blla model.

`Failed processing test.tif: name 'Dict' is not defined `

And when trying to train a new blla model, I have the following error : 

`RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.`

The input is exactly the same than before the new Master branch and everything worked well in the blla branch.
Thanks !

**Comment by mittagessen** [comment]
I might have screwed up the merge. For the CUDNN error, did you
reinitialize the virtual environment? I bumped the pytorch version to
1.4.0 which defaults to CUDA 10 so you might be affected by this bug
[0]. Downgrading to CUDA 9 had resolved the issue for us.


[0] https://github.com/pytorch/pytorch/issues/32395

**Comment by paulo170** [comment]
solved, thanks !
