### ISSUE TITLE
Extracting transcribed images generates empty manifest file and no image label pairs

### ISSUE THREAD

**Issue by naveedunjum** [mittagessen/kraken#201]
After transcribing, when i use the `extract`command, only manifest text file is generated. That too is empty, the png and txt pairs are not generated at all. Please help

**Comment by mittagessen** [comment]
* Naveed Unjum :: 2020-05-18 10:33 Mon:
> After transcribing, when i use the `extract`command, only manifest
> text file is generated. That too is empty, the png and txt pairs are
> not generated at all. Please help

This happens if you don't save the HTML files after transcription. Which
browser are you using? I think chrome and firefox work reliably but the
whole interface is a legacy affair now with the new segmenter which
doesn't have a kraken-internal interface for ground truth creation
anymore.

**Comment by naveedunjum** [comment]
I tried on both chrome and firefox and I did use the download button. The sentences are saved in html file but still issue prevails. I tried this for only one or two images, is it possible that may have caused the issue? And is there a workaround for now?

**Comment by mittagessen** [comment]
* Naveed Unjum :: 2020-05-18 22:46 Mon:
> I tried on both chrome and firefox and I did use the download button. The sentences are saved in html file but still issue prevails. I tried this for only one or two images, is it possible that may have caused the issue? And is there a workaround for now?


Can you try saving with CTRL+S? And make sure that you selected the "web
page, complete" mode when saving?

**Comment by naveedunjum** [comment]
It worked. Thanks. Should've tried this at least. Silly me.
