### ISSUE TITLE
Error in models.py

### ISSUE THREAD

**Issue by pharos-alexandria** [mittagessen/kraken#203]
If I do `ketos test -m model_best.mlmodel training/*.png`, I receive this error:

``` python
File "/venv/lib/python3.8/site-packages/kraken/lib/models.py", line 78, in forward
    line = line.to(self.device)
AttributeError: 'str' object has no attribute 'to'
```

**Comment by mittagessen** [comment]
Sorry, that was another regression from the batches merge. It should work now and be significantly faster than before.
