### ISSUE TITLE
Alphabet mismatch during training

### ISSUE THREAD

**Issue by naveedunjum** [mittagessen/kraken#205]
here's the error I get
 `alphabet mismatch: chars in training set only: {'ۯ', 'ح', 'ڈ', 'ٗ', 'ۍ', 'ع', 'ٹ', '،', 'ژ', 'خ', 'ٖ', 'ڑ', 'ذ', 'غ', 'ف', 'ظ', 'ص', 'ض', 'ٓ'} (not included in accuracy test during training)`
I am training this on a rather small dataset just to check out the working. Gave me the above error. With English language as well, same error. Should I increase the dataset or is there something else going on? please help

**Comment by mittagessen** [comment]
* Naveed Unjum :: 2020-05-21 19:32 Thu:
> here's the error I get `alphabet mismatch: chars in training set only:
> {'ۯ', 'ح', 'ڈ', 'ٗ', 'ۍ', 'ع', 'ٹ', '،', 'ژ', 'خ', 'ٖ', 'ڑ', 'ذ', 'غ',
> 'ف', 'ظ', 'ص', 'ض', 'ٓ'} (not included in accuracy test during
> training)` I am training this on a rather small dataset just to check
> out the working. Gave me the above error. With English language as
> well, same error. Should I increase the dataset or is there something
> else going on? please help

If you're training based on another dataset or restarting training with
the same (small) dataset the repertoire of unicode code points won't be
the same as on the initial training run. Per default kraken aborts here.
You can let kraken hammer the output layer into the correct shape for
the new alphabet with the --resize add/both options that are documented
[0]. Most likely you should do a manual split of your data between
training and validation set and use the -t/-e options to not
accidentally mix previous training data into your validation set.

[0] http://kraken.re/ketos.html#fine-tuning

**Comment by naveedunjum** [comment]
Sorry for taking some time to reply. 
I am training a model from scratch so don't have a pretrained model. So I can't use the resize option. 

While trying to manually seperate the training and validation set, I run in some trouble. Could you please provide the whole command assuming a training folder with train folder and valid folder. Where do I put my manifest file. I tried training on `training` folder keeping manifest here and designating `train` and `valid` with the options. Didn't work.

I am training for a new language which has some additional characters than arabic and has completely different words. Would you suggest keeping that as base or training from scratch? 
Help will be appreciated.

**Comment by mittagessen** [comment]
> While trying to manually seperate the training and validation set, I
> run in some trouble. Could you please provide the whole command
> assuming a training folder with train folder and valid folder. Where
> do I put my manifest file. I tried training on `training` folder
> keeping manifest here and designating `train` and `valid` with the
> options. Didn't work.

$ ketos train -t train.txt -e valid.txt

or

$ ketos train -e valid.txt training/*.png

Basically once you set the validation set that overrides the random
partition and you can add training data with both the `-t` option and as
a last argument. The manifests just contain the paths to all the
images, one per line. 

> I am training for a new language which has some additional characters
> than arabic and has completely different words. Would you suggest
> keeping that as base or training from scratch? 

If it's something like Urdu that has a fairly different typographic
style it probably isn't worth it to start from an existing naskh model.

**Comment by naveedunjum** [comment]
I was kinda discouraged by persistent errors on kraken. So was looking at alternate options. So I forgot posting here. In dealing with the above errors, i thought maybe the data was too small, as such the training and val sets might be getting some extra characters not present in other. So i tried a single sentence for all the lines. This time the error didnt repeat. So maybe the data too small. So I will try expanding my dataset and first try this on English, hopefully will work. 

But another error persists which I had been overlooking. The error is
 `NameError: name 'collate_sequences' is not defined`. In the `train.py` file, this argument is not passed. How do i remove this one? I have attached the error pic





![image](https://user-images.githubusercontent.com/37370766/83977153-e2a69300-a91b-11ea-9659-07d28b72cf67.png)

**Comment by mittagessen** [comment]
You're running master which sometimes breaks because it's the active development version. Any version younger than 7a94744d has this error fixed. For your purposes the latest stable version should be sufficient.

For your original problem I just now realize this isn't even the error I was thinking of but just a warning that informs you that not all code points in the training set will be evaluated in the validation set as the random sample doesn't contain them. You can just ignore that one if you're aware that your sets are fairly small and the estimate will therefore have a fairly high variance.

**Comment by naveedunjum** [comment]
Pulled the new commits and it worked. Thanks.
