### ISSUE TITLE
QhullError

### ISSUE THREAD

**Issue by paulo170** [mittagessen/kraken#206]
Hi,

Since the merge of batch branch, I get the following error when trying to train from xml files.

`
  File "../miniconda/envs/kraken/lib/python3.7/site-packages/skimage/transform/_geometric.py", line 892, in estimate
    self._inverse_tesselation = spatial.Delaunay(dst)
  File "qhull.pyx", line 1839, in scipy.spatial.qhull.Delaunay.__init__
  File "qhull.pyx", line 357, in scipy.spatial.qhull._Qhull.__init__
scipy.spatial.qhull.QhullError: QH6154 Qhull precision error: Initial simplex is flat (facet 1 is coplanar with the interior point)
`

Would you have an idea how to solve that? Thx

**Comment by mittagessen** [comment]
* paulo170 :: 2020-05-26 09:55 Tue:
> Hi,
> 
> Since the merge of batch branch, I get the following error when trying to train from xml files.
> 
> `
>   File "../miniconda/envs/kraken/lib/python3.7/site-packages/skimage/transform/_geometric.py", line 892, in estimate
>     self._inverse_tesselation = spatial.Delaunay(dst)
>   File "qhull.pyx", line 1839, in scipy.spatial.qhull.Delaunay.__init__
>   File "qhull.pyx", line 357, in scipy.spatial.qhull._Qhull.__init__
> scipy.spatial.qhull.QhullError: QH6154 Qhull precision error: Initial simplex is flat (facet 1 is coplanar with the interior point)
> `
> 
> Would you have an idea how to solve that? Thx

Hmmm it should skip non-rectifiable lines. It might be another merge
regression. I'll check.

**Comment by paulo170** [comment]
I see, thx! In which cases do you consider that the line is non-rectifiable (e.g. too many coordinates?)? Because before the merge, I had no problem with the same dataset.

**Comment by mittagessen** [comment]
> I see, thx! In which cases do you consider that the line is
> non-rectifiable (e.g. too many coordinates?)? Because before the
> merge, I had no problem with the same dataset.

It's mostly bounding polygons that can't be triangulated which is
necessary for the piecewise affine transformation that maps it onto a
plane around the straight baseline. But the triangulation happens in an
arcane library behind scipy whose error conditions are not always
immediately obvious.

I think it this case I accidentally removed the check for duplicate
polygon/baseline points during the conflict resolution. Give me a few
hours to fix it, I've only got one hand right now.

**Comment by mittagessen** [comment]
I've added some more checks to the xml parser but frankly the extraction
code is unchanged since january and the replacement code in the dataset
works as intended. maye you're not running master?

If the latest commit don't change anything could you run ketis at a
higher verbosity (-vvv) and show the ouput just before the crash happens
including all crash output?

**Comment by stweil** [comment]
@mittagessen, during the last 6 days this error occurred 10 times on our eS instance which is still running kraken 4.3.13:
```
Traceback (most recent call last):
  File "/escriptorium/app/apps/core/tasks.py", line 648, in transcribe
    part.transcribe(model, transcription, user=user)
  File "/escriptorium/app/apps/core/models.py", line 1434, in transcribe
    for pred in it:
  File "/venv3.11/lib/python3.11/site-packages/kraken/rpred.py", line 635, in __next__
    return self.next_iter(bound)
  File "/venv3.11/lib/python3.11/site-packages/kraken/rpred.py", line 586, in _recognize_baseline_line
    box, coords = next(extract_polygons(self.im, line))
  File "/venv3.11/lib/python3.11/site-packages/kraken/lib/segmentation.py", line 1065, in extract_polygons
    tform.estimate(src_points, dst_points)
  File "/venv3.11/lib/python3.11/site-packages/skimage/transform/_geometric.py", line 978, in estimate
    self._tesselation = spatial.Delaunay(src)
  File "_qhull.pyx", line 1841, in scipy.spatial._qhull.Delaunay.__init__
    <source code not available>
  File "_qhull.pyx", line 353, in scipy.spatial._qhull._Qhull.__init__
    <source code not available>

Exception Type: QhullError
Exception Value: QH6154 Qhull precision error: Initial simplex is flat (facet 1 is coplanar with the interior point)

While executing:  | qhull d Q12 Qbb Qc Qz Qt
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 779359952  delaunay  Q12-allow-wide  Qbbound-last  Qcoplanar-keep
  Qz-infinity-point  Qtriangulate  _pre-merge  _zero-centrum  Qinterior-keep
  Pgood  _max-width 59  Error-roundoff 8.2e-14  _one-merge 5.7e-13
  Visible-distance 1.6e-13  U-max-coplanar 1.6e-13  Width-outside 3.3e-13
  _wide-facet 9.8e-13  _maxoutside 6.5e-13

The input to qhull appears to be less than 3 dimensional, or a
computation has overflowed.

Qhull could not construct a clearly convex simplex from points:
- p1(v4):    30     2    14
- p8(v3):    31     2    59
- p2(v2):    59     2    54
- p0(v1):     0     2     0

The center point is coplanar with a facet, or a vertex is coplanar
with a neighboring facet.  The maximum round off error for
computing distances is 8.2e-14.  The center point, facets and distances
to the center point are as follows:

center point     30.1        2    31.62

facet p8 p2 p0 distance=    0
facet p1 p2 p0 distance=    0
facet p1 p8 p0 distance=    0
facet p1 p8 p2 distance=    0

These points either have a maximum or minimum x-coordinate, or
they maximize the determinant for k coordinates.  Trial points
are first selected from points that maximize a coordinate.

The min and max coordinates for each dimension are:
  0:         0        59  difference=   59
  1:         2         2  difference=    0
  2:         0        59  difference=   59

If the input should be full dimensional, you have several options that
may determine an initial simplex:
  - use 'QJ'  to joggle the input and make it full dimensional
  - use 'QbB' to scale the points to the unit cube
  - use 'QR0' to randomly rotate the input for different maximum points
  - use 'Qs'  to search all points for the initial simplex
  - use 'En'  to specify a maximum roundoff error less than 8.2e-14.
  - trace execution with 'T3' to see the determinant for each point.

If the input is lower dimensional:
  - use 'QJ' to joggle the input and make it full dimensional
  - use 'Qbk:0Bk:0' to delete coordinate k from the input.  You should
    pick the coordinate with the least range.  The hull will have the
    correct topology.
  - determine the flat containing the points, rotate the points
    into a coordinate plane, and delete the other coordinates.
  - add one or more points to make the input full dimensional.
 ```

Most error reports show different points.
