### ISSUE TITLE
binary model

### ISSUE THREAD

**Issue by vaulaner** [mittagessen/kraken#208]
Hi!

I have trained a bl segmenter with color images by using the --no-binarization parameter (-f page mode). When using the created model on color images, I always get the warning "Running binary model on non-binary input image (mode RGBA). This will result in severely degraded performance ".
How could I solve that ?
Thank you

**Comment by mittagessen** [comment]
* vaulaner :: 2020-06-11 09:21 Thu:
> Hi!
> 
> I have trained a bl segmenter with color images by using the --no-binarization parameter (-f page mode). When using the created model on color images, I always get the warning "Running binary model on non-binary input image (mode RGBA). This will result in severely degraded performance ".
> How could I solve that ?

That's a bug. Ignore the warning for now (apparently only the non-binary
flag isn't set during training so it doesn't affect accuracy). I'll get
to it in probably 2 weeks or so when my cast comes off.
