### ISSUE TITLE
pip not in environment.yml

### ISSUE THREAD

**Issue by dkinitz** [mittagessen/kraken#209]
conda env create --name kraken3 -f environment.yml

Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

Would be nice to have in the environment.yml...

**Comment by mittagessen** [comment]
It's already in there. Are you sure you're using an up-to-date env
file?

**Comment by dkinitz** [comment]
My mistake! wget obviously renamed the new environment.yml and so a very old one came into play.
