### ISSUE TITLE
Input image problem

### ISSUE THREAD

**Issue by chomskynet** [mittagessen/kraken#211]
We are developing an OCR for Arabic We train the models using synthetic data that we generate using a python script. Each line has its own font size. so the input images to the model have variable size.

We wonder when u train the models you use fixed images size or they are variable depending the font size/type like our case? 
In addition, our OCR results for large font sizes (28->72) are poor. Do you face similar problem in kraken? if yes, how do you overcome this problem?

**Comment by mittagessen** [comment]
> We wonder when u train the models you use fixed images size or they
> are variable depending the font size/type like our case? 

The line height is usually normalized to a fixed size but both models
are easily implementable in kraken (1,0,H,1 vs 1,0,0,1 input spec). This
should be fine as the font is sufficiently similar over different font
sizes, more so for Arabic typefaces which usually are rather low quality
and don't do any adaptation for different size glyphs.

> In addition, our OCR results for large font sizes (28->72) are poor.
> Do you face similar problem in kraken? if yes, how do you overcome
> this problem?

As everything is scaled to a fixed size we haven't had any issues but
IIRC all publication we ever ran through didn't have large variations in
font size (the old segmenter we used when most of that work was
happening couldn't deal with large headings anyway) but rather used
lithographic headings that didn't match a real typeface.

Anyway, on unaugmented text regardless of font size you should get
99.9+% character accuracy and in a rather low number of epochs (3000
iterations or so with a 'standard' complexity CNN+RNN stack). If that
doesn't work something is awry.
