### ISSUE TITLE
Reading order

### ISSUE THREAD

**Issue by volodos621** [mittagessen/kraken#212]
Hi!
I have some troubles with the order in the recognizer's output, when using the BL segmenter I have trained. Even if there is only one column in my page, after the line number 14 (in general), lines are mixed. Have you already seen such a bug ? How could I fix the line order ? Is-there something to parameter when training the segmenter ?
Thanks

**Comment by mittagessen** [comment]
* volodos621 :: 2020-06-18 15:12 Thu:
> Hi!
> I have some troubles with the order in the recognizer's output, when
> using the BL segmenter I have trained. Even if there is only one
> column in my page, after the line number 14 (in general), lines are
> mixed. Have you already seen such a bug ? How could I fix the line
> order ? Is-there something to parameter when training the segmenter ?

The reading order isn't learned (yet) so it basically runs the old
algorithm on the new output. Is the mixup always happening at line 14
independent of input? Are you training with regions (intra-region lines
are ordered separately) or not?

**Comment by volodos621** [comment]
I understand, but with the previous segmenter I didn't have such a problem. Yes, it always happen at line 14. I have trained by using the --no-region parameter. But actually, my images only have 1 column

**Comment by mittagessen** [comment]
* volodos621 :: 2020-06-19 09:44 Fri:
> I understand, but with the previous segmenter I didn't have such a problem. Yes, it always happen at line 14. I have trained by using the --no-region parameter. But actually, my images only have 1 column

Can you give me some sample output in page/alto or the json segmenter
output? The lines might be offset slightly so the algorithm determines
them to be two columns internally but without data I can't be sure.

**Comment by volodos621** [comment]
Yes sure, you will find the picture here http://www.thedigitalwalters.org/Data/WaltersManuscripts/W312/data/W.312/300/W312_000017_300.tif
and the json file : https://we.tl/t-GMypb4QyC0

**Comment by volodos621** [comment]
Still not working with your last commits :/

**Comment by volodos621** [comment]
When I open an xml file as an output of the segmenter, there is no problem of line order. I have this problem after the ocrization step, in the txt output, even if I use the --reorder parameter. Any idea to solve that ?

**Comment by mittagessen** [comment]
* volodos621 :: 2020-07-05 09:57 Sun:
> When I open an xml file as an output of the segmenter, there is no
> problem of line order. I have this problem after the ocrization step,
> in the txt output, even if I use the --reorder parameter. Any idea to
> solve that ?

Sorry, do you mean that when you're just running the segmenter (on some
XML input) the line order is right or when you use an XML file as an OCR
input the line order gets jumbled? Or does it only happen in the text
output but not the XML one? 

This problem is still on my mind but to be honest I haven't worked as
much on the problem as warranted as I've been busy with other things. My
initial plan to just replace the reading order algo with an alternative
from escriptorium got delayed a bit.

**Comment by volodos621** [comment]
Thanks, I do not succeed to open an alto file, but when I open the pageXML output in transkribus, lines appear in the right order. My Transkribus doesn't understand the glyph tag so I can't see the text, but when I print line numbers, everything is ok.
So, the bug seems to appear during the txt export step : in the txt output, lines are mixed...

**Comment by volodos621** [comment]
Still the same problem even with your last updates :(

**Comment by mittagessen** [comment]
The latest fixes in the region assignment makes the reading order code a bit more robust.
