### ISSUE TITLE
How to get OCR using API

### ISSUE THREAD

**Issue by rathorology** [mittagessen/kraken#213]
$ kraken -i image.tif image.txt binarize segment ocr

How can I do this in python script using Kraken API

**Comment by rathorology** [comment]
from kraken.lib.models import load_any
from kraken import rpred, binarization
from PIL import Image

img = cv2.imread(path)
**## ---Binarization of image---**
genrator_image = Image.fromarray(img)
genrator_image = binarization.nlbin(genrator_image)

****## ---Loading Kraken Model---**(download model and provide path here)**
model = load_any("en-default.mlmodel")

**## Kraken Text Extraction
## x,y,w,h should be determined and feed here to extract text from specific ROI.**
cord = [x, y, x + w, y + h]
bound = {'boxes': [tuple(cord)], 'text_direction': 'horizontal-lr'}

**## Using Kraken API**
generator = rpred.rpred(network=model, im=genrator_image, bounds=bound)
nxt_gen = next(generator)
text = nxt_gen.prediction

**Comment by alem-memic** [comment]
I think this should be written in README.md

**Comment by mittagessen** [comment]
The API docs now include a tutorial style documentation for the 3.0 release.
