### ISSUE TITLE
No line segmentation given. Add one with the input, `-l`, or run `segment` first.

### ISSUE THREAD

**Issue by PeterVoskuilen** [mittagessen/kraken#214]
Kraken version 3.0.0.0b7.dev8:

Hi you all.

I want to use the pagexml solution that is in kraken from release version 3.0b4. To do this I'm using the following steps.

**Binarize**
kraken -i 000000.tiff 000000b.tiff binarize

**Segment** 
kraken -i bin/000000b.tiff 000000l.json segment

So far so good. now the OCR part.
**OCR**
I ran kraken ocr --help te list the parameters, I'm missing the -l / --lines option here. (used to have this in version 2)
So ok, first thought; lets try it without the -l parameter
kraken -i 000000b.tiff 000000.p.xml ocr -x -m en_best.mlmodel 
this throws an error. 

> Failed processing 000000b.tiff: No line segmentation given. Add one with the input, `-l`, or run `segment` first.

okay... lets use the -l parameter then.
kraken -i 000000b.tiff 000000.p.xml ocr -x -m en_best.mlmodel -l 000000l.json

Unfortunately this throws an error aswell
Error: no such option: -l

what is the correct way to get the pagexml output?

thanks!

**Comment by dstoekl** [comment]
Hi Peter. You need to run a segmentation model first in the same pipeline command to detect the baselines. If you are dealing with Latin stuff try out the default model. Are you dealing with print or handwritten data? Best, Daniel

**Comment by PeterVoskuilen** [comment]
Hi Daniel, thans for your reply.

At this moment i'm working with latin stuff, so the default model will do in future there will be some print data.
I changed my kraken command by adding segment in the parameters, is this the correct way to build a pipeline?
My new command:
kraken -i 000000b.tiff 000000.p.xml **segment** ocr -x -m en_best.mlmodel

doing this i receive an error 
> [22.7957] Failed processing 000000b.tiff: 'NoneType' object has no attribute 'keys'

**Comment by mittagessen** [comment]
> I ran kraken ocr --help te list the parameters, I'm missing the -l / --lines option here. (used to have this in version 2)

It got removed because it is now possible to ingest XML documents
directly, e.g. something like:

$ kraken -f alto -i this_is_an_alto_file.xml out.xml ocr -m en_best.mlmodel -x

will take the image and segmentation defined in an alto file and run the
OCR on it (binarize/segment will only grab the image file if used). The
old way of defining an explicit segmentation didn't work with multiple
input files (and relied on the kraken-internal json format) so I dropped
it.

> what is the correct way to get the pagexml output?

Are you manually fixing the segmentation or why are you not using the
command chaining? Apart from providing the segmentation everything is
right.

**Comment by PeterVoskuilen** [comment]
Hi Mittagessen, thanks for the explaination; 

>It got removed because it is now possible to ingest XML documents
Okay, thats clear now. To bad the kraken command is still opting for this parameter. :-)

> Are you manually fixing the segmentation or why are you not using the
> command chaining? Apart from providing the segmentation everything is
> right.

No specific need for having segmentation separated. Don't need the json at this moment.
During testing and playing with kraken version 2 i used this method working with separate steps. and it is a habbit to use it now.

When running the command chaining for pagexml i get an error
> kraken -i 000001b.tiff 000001.xml segment ocr -x -m en_best.mlmodel
gives error : 
> Writing recognition results for 000001b.tiff    [20.1905] Failed processing 000001b.tiff: 'NoneType' object has no attribute 'keys'

running it for txt output is working
> kraken -i 000001b.tiff 000001.txt segment ocr -t -m en_best.mlmodel

any tips to work around this issue?

**Comment by mittagessen** [comment]
Please update, I broke the serialization with the non-trainable segmenter in the latest batch of commits. Your command should work now.

**Comment by PeterVoskuilen** [comment]
> Please update, I broke the serialization with the non-trainable segmenter in the latest batch of commits. Your command should work now.

That did the trick. Issue is resolved. many thanks
