### ISSUE TITLE
Arabic OCR

### ISSUE THREAD

**Issue by chomskynet** [mittagessen/kraken#217]
kindly be informed that I need to test Arabic OCR in Kraken please send to me the steps to can I do 
thanks

**Comment by bmwmy** [comment]
Usage info on: http://kraken.re
Best Arabic trained model is here:  https://github.com/OpenITI/OCR_GS_Data/blob/master/ara/abhath/arabic_generalized.mlmodel

Please close the issue if you do not mind.

**Comment by dirkroorda** [comment]
When I use the model with an up-to-date Kraken I get result but also a severe looking a runtime warning:

```
Loading RNN default	/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/coremltools/models/model.py:115: RuntimeWarning: You will not be able to run predict() on this Core ML model. Underlying exception message was: Error compiling model: "Error reading protobuf spec. validator error: Input MLMultiArray to neural networks must have dimension 1 (vector) or 3 (image-like arrays).".
  _warnings.warn(
✓
Processing  [####################################]  100%          
Writing recognition results for 058-00-bw.png	✓
```

These were my commands

```
kraken -i 058-00.tif 058-00-bw.png binarize
kraken -i 058-00-bw.png 058-00.json segment
kraken -i 058-00-bw.png 058-00.txt ocr --lines 058-00.json -m ../../_local/arabic_generalized.mlmodel
```

Input file attached. Github does not let me attach a tif file, so I attach the binarized PNG file.
Output file attached as well.
![058-00-bw](https://user-images.githubusercontent.com/1374704/97542801-a7d6f180-19c7-11eb-9dfb-bf03de88f0ae.png)
[058-00.txt](https://github.com/mittagessen/kraken/files/5456944/058-00.txt)





Should I worry about this?
