### ISSUE TITLE
Already forked ocropy, so how to fork kraken?

### ISSUE THREAD

**Issue by amitdo** [mittagessen/kraken#22]
The Github GUI does not let me do that.

**Comment by jbaiter** [comment]
Worked fine for me from the with the desktop webinterface: https://github.com/jbaiter/kraken

**Comment by amitdo** [comment]
>**Already forked ocropy**, so how to fork kraken?

@jbaiter
You didn't fork ocropy before you forked kraken. That's why it worked fine for you.

**Comment by zuphilip** [comment]
See also the old thread http://stackoverflow.com/questions/6675994/is-it-possible-to-fork-a-fork-in-github with all its answers (e.g. the options from the command line). Otherwise you can still try to fork kraken in a branch of your ocropy fork.

**Comment by amitdo** [comment]
I don't want to open another account just for this.

Just to fork it from the command line is not a problem.

I want an option that will integrate wlth GH features - let me send PR to both repos.

**Comment by QuLogic** [comment]
You don't need to fork from both; they're both part of the same fork tree, so you can send PRs to either one. Of course, you won't be able to have a single `master` branch that follows both.

**Comment by amitdo** [comment]
OK, Thanks.
