### ISSUE TITLE
Option for Jupyter Lab/Notebook

### ISSUE THREAD

**Issue by JamesMTucker** [mittagessen/kraken#226]
I find the HTML/JavaScript training entry method somewhat cumbersome, when one has to transcribe lines and the right/left parallel format are not coordinated with one other. Would it be possible to have an alternative that utilises the features of Jupyter Lab/Notebook? Where each line could be a new cell with an additional markdown cell added beneath to transcribe? This would make for a better experience in many ways, I think. Thanks for your hard work and for considering my request.

**Comment by dirkroorda** [comment]
This could be an example of such an interface. While this is not exactly the interface for training, it shows how to combine the image and the OCR in one place to see them close together.
We used Kraken to generate OCR transcriptions line by line (we detected the lines ourselves by means of preprocessing), then we generated proof pages, showing the results on top of the original and indicating the confidence by color. 
All of that from a Jupyter Notebook.

See https://nbviewer.jupyter.org/github/among/fusus/blob/master/example/measureOcr.ipynb
then click on one of the page numbers deeper down, e.g.
https://nbviewer.jupyter.org/github/among/fusus/blob/master/example/proof/101.html

Probably you could generate HTML to display in an output cell, containing the image of the line that must be transcribed, plus a widget to type the transcription just above the line.

I have not worked much with widgets and it takes some while to understand it. But it is possible to let a user interact with a widget and then capture the results and work with it in Python code. The crucial thing here is [interactive](https://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html#interactive).

**Comment by mittagessen** [comment]
The transcription interface is indeed rather antiquated now. Unfortunately, reworking it is rather low priority as we've got the new layout analysis system that doesn't use rectangular lines anymore. There's also [escriptorium](https://gitlab.inria.fr/scripta/escriptorium) which has a more ergonomic transcription interface and incorporates kraken in the backend/can export in kraken-(and most other OCR engine)-compatible PageXML/ALTO files.
