### ISSUE TITLE
A solution to the line detection and polygonization issues

### ISSUE THREAD

**Issue by seekingdeep** [mittagessen/kraken#227]
While going through kraken's commits, i noticed that the polygonization is a constant issue. So i think i have a solution for you, why don't you skip the textline detection part.

Recent advancements such as OrigamiNet, can recognize the text at the paragraph level, yes i mean the paragraph level!
The model can automatically localize the textlines byitself, and according to their results it can even get higher accuracy than single line detector/recognizer models. Also it is robust and can recognize text even if the textlines are overlapping each other.
have a look:
https://www.youtube.com/watch?v=CXxsiS838mQ
https://github.com/IntuitionMachines/OrigamiNet
https://arxiv.org/abs/2006.07491

![origaminet](https://user-images.githubusercontent.com/71519088/99933080-05fab880-2d6b-11eb-95c8-6f39457f3c99.jpg)

**Comment by mittagessen** [comment]
I am aware of these methods but they still require segmentation (the one
you linked) or large amounts of training data, inference time, and
aren't really feasable to retrain for the average person (the Tensmeyer
systems). They've also got conceptual quirks that make the unusable for
real-world documents, such as assumptions of fixed line height or neatly
ordered lines that don't hold even on a paragraph level for historical
documents.

**Comment by seekingdeep** [comment]
Send me samples and their annotation, of the document layouts that you deem relevant and representative of the real-world, Alto-xml & Page-xml are preferred. I want to test different text localization methods.

For now, my interest is to try to improve the state of layout detection.
my offer expires after 3 days.

**Comment by kba** [comment]
> my offer expires after 3 days.

🤣
