### ISSUE TITLE
long Segmenting process

### ISSUE THREAD

**Issue by josef821** [mittagessen/kraken#231]
i compile kraken with anaconda and run this command :
kraken -i image.png image.txt binarize segment ocr -m en_best.mlmodel
output : 
_[0.0025] Baseline model (/home/mypc/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/blla.mlmodel) given but legacy segmenter selected. Forcing to -bl. 
Loading ANN /home/mypc/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/blla.mlmodel	✓
Loading ANN default	✓
Binarizing	✓
Segmenting	_

it will hold almost 30 to 40 second on sementing and ocr will be very slow.
what should i do?

**Comment by kba** [comment]
If you know that the work is single-column, you can set `maxcolseps` to `0`, that speeds up segmentation in my experience.

**Comment by dstoekl** [comment]
Why dont you want to train the new segmenter?

________________________________
De : Konstantin Baierer <notifications@github.com>
Envoyé : jeudi 7 janvier 2021 10:23
À : mittagessen/kraken <kraken@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [mittagessen/kraken] long Segmenting process (#231)


If you know that the work is single-column, you can set maxcolseps to 0, that speeds up segmentation in my experience.

**Comment by josef821** [comment]
_Error: no such option: maxcolseps_
i want to ocr very simple image with two or more line . no column and no image.
in 2.x version segmentation was easy.

**Comment by kba** [comment]
> Error: no such option: maxcolseps

It's an option of the segment CLI, i.e.

```
kraken -i image.png image.txt binarize segment --maxcolseps 0 ocr -m en_best.mlmodel
```

**Comment by kba** [comment]
> i replace with kraken-3.0b12 it works like old version now.

Most recent version is 3.0b18 btw.

**Comment by josef821** [comment]
> > Error: no such option: maxcolseps
> 
> It's an option of the segment CLI, i.e.
> 
> ```
> kraken -i image.png image.txt binarize segment --maxcolseps 0 ocr -m en_best.mlmodel
> ```

it still wait 30 to 40 second on segmenting.

**Comment by mittagessen** [comment]
> it still wait 30 to 40 second on segmenting.

I did a stupid in November that's why. kraken is defaulting to the new
trainable segmenter and the legacy one couldn't be selected anymore.
There's a hotfix in 3.0b19. Although I'm not sure why the new segmenter
is slower for you than the old one, generally it is a bit faster if
there's a 'normal' amount of lines on the page and you've got sufficient
free memory (~4Gb).

**Comment by josef821** [comment]
some image have 1 and some 10 very simple line.
my pc spec:
cpu:i7-6700
ram:32G
graphic:1070 - 8G up to 16G
hdd:500G SSD

**Comment by dirkroorda** [comment]
I also encountered long segmenting times and that's why I do the segmentatio  myself, in opencv.
