### ISSUE TITLE
Only one model in the repository?

### ISSUE THREAD

**Issue by jsbien** [mittagessen/kraken#237]
I just installed kraken and `kraken list` gives only 
`10.5281/zenodo.2577813 (pytorch) - A generalized model for English printed text`.
Where are other models? I'm especially interested in Medieval Latin.

**Comment by kba** [comment]
For Arabic there is https://github.com/OpenITI/OCR_GS_Data, there is the legacy https://github.com/mittagessen/kraken-models and there are various older `pronn` models listed in https://data.bib.uni-mannheim.de/ocr-models/ (data was gathered ~2017 though).

@pontelneptique shared a Latin mlmodel here: https://github.com/mittagessen/kraken-models/pull/5

**Comment by jsbien** [comment]
Thanks.
However  for @ponteIneptique's model I see
`This commit does not belong to any branch on this repository.`
I've cloned the repository but I don't see the model there.
Moreover I don't know how to use a model which is not listed by 'kraken list' :-(

**Comment by mittagessen** [comment]
* Janusz S. Bień :: 2021-01-25 12:43 Mon:
> Moreover I don't know how to use a model which is not listed by 'kraken list' :-(

You just use the -m option like for repository models and put the path
of the model file instead. The model repository is empty as its use is
not documented and requires some technical skill to get the identifiers
for zenodo and such. It is going to be added to escriptorium soon-ish
though which should improve the situation.

In the meanwhile there are people keeping models in various git
repositories...

**Comment by jsbien** [comment]
Thanks again.
Please note that `kraken --help` doesn't show `-m` option. What should I consult to avoid asking elementary questions?

**Comment by kba** [comment]
You can see the definition of the CLI in `kraken/kraken.py`, i.e. those lines that start with `@click.option`, `@click.argument` etc.

**Comment by kba** [comment]
> I've cloned the repository but I don't see the model there.

Go to https://github.com/mittagessen/kraken-models/blob/ec4407159e19d0df6e366038f262b4f5a8bbb12a/mlmodel/latin-teubner/latin-teubner.mlmodel and click "Download"

**Comment by mittagessen** [comment]
* Janusz S. Bień :: 2021-01-25 12:57 Mon:
> Please note that `kraken --help` doesn't show `-m` option. What should I consult to avoid asking elementary questions?

It is an option on the ocr subcommand. `kraken ocr --help` should print
it (and a million others).

There is some documentation here [0] on the option usage for the
different subcommands, although that's for the last stable release and
not the development branch.

[0] http://kraken.re/advanced.html

**Comment by jsbien** [comment]
Thank you very much!

**Comment by FergusJPWalsh** [comment]
Hi, I'm having real trouble understanding the documentation and parts of this thread.
Can you please tell me what the command would be to install a custom model from a Github repo?
If I can just download the file and put it in the Kraken directory, then which directory and where?
I'm using Linux (Ubuntu) and have Kraken installed.
Thank you.

**Comment by mittagessen** [comment]
* Fergus :: 2021-08-06 20:32 Fri:
> Hi, I'm having real trouble understanding the documentation and parts of this thread.
> Can you please tell me what the command would be to install a custom model from a Github repo?
> If I can just download the file and put it in the Kraken directory, then which directory and where?

Yes, you can just download the model file and place it whereever you
want. Then you can use it by pointing kraken to the file with the `-i`
or `-m` option  depending on the command you're actually running. The
auto-finding feature that scours the default directory is completely
optional.

**Comment by FergusJPWalsh** [comment]
I have tried using the -m option, and am still having no luck. I have the [following models](https://github.com/pharos-alexandria/ocr-greek_cursive) downloaded on my PC  and I am also trying to get one from GitHub.

Please advise on exactly which commands I should use.

I appreciate your help.

```
kraken -m get model_grc_catlips.mlmodel
Usage: kraken [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...
Try "kraken --help" for help.

Error: no such option: -m
```

```
kraken get -m rahlfs-2014-05-26-19-05-00100000.pyrnn.pronn
Usage: kraken get [OPTIONS] MODEL_ID
Try "kraken get --help" for help.

Error: no such option: -m
```

```
kraken get rahlfs-2014-05-26-19-05-00100000.pyrnn.pronn
Retrieving model .[1.0987] Found 0 models when querying for id 'rahlfs-2014-05-26-19-05-00100000.pyrnn.pronn' 
Traceback (most recent call last):
  File "/home/fergus/.local/bin/kraken", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/fergus/.local/lib/python3.8/site-packages/kraken/kraken.py", line 619, in get
    filename = repo.get_model(model_id, click.get_app_dir(APP_NAME),
  File "/home/fergus/.local/lib/python3.8/site-packages/kraken/repo.py", line 118, in get_model
    raise KrakenRepoException(f'Found {resp["hits"]["total"]} models when querying for id \'{model_id}\'')
kraken.lib.exceptions.KrakenRepoException: Found 0 models when querying for id 'rahlfs-2014-05-26-19-05-00100000.pyrnn.pronn'
```

**Comment by kba** [comment]
@FergusJPWalsh If you already have the models downloaded, you don't need to call `kraken get`. Also `-m` is an option to the `ocr` command and should be the path to the model to use. See  `kraken ocr --help`.

**Comment by FergusJPWalsh** [comment]
But when I call ```list``` I only get the English model
```
kraken list
Retrieving model list .✓
10.5281/zenodo.2577813 (pytorch) - A generalized model for English printed text
```

**Comment by FergusJPWalsh** [comment]
Could I ask that the whole process of installing a new model be explained to me, step by step and with the appropriate commands?
If so, I would be very grateful.

**Comment by kba** [comment]
`kraken list` will only show the models in the repository, not your downloaded models.

Let's say yout want to process `foo.png` with https://github.com/pharos-alexandria/ocr-greek_cursive/raw/master/kraken-models/model_grc_savile.mlmodel:


```sh
wget https://github.com/pharos-alexandria/ocr-greek_cursive/raw/master/kraken-models/model_grc_savile.mlmodel
kraken -i foo.png binarize segment -bl ocr -m model_grc_savile.mlmodel
```

This will download the model and run binarization, segment and ocr with kraken.

**Comment by FergusJPWalsh** [comment]
Thank you so much. That's been a great help.
