### ISSUE TITLE
problem with direction

### ISSUE THREAD

**Issue by josef821** [mittagessen/kraken#240]
i trained my own model. but i got new problem.
line 1 and 3 will convert good but If the text ends with an English word ( or any LTR word ) line will convert LTR.
and when i change direction of text to rtl it gets messed up.
line 1 and 3 is Arabic and words will be fine when change direction to RTL. but line 2 is only show correct in ltr.
in Arabic all text must be Right to Left
I hope you have fully understood what I mean.

**Comment by mittagessen** [comment]
The BiDi algorithm has some intricacies that can cause behavior like
this. Basically, the algorithm defaults to LTR text until it encounter
something that isn't and then switches to RTL. You can often switch the
default text direction through external means such as HTML markup but as
there is no reliable Unicode-internal way to do it Kraken uses the
default behavior. You'll probably have encountered similar issues when
typing mixed Arabic and Latin text into a text field in your web brower.

The current best way to deal with this is through RTL marks in the
training data. They are probably already in there and this is just a
misrecognition. If this error persists we can add default text direction
to the model metadata and let you select it with a command line option
during training.
