### ISSUE TITLE
kraken segment – 'Polygon' object is not iterable

### ISSUE THREAD

**Issue by maxnth** [mittagessen/kraken#241]
When running `kraken -x -v -I <IMAGES> -o .kraken.xml segment -bl --model <PATH-TO-MODEL>` with a custom trained model I get errors like the following for certain pages of the data set:

```
...
[34.9230] Segmenting kraken_data/zpd/f_1597-Ferber_Blutregen/pages/sel/0004.ocropus.bin.png 
[34.9232] Segmenting kraken_data/zpd/f_1597-Ferber_Blutregen/pages/sel/0004.ocropus.bin.png 
[36.3385] Vectorizing regions 
[36.5834] Failed processing kraken_data/zpd/f_1597-Ferber_Blutregen/pages/sel/0004.ocropus.bin.png: 'Polygon' object is not iterable
...
```

When using a different model the errors can't be reproduced on the same images but are then raised on other images.

Is this bug connected to faulty training / training with a too small dataset? 
The `boundaries` list in https://github.com/mittagessen/kraken/blob/d39c45564df81d84bea58ee0067a48585a5f63e2/kraken/lib/segmentation.py#L349 
always stays empty for runs where the error is raised.

One of the pages where the error appears: [0004.ocropus.bin.zip](https://github.com/mittagessen/kraken/files/6310596/0004.ocropus.bin.zip)

**Comment by mittagessen** [comment]
Could you run the same command with the -r/--raise-on-error option, to
get a full stacktrace? And could you upload the model that produces
these errors as well?

**Comment by maxnth** [comment]
>Could you run the same command with the -r/--raise-on-error option, to
get a full stacktrace? And could you upload the model that produces
these errors as well?

[kraken_issue_data.zip](https://github.com/mittagessen/kraken/files/6310732/kraken_issue_data.zip)

**Comment by mittagessen** [comment]
Sorry for the delay, I took a few days off. The bugfix is in master and also in the newly tagged 3.0b24.

**Comment by maxnth** [comment]
Thanks a lot.
