### ISSUE TITLE
Multi-process/thread Dataset building ?

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#242]
Hi there :)
I was wondering if it'd be possible to boost a little the speed of building training set / valid set ? I looked at it and it seems quite "sequential" 

https://github.com/mittagessen/kraken/blob/d39c45564df81d84bea58ee0067a48585a5f63e2/kraken/lib/train.py#L624-L632

I could take a chance at it if you do not have the time, and if you give me pointer on how you'd like it to be done (proxy function / reusing `--threads`, etc. )

**Comment by mittagessen** [comment]
* Thibault Clérice :: 2021-04-16 11:44 Fri:
> I could take a chance at it if you do not have the time, and if you
> give me pointer on how you'd like it to be done (proxy function /
> reusing `--threads`, etc. )

I had already taken a look a while ago on how to best parallelize the
loading and couldn't really find a nice pytorch-y way. A proper
implementation would probably make add() asynchronous by having an
internal Queue() and a Pool() working down the queue. It shouldn't be
terribly complicated but there might be corner cases somewhere as
pytorch finagles a bit with the multiprocessing module and ships an own
version of it.

**Comment by PonteIneptique** [comment]
I assume the simplest would probable be a pool on `dataset.parse()` then adding the result in sync ? No ?

Something like

```python
    with Pool(processes=nb_threads) as pool:
        for parsed in pool.imap_unordered(gt_set.parse, training_data): 
            gt_set.add(parsed)
```

while probably having an `async` in the parse as well if the file is XML (ie. more than 1 line per file), to allow for some light parallelization ? Right now, parsing can be 20 minutes for 40 minutes of training, which is definitely something I'd like to see improved :D

**Comment by mittagessen** [comment]
The problem is the computationally intensive piece is somewhat necessarily in the dataset class (you need the correct codec, image mode, ... to do it) so having parallelization outside would really do nothing.

**Comment by PonteIneptique** [comment]
I get that, I actually meant to separate the current `add` function in two bits: one which does the parsing, the other which does the *registering* within the dataset.

*ie*, have `parse` (or `_add` if you prefer) which does this https://github.com/mittagessen/kraken/blob/d39c45564df81d84bea58ee0067a48585a5f63e2/kraken/lib/dataset.py#L443-L473

while `add` simply register the output, _ie_ https://github.com/mittagessen/kraken/blob/d39c45564df81d84bea58ee0067a48585a5f63e2/kraken/lib/dataset.py#L474-L478

**Comment by PonteIneptique** [comment]
You could also have a *parallelized* `parallel_add` function at the dataset level, which would avoid writing this in the Trainer, if this is your first concern :)

**Comment by mittagessen** [comment]
Ah then I misunderstood. That would obviously work and be fairly quick to implement. An instance method seems a bit ugly but should do the trick.

**Comment by PonteIneptique** [comment]
That's great ! Thanks. How do I update this via conda ?

**Comment by mittagessen** [comment]
you don't really. The easiest way is probably to just clone the repository, switch to the branch and do an editable install with pip inside the conda environment.

**Comment by PonteIneptique** [comment]
Got an error with unicode normalization this morning:

```python-tb
Traceback (most recent call last):
  File "kraken-unstable/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "kraken-dev/kraken/lib/train.py", line 47, in _star_fun
    return fun(**kwargs)
  File "kraken-dev/kraken/lib/dataset.py", line 460, in parse
    text = func(text)
  File "kraken-dev/kraken/lib/functional_im_transforms.py", line 70, in text_normalize
    return unicodedata.normalize(normalization, x)
NameError: name 'x' is not defined
```

**Comment by PonteIneptique** [comment]
Otherwise with 10 threads I saw a speed increase of x4, which is nice :)

**Comment by PonteIneptique** [comment]
> Thanks, that's a typo. You're probably running into I/O limits there. I've got an roughly 8 times speed up with 8 processes but my SSD is fairly fast.

Yeah, we have a NVME but you know what, I am fairly happy with the increase nonetheless. Of course, this is a quickfix for a problem that might need other way to deal with it, but I assume for eScriptorium this will have a huge impact as 64 core processors might really be used ;)

**Comment by mittagessen** [comment]
Chunking gave another slight speedup so I'll merge it now. Apart from rewriting the line justification code in C there's unfortunately not much that can be done to get further speedup without preprocessing datasets separately.
