### ISSUE TITLE
Very minor error in mm_rpred()

### ISSUE THREAD

**Issue by alix-tz** [mittagessen/kraken#246]
Hi,

I'm getting this message: `Recognizers with segmentation types set() will be applied to segmentation of type baselines. This will likely result in severely degraded performace` 

In: 
https://github.com/mittagessen/kraken/blob/984f1e7a3fdbb5306419a9260ac55c966ecc77f4/kraken/rpred.py#L178
Very small typo: should be "performance".

Also, not sure you meant to display "set()" when you refer to the types. Maybe it results from something going wrong here: https://github.com/mittagessen/kraken/blob/984f1e7a3fdbb5306419a9260ac55c966ecc77f4/kraken/rpred.py#L174

**Comment by mittagessen** [comment]
* Alix Chagué :: 2021-05-12 16:54 Wed:
> Also, not sure you meant to display "set()" when you refer to the
> types. Maybe it results from something going wrong here:

It's just how the set of types in the models given to mm_rpred are
printed. If they are empty (because the model was trained with a version
of kraken that has the type check but didn't serialize the type into the
model metadata) it looks like this.
