### ISSUE TITLE
Line type problem using ketos segtrain

### ISSUE THREAD

**Issue by Juliettejns** [mittagessen/kraken#248]
Hi, 

I am encountering some problems while training a model for layout analysis with ketos segtrain.

According to kraken, it seems that a same type (`Default`) has been written alternatively with (`Default`) and without (`default`) a capital letter:

![Capture d’écran de 2021-05-28 14-22-04](https://user-images.githubusercontent.com/56683417/119983285-3cd2b500-bfc0-11eb-83b2-2c8065a54116.png)

The problem is that I cannot find in my data the version without the capital letter (`@LABEL="default"`) but only with it (`@LABEL="Default"`). Could Kraken be the source of the problem? Indeed, similar problem has been encountered by other users.

Data have been exported from Transkribus and manually annotated in eScriptorium. They are available here: `https://github.com/Juliettejns/cataloguesSegmentationOCR`

Command used: `ketos segtrain -t DIRECTORY -f alto`
Ubuntu v. 18.04
Kraken v. 3.0.0.0

Thanks in advance for your help

**Comment by mittagessen** [comment]
Lines without an explicit type get assigned the `default` class. So your data contains some lines with an explicit `Default` type and some without any type. I hope that clears it up.

**Comment by Juliettejns** [comment]
Thank you very much for your answer, that helps a lot.
