### ISSUE TITLE
Problem using another segmentation model than default one

### ISSUE THREAD

**Issue by Heresta** [mittagessen/kraken#249]
Hi, 

I am encountering some problems while using a model for layout analysis with both kraken segment and kraken commands.

It seems that I can't use my own segmentation model to segment my pictures, with or without binarize.

png used can be found on GitHub (available [here](https://github.com/Heresta/datasetsOCRSegmenter17/blob/main/Data/Balzac1624_Lettres_btv1b86262420_corrected/png/Balzac1624_Lettres_btv1b86262420_corrected_0062.png)).
Segment model used can be found on GitHub (available [here](https://github.com/Heresta/datasetsOCRSegmenter17/blob/main/Model/Segment/segment17.mlmodel))

Command used: `kraken -i input.png output.xml binarize segment -bl -i segmenter.mlmodel ocr -m HTR.mlmodel`
Output Error: `Failed processing Data/Balzac1624_Lettres_btv1b86262420_corrected/png/Balzac1624_Lettres_btv1b86262420_corrected_0062.png: name 'netn' is not defined`
Ubuntu v. 18.04.5
Kraken v. 3.0b25 

Thanks in advance for your help

**Comment by maxnth** [comment]
Looks to be caused by a typo (`netn.user_metadata["topline"]` instead of `net.user_metadata["topline"]`) in: https://github.com/mittagessen/kraken/blob/b99a6d0374dfca3a8ff5e273637e31bb7d6dfd75/kraken/blla.py#L225

**Comment by Heresta** [comment]
It worked ! Thanks !
