### ISSUE TITLE
Ketos segtrain applying topline when asking for baseline and vice-versa ?

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#256]
Hey there,

I can be wrong, but I have had weird behavior training the segmenter. I believe there is a mistake in the Click definition of the segmenter, but again, I can be wrong...

In the click, you got `-bl/-tl`:

https://github.com/mittagessen/kraken/blob/45f6bb0b1b1632de6077e6712f11d5461ddad63a/kraken/ketos.py#L158-L161

This value is of baseline (True or False) is passed down

https://github.com/mittagessen/kraken/blob/45f6bb0b1b1632de6077e6712f11d5461ddad63a/kraken/ketos.py#L260

 to the topline kwarg and can be reused here:

https://github.com/mittagessen/kraken/blob/abe08ba4bec3778cf9e15c5cea7c0de503358a61/kraken/lib/segmentation.py#L440-L444

In this excerpt, it shows that topline=True will use topline (which makes sense).

If you create a file simply containing the same click declaration, such as :

```python
import click

@click.command() 
@click.option('-bl/-tl', '--baseline/--topline', show_default=True, 
        default=False, help='Switch for the baseline location in the scripts. ' 
        'Set to topline if the data is annotated with a hanging baseline, as is ' 
        'common with Hebrew, Bengali, Devanagari, etc.') 
def bl(baseline): 
    print(baseline)

if __name__ == "__main__":
	bl()
```

you'll see that `-bl` gets makes `baseline=True` which will be directly used as `topline=True`. On the contrary, using `-tl` will set it to False. Basically, it seems to be the opposite of what is expected.

**Comment by PonteIneptique** [comment]
Note that even training with either params looks like it trains on topline, but that could be an artefact of the manuscript.

**Comment by mittagessen** [comment]
Yup, that's a bug. As a note this switch just sets a field in the model metadata as a hint to the postprocessor, there's no change in the actual training procedure. Lines get offset into the line corpus now for more robust polygonization and the direction changes for top- and bottom baselines. There's a script `set_seg_options.py` in contrib that allows you to manually change this field (and the bounding regions as well).

**Comment by PonteIneptique** [comment]
Thanks for the quick reaction, just a follow up to clear up my understanding:
With the current eScriptorium model on Traces6, the baseline in under the letters (baseline then). With newly trained model, the lines are basically strike-through (really in the middle of the line). This behavior is now the default one to enhance repolygonization then and as such completely normal ?

**Comment by mittagessen** [comment]
* Thibault Clérice :: 2021-06-14 11:46 Mon:
> Thanks for the quick reaction, just a follow up to clear up my understanding:
> With the current eScriptorium model on Traces6, the baseline in under
> the letters (baseline then). With newly trained model, the lines are
> basically strike-through (really in the middle of the line). This
> behavior is now the default one to enhance repolygonization then and
> as such completely normal ?

Uhhm no that shouldn't happen. There was an explicit offset in the
training code a while ago but we reverted that as it causes issues when
training serially (the baseline keeps creeping up with each time a model
is adapted). Let me investigate.

The offset is purely internal during polygonization.

**Comment by PonteIneptique** [comment]
Should we reopen until investigation done ? :)

**Comment by mittagessen** [comment]
* Thibault Clérice :: 2021-06-14 12:36 Mon:
> Should we reopen until investigation done ? :)

Na, that logic is independent of the switches. And I screwed up by
accidentally reverting the reverted change when I merged another branch
a while ago.

**Comment by PonteIneptique** [comment]
Can you update here when the thing is fixed ? :)

**Comment by mittagessen** [comment]
* Thibault Clérice :: 2021-06-14 12:41 Mon:
> Can you update here when the thing is fixed ? :)

Yup. Shouldn't take that long. After lunch.

**Comment by PonteIneptique** [comment]
Bon appétit !

**Comment by gabays** [comment]
Hey! Seems we have the same problem here. Did you have the time to fix it finally?

**Comment by mittagessen** [comment]
Actually committing and pushing changes helps making said changes accessible to other people. It's fixed now (in master).

**Comment by PonteIneptique** [comment]
WOOOOOOOOOOOHOOOOOOOO

**Comment by gabays** [comment]
Thank you!

**Comment by gabays** [comment]
In some cases the result is much better

![image](https://user-images.githubusercontent.com/26046460/122070160-01c0e600-cdf6-11eb-9cc2-f347755b8045.png)

But most of the time it is pretty chaotic

![image](https://user-images.githubusercontent.com/26046460/122069424-79dadc00-cdf5-11eb-9857-7a17682b8faa.png)

The model 
[models_images.zip](https://github.com/mittagessen/kraken/files/6656375/models_images.zip)

**Comment by PonteIneptique** [comment]
The same training dataset with the same training command does indeed create weird things : 
![image](https://user-images.githubusercontent.com/1929830/122073064-6aa95d80-cdf8-11eb-9c81-633bfe956b06.png)

Note that it was trained just before you pushed this last commit https://github.com/mittagessen/kraken/commit/41d5fdb3de643157e829338dc5b589d360223722

**Comment by mittagessen** [comment]
* Thibault Clérice :: 2021-06-15 16:41 Tue:
> The same training dataset with the same training command does indeed create weird things (from @ArianePinche) : 
> ![image](https://user-images.githubusercontent.com/1929830/122073064-6aa95d80-cdf8-11eb-9c81-633bfe956b06.png)

Hmm that looks like errors caused by low resolution. If the lines 'wash'
into each other the skeletonization can pick random end points and you
can get lines like these. If you train on a higher resolution:

```
ketos segtrain -s [1,1800,0,3 Cr7,7,64,2,2 Gn32 Cr3,3,128,2,2 Gn32 Cr3,3,128 Gn32 Cr3,3,256 Gn32 Cr3,3,256 Gn32 Lbx32 Lby32 Cr1,1,32 Gn32 Lby32 Lbx32] ...
```

the problem will most likely resolve itself.
