### ISSUE TITLE
Segmenter proposes creative segmentations

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#257]
Hey, 
To follow up on https://github.com/mittagessen/kraken/issues/256, I felt like a new issue was in order, as the first was targeted at the inversion of `-bl` and `-tl`.

Before today, training and segmenting would provide a rather good segmentation but strike-through:
![image](https://user-images.githubusercontent.com/1929830/122081009-063dcc80-cdff-11eb-8025-c6e6ddb1e5f5.png)

Since the commits of today, the segmentation is completely all over the place, using the same training set, eval set and command:
![image](https://user-images.githubusercontent.com/1929830/122081089-18b80600-cdff-11eb-87a4-b34be0001192.png)

@gabays has seen the same issue

**Comment by PonteIneptique** [comment]
Command and logs:

```
ketos segtrain -bl -f alto  -t train.txt -e val.txt -o NoFineTuningBL --device cuda:0 --threads 10 --augment --merge-baselines Default:default --merge-baselines Default:Numbering --merge-baselines Default:Main --merge-baselines Default:DropCapitalLine --epochs 50 --schedule reduceonplateau --suppress-regions --merge-baselines Default:Rubric

Creating model [1,1200,0,3 Cr7,7,64,2,2 Gn32 Cr3,3,128,2,2 Gn32 Cr3,3,128 Gn32 Cr3,3,256 Gn32 Cr3,3,256 Gn32 Lbx32 Lby32 Cr1,1,32 Gn32 Lby32 Lbx32 O2l3] with 3 outputs ✓
Training line types:
  Default	2	10243
Etc.
```

**Comment by PonteIneptique** [comment]
Trying 

```
ketos segtrain -s [1,1800,0,3 Cr7,7,64,2,2 Gn32 Cr3,3,128,2,2 Gn32 Cr3,3,128 Gn32 Cr3,3,256 Gn32 Cr3,3,256 Gn32 Lbx32 Lby32 Cr1,1,32 Gn32 Lby32 Lbx32] ...
```

as mentioned in the other issue.

**Comment by mittagessen** [comment]
There's a script in `contrib/` called `baselineset_overlay.py` that produces overlays for training data. Can you run it on some of your XML files and see if the output looks reasonable? Otherwise it might be the aforementioned resolution problem (the page is quite densely written on so 1200px in height can be a bit crowded).

**Comment by mittagessen** [comment]
But I'm a bit puzzled why it works well with the offset and not at all without. It's possible that not offsetting increases the uncertainty of the model....

**Comment by PonteIneptique** [comment]
This is the thing to be honest: it "worked" before, while weirdly with the line offset in the middle. Older models worked as well... Just newer ones don't.

**Comment by PonteIneptique** [comment]
The new model seem to work, but I am still puzzled as how it broke in between offset issues.

**Comment by PonteIneptique** [comment]
> There's a script in `contrib/` called `baselineset_overlay.py` that produces overlays for training data. Can you run it on some of your XML files and see if the output looks reasonable? Otherwise it might be the aforementioned resolution problem (the page is quite densely written on so 1200px in height can be a bit crowded).

Do you mean https://github.com/mittagessen/kraken/blob/0f6bfd21f60c6dbb39e86c56474b052d029cf332/kraken/contrib/forced_alignment_overlay.py ?

**Comment by PonteIneptique** [comment]
I can't find the script you mean and most of them error out, so here are two example files :D 
[krak.zip](https://github.com/mittagessen/kraken/files/6657368/krak.zip)

**Comment by mittagessen** [comment]
I pushed the script. And I think I found the error. The lines were twice as wide as before because the syntax of the single-sided buffer and double-sided is different. Please try with the current master.

**Comment by PonteIneptique** [comment]
You'll have the results in the morning. In the meanwhile, thank you very much for the quick support you're providing :)

**Comment by PonteIneptique** [comment]
Seems to be fixed. Now let's go see if things are clean with regions :D 
![image](https://user-images.githubusercontent.com/1929830/122117037-a6f3b280-ce26-11eb-96e8-5289d719de12.png)

**Comment by PonteIneptique** [comment]
Actually, no matter what region gives, this is probably another issue. I'll let other open one if they feel something is weird :) Thanks @mittagessen !

**Comment by mittagessen** [comment]
Hm weird. Regions are working rather reliably for us.

**Comment by gabays** [comment]
Thank you both for you help. Results are great!
