### ISSUE TITLE
kraken version numbers?

### ISSUE THREAD

**Issue by pverkind** [mittagessen/kraken#258]
Hi Ben, 

we're OCR'ing texts for the OpenITI corpus, and I'd like to indicate in the metadata which version of kraken was used. 
Are you using some kind of version numbering for kraken? If so, where can I find the version number?

Best, 

Peter

**Comment by mittagessen** [comment]
Kraken uses standard semantic versioning. You can use `pkg_resources` for this:

```
import pkg_resources
pkg_resources.get_distribution('kraken').version
```

Or `importlib` if you're running on python>=3.8.

**Comment by pverkind** [comment]
Great, thanks!
