### ISSUE TITLE
kraken.lib.exceptions.KrakenInvalidModelException: Model incomplete

### ISSUE THREAD

**Issue by SeguinBe** [mittagessen/kraken#261]
Hello,

I have been trying to evaluate different OCR methods for arabic, including the Kraken models.

According to [this issue](https://github.com/mittagessen/kraken/issues/121) the best arabic model is [this one](https://github.com/OpenITI/OCR_GS_Data/blob/master/ara/abhath/arabic_generalized.mlmodel), however it is probably in an older format and trying to use it leads to an `kraken.lib.exceptions.KrakenInvalidModelException: Model incomplete` error (more specifically `ValueError: No VGSL spec in model metadata`)

I tried in `2.0.8` and downgrading to `1.0.1` to no success.

Is there something I missed, or is there a way to convert the model relatviely easily? Dare I suggest adding it to the zenodo model zoo which is surprisingly empty on `2.0.8`?

Best

**Comment by mittagessen** [comment]
There have been some changes lately, mostly in relation to the new trainable segmenter so while this model works reasonably well on naskh print text it isn't optimal when used in the fully trainable pipeline now. You can use it with binarization and the old box segmenter though (the segmenter will probably not produce perfect results).

Nevertheless it should work perfectly fine with the current code as it is always kept backwards compatible. It does on my side.
