### ISSUE TITLE
Resizing Segmentation Models

### ISSUE THREAD

**Issue by rohanchn** [mittagessen/kraken#264]
Hi @mittagessen 

I've been training a segmentation model from data exported from eScriptorium. Everything is working as expected. 

This blog post [[1](https://digitalintellectuals.hypotheses.org/3844)] talks about resizing the cBAD segmentation model. I tried looking it up, but couldn't find it. 
Was this model trained on the cBAD dataset available on zenodo? 
Can you please point me to the cBAD models so that I can resize those instead of training everything from scratch whenever it's convenient?

Are the cBAD models and blla.mlmodel the same? 
Also, would it be more efficient to just train on top of the default segmentation model in kraken? 

Thank you for your hard work,
Rohan

[1] https://digitalintellectuals.hypotheses.org/3844

**Comment by mittagessen** [comment]
> Can you please point me to the cBAD models so that I can resize those instead of training everything from scratch whenever it's convenient?

You probably mean transfer learning. You can train from an existing
model even if you want to add additional line/region types. Just use the
`-i` option as explaned in the article (and `--resize add` or `--resize
both` to get the types in your dataset).

> Are the cBAD models and blla.mlmodel the same?

They are not exactly the same but interchangeable. The latter has been
trained with some additional material.

> Also, would it be more efficient to just train on top of the default segmentation model in kraken?

Yes, if your material is remotely similar you'll most likely benefit
from starting off the default model.

**Comment by rohanchn** [comment]
Thank you for your feedback. 

Yes, I want to resize an existing model whenever my dataset is somewhat similar. 
Is the dataset used to train blla.mlmodel publicly available ?
Can you please point me to it? 

I looked at the cBAD dataset, and found it somewhat similar to the material I have been working with.

**Comment by mittagessen** [comment]
> Is the dataset used to train blla.mlmodel publicly available ?
> Can you please point me to it?

It's mostly cBAD, the OpenITI Arabic print data, BADAM and some printed
Syriac I'm probably not allowed to make public. Basically a melange of
what we had laying around.

**Comment by rohanchn** [comment]
Makes sense. My guess is BADAM would be the most different among these. 

Thank you for your help.
