### ISSUE TITLE
Add --batch-input syntax in documentation

### ISSUE THREAD

**Issue by sven-nm** [mittagessen/kraken#265]
Hello all, 
This is not really an issue but rather a question : how are you supposed to use kraken with `-I/--batch-input` ? Placing a glob expression (eg `img/*.png`) and a suffix with `-o` does not do anything. What am I am doing wrong ? 

Example using kraken-3.0b24 : 

```
kraken -I /img/*.png -o OCR -h segment  ocr --model /OCR-kraken-models/kraken-models/greek-german_serifs_bsb10234118/greek-german_serifs_bsb10234118.mlmodel
```

**Comment by mittagessen** [comment]
Hmm this is indeed an oversight in the docs. You have to escape the glob
expression so it doesn't get resolved by the shell, like this:

```
$ kraken -I '/img/*.png' -o OCR -h segment ...
```

**Comment by sven-nm** [comment]
Oh got it, thanks a lot ! 😊
