### ISSUE TITLE
Region IDs are not unique in PageXML and ALTO outputs after baseline segmentation

### ISSUE THREAD

**Issue by bencomp** [mittagessen/kraken#269]
After binarizing and segmenting the TIFF version of <https://digitalcollections.universiteitleiden.nl/view/item/3151088>, the PageXML as well as the ALTO outputs have non-unique IDs in `TextRegion` and `TextBlock` (respectively). This happens with the default `blla.mlmodel`.

Could the cause be in `serialization.serialize()`? I don't completely grasp the algorithm for serialisation yet (and the extra closing tags in the Jinja templates), but I get the feeling some merging of block IDs is happening there.

**Comment by mittagessen** [comment]
* bencomp :: 2021-08-02 11:56 Mon:
> Could the cause be in `serialization.serialize()`? I don't completely
> grasp the algorithm for serialisation yet (and the extra closing tags
> in the Jinja templates), but I get the feeling some merging of block
> IDs is happening there.

Are you sure? Mind you that there are block_N and textblock_N
identifiers. The N is just the index in the loop over regions so there
shouldn't be any duplication.

**Comment by bencomp** [comment]
I am sure (trusting the XML tools to point out duplicate values in attributes of type ID and manually confirming): 
[pIV-V_page.txt](https://github.com/mittagessen/kraken/files/6929930/pIV-V_page.txt)
(renamed to txt for GitHub). Notice that the block and textblock numbering isn't in strict ascending order either, but the line numbers are unique and in ascending order.

The command used for creating this file was `kraken -i pIV-V.tiff pIV-V_page.xml -x binarize segment -bl`.

**Comment by mittagessen** [comment]
* bencomp :: 2021-08-04 11:54 Wed:
> I am sure (trusting the XML tools to point out duplicate values in attributes of type ID and manually confirming): 
> [pIV-V_page.txt](https://github.com/mittagessen/kraken/files/6929930/pIV-V_page.txt)
> (renamed to txt for GitHub). Notice that the block and textblock numbering isn't in strict ascending order either, but the line numbers are unique and in ascending order.

I suspect it's related to the region encapsulation of lines during
serialization. The reading order algorithm should ensure that lines in regions
are ordered as a block but there's a 'hole' in the order which results
in the serializer outputting the same region twice. While I can't
promise anything as I'm on vacation, I might push a bugfix if it isn't
too involved.

**Comment by bencomp** [comment]
Please don't let me ruin your vacation!

After playing with the segmentation overlay scripts, I see that the reading order is way off.
![high_pIV-V_page3 xml_lines_default](https://user-images.githubusercontent.com/1303898/128183162-cc714d51-85e9-46d0-881f-75af5d9b47de.png)

Then it makes total sense that the same regions are output multiple times. I modified the script to add the region's ordinal number, as well as the points' ordinal numbers.
![high_pIV-V_page3 xml_regions_text](https://user-images.githubusercontent.com/1303898/128183169-de2d477e-2d03-4f0d-8a9e-68c224d4b360.png)

**Comment by bencomp** [comment]
Further experimenting shows that this scan having two pages is not the issue causing the strange line order. When I split the file and run the whole process on both pages, both files have strange line ordering (and duplication of regions).

![Lines in right page](https://user-images.githubusercontent.com/1303898/128207954-9995296c-9f70-4511-b710-2bd108d35875.png)

Perhaps I should train a segmentation model based on the default `blla.mlmodel`?
Would this page and JSON or Page XML segmentation data be useful resources for a unit test of the reading order algorithm? I'm happy to help with those.

**Comment by mittagessen** [comment]
I think I found the source of the error. The `polygonal_reading_order`
function uses stricter criteria for determining region assignment than
the serializer. That's an easy fix. I'll merge it tomorrow.

> Perhaps I should train a segmentation model based on the default
> `blla.mlmodel`?

Line order isn't trained in the segmenter yet (although that's in the
near-term todo list).

> Would this page and JSON or Page XML segmentation data be useful
> resources for a unit test of the reading order algorithm? I'm happy to
> help with those.

Oh yes, the unit tests are a complete mess right now. Any pull request
containing any tests that actually catch regressions will be merged with
outmost enthusiasm and a round of a beverage of choice if we ever cross
paths in real life.

**Comment by bencomp** [comment]
Great! Running the tests doesn't work yet on my machine – running `python setup.py test` starts running the tests in a loop. Maybe fixing or rewriting the unit tests should be a separate issue.

I now realise that the reading order problem(s) is already mentioned in #267 and #212. It would be great if a simple fix solves those too, but they may be more complex issues.

**Comment by bencomp** [comment]
I think this issue hasn't been resolved yet. Could you reopen it, please?

I think one part of the fix is #285, but there is more. One other part is changing how `serialization.serialize()` adds regions to the list of *page entities* multiple times if lines `n-1` and `n+1` are in region 1 while line `n` is in region 2.
Perhaps it could also help to build a strict hierarchy of regions and textlines before sending the data to the template, so that templates do not have to check whether the entities are regions or lines. Let me open another PR for changing the `serialization.serialize()` behaviour.

**Comment by mittagessen** [comment]
OK, I see it as a chance to write some tests then to address this.
