### ISSUE TITLE
Running Kraken on Apple M1 is tricky

### ISSUE THREAD

**Issue by bencomp** [mittagessen/kraken#270]
I ran into dependency issues when trying to install Kraken on an Apple MacBook with the M1 architecture. After some trial and error, it seems everything I tried works except for PDF processing because I couldn't get [pyvips] working. The core issue is that not all packages on Conda Forge are available for `osx-arm64`.
I will try to describe my experiences and submit a PR if possible, but wanted to create an issue first because I needed to change dependency versions to make it work.

[pyvips]: https://libvips.github.io/pyvips/

By cloning the repository and changing dependencies in environment.yml I managed to get Kraken to run with Python 3.9.

- allow Python 3.7 and up
- pin numpy to 1.19.5
- use torchvision-cpu 0.9.0 and pytorch 1.8.0 from the conda-forge channel (it has osx-arm64 builds, whereas the pytorch channel hasn't)
- install pyvips with pip, because there is no osx-arm64 build on conda-forge (I just created https://github.com/conda-forge/pyvips-feedstock/issues/9)
- `pip install` the cloned repository instead of checking out the master branch from GitHub, as it tries to download different dependencies from requirements.txt that don't work with conda-installed osx-arm64 packages

I can install `libvips` with Homebrew, but I didn't manage to get pip-installed pyvips to find the binary libraries.

It seems to work for me, with the noted exception, but I don't know if the updated dependencies have an effect that I don't see yet. If others have similar experiences or other tips, I'd like to work together to improve support and maybe (I certainly hope I didn't cause #269 myself.)

To be clear: with the updated environment.yaml, I can run `conda create -f environment.yml` and have a new environment called `kraken`.

**Comment by bencomp** [comment]
I'm learning that updates are underway to make `pyvips` (and `coremltools`) available for osx-arm64. It has to wait for `libvips` to become available, which in turn is waiting for `libexif`, `libmatio` and `libgsf` to be succesfully migrated.

**Comment by amitdo** [comment]
It seems that (py)vips is only used for extracting images from PDFs.

Maybe the dependencies list should be split into two files: core (mandatory) and optional.

**Comment by bencomp** [comment]
I pushed https://github.com/bencomp/kraken/tree/m1 with the first of my changes in environment.yml.

@amitdo That sounds like a good idea. However, I don't know how that would work with Conda. Or what would need to change in the kraken code to provide a friendly message to users when they forgot to install the package with extras.

Maybe I should use Rosetta to run x86_64 code, like Apple does with their own Core ML Tools(!) – though I prefer to be able to run native code.

**Comment by mittagessen** [comment]
* Amit D. :: 2021-08-03 14:35 Tue:
> It seems that (py)vips is only used for extracting images from PDFs.

It's used for all kinds of multi-image processing, including JPEG2000s
and TIFFs. 

> Maybe the dependencies list should be split into two files: core (mandatory) and optional.

IIRC doing optional dependencies with setup.cfg and requirements files
is a bit quite ugly. In any case you can just ignore it, the CLI driver
only loads the module with PDF inputs are used.

**Comment by mittagessen** [comment]
I spent the weekend updating the build process and moving everything into the new github workflow CI.  476102b should solve all of the Mac OS ARM issues (*he boldly claims without any way to check*). You even get conda packages for the 3.0.6 release now (including for ARM):
```
$ conda install -c conda-forge -c mittagessen kraken
```

**Comment by raphaelmerx** [comment]
For what it's worth I can run kraken current (3.0.9) on an M1 chip with Python 3.9 without issues, with the following environment:
```
numpy==1.22.2
torch==1.10.2
scikit-image==0.19.1
scikit-learn==1.0.2
scipy==1.7.3
pyvips==2.1.12
```

Where are pre-built wheels available for the above packages on Mac M1 (arm architecture) for Python 3.9.

Of course the main issue is that torch doesn't yet have gpu acceleration for M1 macs, see https://github.com/pytorch/pytorch/issues/47702
