### ISSUE TITLE
"Big" dataset issue and multiprocessing failure

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#274]
Hey there, 
I just encountered for the first time a multiprocessing issue at parsing time that does not seem to be content related but rather OS related, in the form of an exception `unable to write to file /torch_Someid`.

My dataset just grew quite a lot bigger (25k lines in train, dev is 2.6k) by around 5k lines at least.

I am trying to debug what's going on but this might be tied to `/dev/shm` size (16gb on my server with 32gb of RAM).

Outside of playing with SHM, do you have any other idea of what could be done ?

**Comment by PonteIneptique** [comment]
I can confirm it's a `/dev/shm` issue, and I am wondering if software side something can be done: I raised my `/dev/shm` capacity from 16 to 24g, it's now filled by 17g of data, and it's running smoothly in its third epoch.

**Comment by mittagessen** [comment]
* Thibault Clérice :: 2021-08-19 11:01 Thu:
> I can confirm it's a `/dev/shm` issue, and I am wondering if software
> side something can be done: I raised my `/dev/shm` capacity from 16 to
> 24g, it's now filled by 17g of data, and it's running smoothly in its
> third epoch.

Unfortunately, this is a bit of an inherent problem with the
parallelized loader. There's not much that can be done but cranking up
the SHM limits or setting the loaders to 0 which is obviously not
something you'd want.

**Comment by PonteIneptique** [comment]
As a side question, (I'll close the issue after), have you envisionned a way to potentially dump data into HDF5 so that parsing does not need to happen, or at least in an incremental way (add 100 pages to a 600 dataset ? Only parse the 100 new) ?

**Comment by mittagessen** [comment]
* Thibault Clérice :: 2021-08-30 11:26 Mon:
> As a side question, (I'll close the issue after), have you envisionned
> a way to potentially dump data into HDF5 so that parsing does not need
> to happen, or at least in an incremental way (add 100 pages to a 600
> dataset ? Only parse the 100 new) ?

I had thought about it a bit but hadn't looked at the specific
requirements of which preprocessing steps are safe to do in advance and
which have to be done at runtime as they're specific to the particular
network configuration. It shouldn't be too difficult though.

**Comment by amitdo** [comment]
Maybe you can use Numpy's savez instead of HDF5.

https://numpy.org/doc/stable/reference/generated/numpy.savez.html

**Comment by PonteIneptique** [comment]
I feel like saving the "cropped and decoded image" and text, while maybe leaving some room for the processing (Text normalization ?), might be already enough to reduce a lot of IO operations, which numpy could not suport if I am understanding the `Save several arrays`.
But this should probably become a new issue.
