### ISSUE TITLE
skimage version requirement causes error in bbla.segment

### ISSUE THREAD

**Issue by anutkk** [mittagessen/kraken#275]
When running the line:
`baseline_seg = blla.segment(im, model=segmentation_model)`

I got the following error (shortened for clarity):

> /usr/local/lib/python3.7/dist-packages/kraken/lib/segmentation.py in vectorize_lines(im, threshold, min_length)
>     266     sep_map = st_map + end_map
>     267     bl_map = im[2]
> --> 268     bl_map = filters.sato(bl_map, black_ridges=False, mode='constant')
>     269     bin_bl_map = bl_map > threshold
>     270     # skeletonize
> 
> TypeError: sato() got an unexpected keyword argument 'mode'

It turns out that in skimage.filters.sato(), the keyword 'mode' was introduced only in version [0.17](https://scikit-image.org/docs/0.17.x/api/skimage.filters.html#skimage.filters.sato), but does not exist in [0.16](https://scikit-image.org/docs/0.16.x/api/skimage.filters.html#skimage.filters.sato). 

`requirements.txt` has the version requirement:

> scikit-image<=0.17.2

And similarly in `environmnent.yml`.

Thus, in some setups (in my case: Google Colab) skimage's version will remain 0.16.0, whereas the explicit requirements should prevent that.

### Proposed solution

In `requirements.txt` change the line to:

> scikit-image>=0.17.0,<=0.17.2

And similarly in `environmnent.yml`. 

### Workaround

Install the appropriate version of scikit-image before installing kraken:

```
pip install scikit-image==0.17.2
pip install kraken
```

**Comment by mittagessen** [comment]
Thanks for that. I'm not sure anymore why it was pinned to a max of 0.17.2 but it seems to work with the latest scikit-image release. I vaguely remember something about another dependency breaking.
