### ISSUE TITLE
Ability to preparse dataset and dump them into a less "IO / Computation intensive" format

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#276]
As per #274, we started discussing the interest of having something like HDF5 for Kraken. I'll use HDF5 from now on but any similar technology might be cool

My use case if the following:

Right now, with datasets over 20k lines, processing the hundreds of image files and XML files takes up to 30 minutes, with 10 threads on a fairly powerful machine. And sometime, you might want to test few different options of parameters or unicode normalization: in this context, having a one-file dump that ease reading for further steps might be super useful.

Functionalities I could see being very useful:

- Mix dataset type, using a HDF5 file as a basis for the whole training. That might be super useful on eScriptorium, where big dataset are provided as a basis of a new model, instead of tuning a previous model.
- Incrementable HDF5 dump: easily add new data to the HDF5 file, avoids reparsing everything.
- To avoid issues, I can see the HDF5 dataset class dumping info about itself in the file, like somekind of "subversioning", in case the class would change enough to required a new dump to be compatible with the new changes.
- There could really well be a two tier kinda HDF5: one with raw information (text + image cropped), one much more advanced in terms of preprocessing (arrays + text + "augmented" dataset ?) that might introduce more maintenance but more flexibility in terms of where you wanna start from.

**Comment by mittagessen** [comment]
After checking in the code, I'm mostly sure that a basic dump would only need to include the rectified line images before scaling. This should eliminate the most important performance issue as it's mostly the affine transformation on the large image array that is slow. I don't think an advanced version would provide much gain.

The main problem is that it would break augmentation as some of the transformations are global on the page (and have to be). But there could be an option to pre-compute the augmented data and just dump it in there as well.

Keeping it simple like this should also be forward compatible. My only concern is that the last time I worked with python HDF5 libraries is that they were rather annoying to set up, definitely too complex for the average user.

**Comment by mittagessen** [comment]
I just merged the branch.
