### ISSUE TITLE
PIL decompression_bomb_check should give the image filename

### ISSUE THREAD

**Issue by dstoekl** [mittagessen/kraken#299]
On big images PIL fails. It would be nice to have an explicit error message with the precise image filename that causes the error. 

ketos.py", line 565, in train
    trainer = KrakenTrainer.recognition_train_gen(hyper_params,
train.py", line 605, in recognition_train_gen
    training_data = preparse_xml_data(training_data, format_type, repolygonize)
/kraken/lib/dataset.py", line 308, in preparse_xml_data
    Image.open(fp)
/PIL/Image.py", line 3016, in open
    im = _open_core(fp, filename, prefix, formats)
/PIL/Image.py", line 3003, in _open_core
    _decompression_bomb_check(im.size)
/PIL/Image.py", line 2912, in _decompression_bomb_check
    raise DecompressionBombError(
PIL.Image.DecompressionBombError: Image size (185678746 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

**Comment by mittagessen** [comment]
I can't influence what exactly PIL does internally or the information it prints in its exceptions. It might be easiest to wrap the `Image.open` handler to show the filename in addition to the original exception message.

**Comment by kba** [comment]
If you know that the image is legit and you have the memory available, you can disable the check altogether by [setting `Image.MAX_IMAGE_PIXELS = None`](https://stackoverflow.com/questions/56174099/how-to-load-images-larger-than-max-image-pixels-with-pil). I had to do this before for large newspaper pages.

**Comment by mittagessen** [comment]
Yeah, I've seen that in the docs but it feels very unsavory just disabling a safety check that's supposedly there for a good reason. What is the largest image size you've yet encountered? Multiplying that by 4 instead seems a bit more reasonable.

**Comment by kba** [comment]
> What is the largest image size you've yet encountered?

I don't remember now, but your solution (`20k by 20k`) is a reasonable upper bound. We should do the same in [OCR-D](https://github.com/OCR-D/core/issues/735).
