### ISSUE TITLE
ketos train fails with error

### ISSUE THREAD

**Issue by Zerith** [mittagessen/kraken#30]
After building ground truth data, the train command fails with:
![image](https://cloud.githubusercontent.com/assets/1922574/20803613/7466f168-b7f8-11e6-95ce-824e3db6e3ef.png)

**Comment by mittagessen** [comment]
It's not supposed to work (yet) as the CLSTM python bindings aren't complete and can't initialize a new model. There's ongoing work on these bindings and I'll hopefully get around to provide a working command but that's entirely dependent on CLSTM. 

If something isn't documented it might as well doesn't exist (and in this case doesn't).
