### ISSUE TITLE
Problems with PageXml output when segmenting using trained segmentation model

### ISSUE THREAD

**Issue by jacoborrje** [mittagessen/kraken#305]
Hi,

First, thanks for a great application and the continuous development.

I want to use Kraken to segment the regions on a set of pages and identify some specific region types (paragraphs, marginalia, pagenumbers). To my knowledge, training a model using ketos and a trainingset of PageXML files went fine (`'ketos segtrain -f xml *.xml --suppress-baselines'`).

However, I run into problems when using the model to generate new PageXML files from my images. I guess I probably have made a mistake somewhere in the commands. :)

Running `kraken -i 0023.png 0023.xml -f image -x segment -bl --model /home/jacob/SynologyDrive/models/segmenting/best.mlmodel `
yields the result:
```
Loading ANN /home/jacob/SynologyDrive/models/segmenting/best.mlmodel	✓
Segmenting	[5.9539] Failed processing 0023.png: list index out of range
```
The standard baseline model works on the same image, and generates xml output:
```
kraken -i 0023.png 0023.xml -f image -x segment -bl
Loading ANN /home/jacob/python/kraken_venv/lib/python3.7/site-packages/kraken/blla.mlmodel	✓
Segmenting	(slice(2408.0, 2408.0, None), slice(1310.0, 1429.0, None)) - (slice(384.0, 384.0, None), slice(1585.0, 1701.0, None))
(slice(365.0, 370.0, None), slice(577.0, 769.0, None)) - (slice(384.0, 384.0, None), slice(1585.0, 1701.0, None))
(slice(365.0, 370.0, None), slice(577.0, 769.0, None)) - (slice(2408.0, 2408.0, None), slice(1310.0, 1429.0, None))
(slice(1760.0, 1766.0, None), slice(195.0, 555.0, None)) - (slice(384.0, 384.0, None), slice(1585.0, 1701.0, None))
(slice(1760.0, 1766.0, None), slice(195.0, 555.0, None)) - (slice(2408.0, 2408.0, None), slice(1310.0, 1429.0, None))
(slice(2197.0, 2205.0, None), slice(195.0, 700.0, None)) - (slice(384.0, 384.0, None), slice(1585.0, 1701.0, None))
[...]
```
Also, my custom model generates JSON output when skipping the '-x' switch:
```
kraken -i 0023.png 0023.xml -f image segment -bl --model /home/jacob/SynologyDrive/models/segmenting/best.mlmodel 
Loading ANN /home/jacob/SynologyDrive/models/segmenting/best.mlmodel	✓
Segmenting		✓
```
The generated json from my model looks like this:
`{"text_direction": "horizontal-lr", "type": "baselines", "lines": [], "regions": {"page-number": [], "text": [], "marginalia": [[[1349, 2384], [1390, 2384], [1390, 2403], [1360, 2403], [1349, 2384]]], "paragraph": [[[593, 395], [1162, 395], [1225, 527], [1214, 2853], [1140, 2930], [912, 2919], [788, 2974], [186, 2941], [197, 516], [307, 406], [593, 395]]]}, "script_detection": false}`

If someone could give a hint on what's wrong, I would really appreciate it! :)

Again, thanks for all your work!
Best,
Jacob

**Comment by mittagessen** [comment]
The crash is a bug but how the serializer constructed the data structure also meant that pages without lines wouldn't get any regions serialized. I changed the behavior so that if there aren't *any* lines all regions get output. Unfortunately, regions themselves don't have an order (yet) so the order is random. I hope that does what you want.

**Comment by jacoborrje** [comment]
That's great. Thanks for the quick fix! :)
