### ISSUE TITLE
kraken in escriptorium, does not work with Nvidia RTX 3090

### ISSUE THREAD

**Issue by jbarth-ubhd** [mittagessen/kraken#309]
I'm trying to run kraken training on our RTX 3090 within escriptorium.

Issue there: https://gitlab.com/scripta/escriptorium/-/issues/524

Possible cause/solution(?): https://github.com/pytorch/pytorch/issues/49161

As far as I understood, the solution would be »LibTorch 1.7.1 point release is required for new nVidia cards dotnet/TorchSharp#198«.

Would it be possible to change the dependency of kraken from `pytorch<=1.7.0` to `<=1.7.1` or later?

**Comment by mittagessen** [comment]
> Would it be possible to change the dependency of kraken from
> `pytorch<=1.7.0` to `<=1.7.1` or later?

I can bump the minimum version up. Are you sure you're installing the
latest release though? Because right now the range in
environment.yml/setup.cfg is `pytorch>=1.5.0,<1.11`.

**Comment by stweil** [comment]
At UB Mannheim we train with RTX A5000 (similar to RTX 3090, but newer and with less power consumption). I had to use a newer pre-release of `torch`:

    pip install --pre --upgrade -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html torchvision torch

See [details](https://github.com/UB-Mannheim/gt-fraktur/wiki) on our latest training.
