### ISSUE TITLE
`Failed processing image.png: ndim`

### ISSUE THREAD

**Issue by gabays** [mittagessen/kraken#316]
When I run the following command:
```bash
kraken -i OCR17plus/Data/Balzac1624_Lettres_btv1b86262420_corrected/png/Balzac1624_Lettres_btv1b86262420_corrected_0042.png results.txt segment -bl -i OCR17plus/Model/Segment/appenzeller.mlmodel ocr -m OCR17plus/Model/HTR/dentduchat.mlmodel
```
I have the following issue:
```bash
[37.7261] Failed processing OCR17plus/Data/Balzac1624_Lettres_btv1b86262420_corrected/png/Balzac1624_Lettres_btv1b86262420_corrected_0042.png: ndim 
```
The data used is available here: https://github.com/Heresta/OCR17plus

Any idea what the problem could be?

**Comment by Edwin-Carlinet** [comment]
I just had the same problem. This is due to a PIL image passed to skimage while it expects a numpy array.

https://github.com/mittagessen/kraken/blob/9882ba0743797a2d5b0a7b562fcc7235e87323da/kraken/blla.py#L139

The hot fix is:

```py
im_feats = gaussian_filter(sobel(np.asarray(scal_im)), 0.5)
```

**Comment by mittagessen** [comment]
On 22/01/18 08:38AM, Simon Gabay wrote:
> When I run the following command:
> ```bash
> kraken -i OCR17plus/Data/Balzac1624_Lettres_btv1b86262420_corrected/png/Balzac1624_Lettres_btv1b86262420_corrected_0042.png results.txt segment -bl -i OCR17plus/Model/Segment/appenzeller.mlmodel ocr -m OCR17plus/Model/HTR/dentduchat.mlmodel
> ```
> I have the following issue:
> ```bash
> [37.7261] Failed processing OCR17plus/Data/Balzac1624_Lettres_btv1b86262420_corrected/png/Balzac1624_Lettres_btv1b86262420_corrected_0042.png: ndim 
> ```
> The data used is available here: https://github.com/Heresta/OCR17plus
> 
> Any idea what the problem could be?

I'm on a slow internet connection right now so could you run the same
command with the --raise-on-error switch enabled on the kraken command?
This will print the whole stack trace which should make it easier to
pinpoint the problem.

**Comment by mittagessen** [comment]
Could either of you give me your scikit-image version? It used to auto-cast pil images to numpy arrays but that's apparently no longer the case.

**Comment by Edwin-Carlinet** [comment]
Name: scikit-image
Version: 0.19.1
Summary: Image processing in Python
Home-page: https://scikit-image.org
Author: 
Author-email: 
License: Modified BSD
Location: /home/edwin/.local/share/virtualenvs/directory-annotator-back-9b4vsgbe/lib64/python3.9/site-packages
Requires: imageio, networkx, numpy, packaging, pillow, PyWavelets, scipy, tifffile
Required-by: kraken, pero-ocr

**Comment by mittagessen** [comment]
Yup, it's the 0.19 release that's the trouble, although there's nothing in the change log mentioning the new behavior. Well, that's another one for python software API stability. I'll sift through the code to see where else this could crop up and start pinning scikit-image.

**Comment by mittagessen** [comment]
Weird. 0.18.3 works without trouble. Anyway, I'll apply the fix and pin anyway as there wasn't a deprecation warning and I can't find any change log entries back to 0.17 which is the earliest tag that has this change.

**Comment by gabays** [comment]
Thank you!

**Comment by alexislitvine** [comment]
Same issue here today - not sure if it had been fixed but I got the error message again despite applying this:

> I just had the same problem. This is due to a PIL image passed to skimage while it expects a numpy array.
> 
> https://github.com/mittagessen/kraken/blob/9882ba0743797a2d5b0a7b562fcc7235e87323da/kraken/blla.py#L139
> 
> The hot fix is:
> 
> ```python
> im_feats = gaussian_filter(sobel(np.asarray(scal_im)), 0.5)
> ```

**Comment by mittagessen** [comment]
On 22/01/19 02:19PM, alexislitvine wrote:
> Same issue here today - not sure if it had been fixed but I got the error message again despite applying this:

Can you run your command with the `--raise-on-error` option? That should
pinpoint the exact location of the crash.

**Comment by alexislitvine** [comment]
Thanks by looking at the log I was now able to fix it! I was simply modifying the wrong blla.py file!! Sorry.

**Comment by alexislitvine** [comment]
Quick question for you - how do I know whether Kraken uses my GPU? Can't see any activity in my Nvidia-smi.

**Comment by mittagessen** [comment]
On 22/01/20 03:43AM, alexislitvine wrote:
> Quick question for you - how do I know whether Kraken uses my GPU? Can't see any activity in my Nvidia-smi.

Nvidia-smi should show something. Are you telling it to use the GPU (`-d
cuda:0`)?

**Comment by alexislitvine** [comment]
When I do this: 
```
kraken -d cuda:0 -i /home/alexis/images/test2.tiff image.txt segment -bl ocr -m /home/alexis/kraken/en_best.mlmodel
WARNING:root:Torch version 1.10.1+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.9.1 is the most recent version that has been tested.
```
I get this error: 
```
Loading ANN /home/alexis/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/blla.mlmodel	✗

**Comment by mittagessen** [comment]
On 22/01/20 06:50AM, alexislitvine wrote:
> When I do this: 
> ```
> kraken -d cuda:0 -i /home/alexis/images/test2.tiff image.txt segment -bl ocr -m /home/alexis/kraken/en_best.mlmodel
> WARNING:root:Torch version 1.10.1+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.9.1 is the most recent version that has been tested.
> ```
> I get this error: 
> ```
> Loading ANN /home/alexis/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/blla.mlmodel	✗

Could you please run it with the `--raise-on-error` option so I can see
what exactly breaks?

**Comment by alexislitvine** [comment]
same output:

```$ kraken --raise-on-error -d cuda:0 -i /home/alexis/images/test2.tiff image.txt segment -bl ocr -m /home/alexis/kraken/en_best.mlmodel
WARNING:root:Torch version 1.10.1+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.9.1 is the most recent version that has been tested.
Loading ANN /home/alexis/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/blla.mlmodel X
```
