### ISSUE TITLE
line extraction bug for lines written upside down or oblique upside-down

### ISSUE THREAD

**Issue by dstoekl** [mittagessen/kraken#317]
The bug concerning wrong extraction of upside down lines is in extract_polygons in segmentation.py in the fast path for straight baselines with 2 points only. All lines with more than 2 points in baseline are treated correctly.

**Comment by dstoekl** [comment]
My suspicion concerns line 956

**Comment by dstoekl** [comment]
disabling the fast track solves the problem

**Comment by mittagessen** [comment]
On 22/01/21 08:55AM, Daniel Stoekl wrote:
> The bug concerning wrong extraction of upside down lines is in extract_polygons in segmentation.py in the fast path for straight baselines with 2 points only. All lines with more than 2 points in baseline are treated correctly. 

Yeah, I was already at that point as well. The rotation angle is just
calculated wrongly.
