### ISSUE TITLE
PageXML schema requires Created/LastChange date to be UTC, kraken sets local time

### ISSUE THREAD

**Issue by bencomp** [mittagessen/kraken#327]
This is a minor issue, but I do like XML output to be as good as it can get :)

The XML schema for the `Created` and `LastChange` elements in Page XML (or PAGE XML) says *The timestamp has to be in UTC (Coordinated Universal Time) and not local time.*
<https://ocr-d.de/en/gt-guidelines/pagexml/pagecontent_xsd_Complex_Type_pc_PcGtsType.html#PcGtsType_Metadata>

The serialization function provides local time to the templates, although the ALTO template does not add info about time and its schema does not require indication of time zone or that the time be in UTC.

I can provide a PR for this.

**Comment by mittagessen** [comment]
Sure. If it isn't too much trouble I'd prefer the pull request. Otherwise I can do it myself when adding the infrastructure for explicit reading order.
