### ISSUE TITLE
Error while using clstm models

### ISSUE THREAD

**Issue by bmwmy** [mittagessen/kraken#33]
Hi
I have installed kraken and ran the default pyrnn model successfully but when I tried to use any of clstm models I get: "Loading RNN	Segmentation fault (core dumped)" while loading the RNN
I have passed clstm tests also.
N.B. I am using VM with these specs 8cores, 8gb ram, 2gb graphics ram

**Comment by bmwmy** [comment]
Ok I figured out have to install the old clstm version from the branches

**Comment by bmwmy** [comment]
cant decide the correct version or release of clstm to use with kraken please help 
one of branches made loading RNN correctly but fails in processing step giving this trace of error: 
sudo kraken -i yarab.tif yaAllah.txt binarize segment ocr --model toy.clstm
Loading RNN	✓
Binarizing	✓
Segmenting	✓
Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1087, in invoke
    return _process_result(rv)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1025, in _process_result
    **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 144, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 103, in recognizer
    for pred in it:
  File "/usr/local/lib/python2.7/dist-packages/kraken/rpred.py", line 198, in rpred
    pred = network.predictString(line)
  File "/usr/local/lib/python2.7/dist-packages/kraken/lib/models.py", line 96, in predictString
    cls[i] = v
  File "/usr/local/lib/python2.7/dist-packages/clstm.py", line 192, in __setitem__
    return _clstm.Classes___setitem__(self, *args)
TypeError: in method 'Classes___setitem__', argument 3 of type 'int'

**Comment by mittagessen** [comment]
Hi,

the head of [separate-derivs](https://github.com/tmbdev/clstm/tree/separate-derivs) is the one we've been using for everything as the main branch has a bug in the deserialization code causing the segmentation fault you've encountered. Can you tell me which python version on which distribution you're running. The output of ``pip list`` would help a lot, too.

**Comment by bmwmy** [comment]
Hi,

I am using Python 2.7 on Ubuntu 14.04 
pip list output:
adium-theme-ubuntu (0.3.4)
apt-xapian-index (0.45)
beautifulsoup4 (4.2.1)
chardet (2.0.1)
click (6.6)
clstm (0.0)
colorama (0.2.5)
command-not-found (0.3)
debtagshw (0.1)
decorator (3.4.0)
defer (1.0.6)
dirspec (13.10)
duplicity (0.6.23)
future (0.16.0)
h5py (2.2.1)
html5lib (0.999)
httplib2 (0.8)
Jinja2 (2.8.1)
kraken (0.9.0)
lockfile (0.8)
lxml (3.3.3)
MarkupSafe (0.23)
matplotlib (1.3.1)
numexpr (2.2.2)
numpy (1.8.2)
oauthlib (0.6.1)
ocropy (0.2)
oneconf (0.3.7.14.4.1)
PAM (0.4.2)
pexpect (3.1)
Pillow (2.3.0)
pip (9.0.1)
piston-mini-client (0.7.5)
protobuf (3.1.0.post1)
pycrypto (2.6.1)
pycups (1.9.66)
pyenchant (1.6.5)
pygobject (3.12.0)
pyOpenSSL (0.13)
pyparsing (2.0.1)
pysane (2.0)
pyserial (2.6)
pysmbc (1.0.14.1)
python-apt (0.9.3.5ubuntu2)
python-bidi (0.4.0)
python-dateutil (1.5)
python-debian (0.1.21-nmu2ubuntu2)
pytz (2012rc0)
pyxdg (0.25)
regex (2016.12.27)
reportlab (3.0)
requests (2.2.1)
scipy (0.13.3)
sessioninstaller (0.0.0)
setuptools (3.3)
six (1.5.2)
software-center-aptd-plugins (0.0.0)
system-service (0.1.6)
tables (3.1.1)
Twisted-Core (13.2.0)
Twisted-Web (13.2.0)
unity-lens-photos (1.0)
urllib3 (1.7.1)
wheel (0.24.0)
xdiagnose (3.6.3build2)
zope.interface (4.0.5)

**Comment by bmwmy** [comment]
Ok I have manage it.
Have to use separate-derivs clstm but have to modify its source with this command before installing clstm
$ cd clstm
$ sed -i 's/isnan/std::isnan/g' `grep "isnan" -rl`

**Comment by christophered** [comment]
@bmwmy how do I install the separate-derivs clstm
what is this command?
sed -i 's/isnan/std::isnan/g' grep "isnan" -rl
