### ISSUE TITLE
any command results in Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by rmrf-sl4sh** [mittagessen/kraken#335]
Illegal instruction (core dumped)

how do I go about troubleshooting?

**Comment by mittagessen** [comment]
Which platform are you running on and how did you install kraken? It is most likely not a kraken bug but a broken library package (probably something complex like pytorch).

**Comment by jdqw210** [comment]
Fedora 34 server, installed via 
`pip install .`
after cloning the git

I followed the guide at https://kraken.re/master/index.html

The newer version of pytorch was installed so I uninstalled and installed the one the program recommended... So I think you are likely correct, my python is probably not set up correctly

**Comment by mittagessen** [comment]
On 22/03/22 01:28PM, z3n wrote:
> The newer version of pytorch was installed so I uninstalled and
> installed the one the program recommended... So I think you are likely
> correct, my python is probably not set up correctly

pytorch 1.11 *should* be fine, I just haven't had a chance to pin the
requirements to the latest version. Are you using a python virtual
environment or a global install? The latter can mean that there half a
billion other things happening in the python environment which
frequently interfere with each other.

**Comment by jdqw210** [comment]
I went with a global install, I'll give it a shot in a virtual env and see. Thanks for the reply
