### ISSUE TITLE
coloms

### ISSUE THREAD

**Issue by Hoekman57** [mittagessen/kraken#337]
I trained a double colom in escriptorium although I splitted them in 2 coloms with the sciccor tool Then I exported to page and trained wioth the latest version of kraken. Is it possible to get a 2 colom OCR-ed pdf (or other format) output with the 2 coloms layout?

**Comment by mittagessen** [comment]
Sorry for not getting back to you earlier. The lines should be associated automatically with the columns *and* the columns should be automatically in the right order (left-to-right for LTR main script/right-to-left for RTL main script) but an explicit semantic annotation as columns doesn't happen as the region detector is agnostic to the nature of the regions. The serializations that you can get out of kraken are either ALTO or PageXML though so no automatic PDF generation. I hope that clears it up.
