### ISSUE TITLE
Python API for Kraken version?

### ISSUE THREAD

**Issue by stweil** [mittagessen/kraken#338]
It looks like there is currently no API to get the Kraken version. Therefore eScriptorium currently has to run a subprocess `kraken --version` to get that information. That fails if there is no `kraken` in the `PATH`. A Python API would avoid the need for a subprocess and the `PATH` problem.

**Comment by kba** [comment]
Could also be done without a dedicated API, e.g. with setuptools:

```
from pkg_resources import get_distribution
get_distribution('kraken').version
```

**Comment by stweil** [comment]
Thank you, @kba. That works perfectly, see https://ocr-bw.bib.uni-mannheim.de/escriptorium2/.

**Comment by stweil** [comment]
See https://gitlab.com/scripta/escriptorium/-/merge_requests/222.
