### ISSUE TITLE
Compile doc says "--workers" only apply to CPU mode, but AFAIK there is no GPU mode for compile

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#339]
This is a small "issue". AFAIK, there is no GPU mode for `ketos compile`, or I missed it.

In the following CLI, it seems to imply it has one. I assume it's simply a copy/past of other CLI entry help value.

https://github.com/mittagessen/kraken/blob/0f82bbb9717eb2e5b9ffb6db6e842a1c1008c7f7/kraken/ketos.py#L1189

**Comment by mittagessen** [comment]
Indeed, there isn't a GPU mode for dataset compilation. I fixed the help message.
