### ISSUE TITLE
kraken linegen?

### ISSUE THREAD

**Issue by wrznr** [mittagessen/kraken#34]
## Expected Behavior
@amitdo pointed me to kraken's linegen implementation using pango+cairo. However 'linegen' is no valid subcommand of 'kraken'. It would be neat if one could access the contents of 'linegen.py' from kraken's CLI.

## Current Behavior
'linegen.py' is not wrapped in kraken.py

## Possible Solution
Add 'linegen' as a subcommand to 'kraken'.

**Comment by amitdo** [comment]
http://kraken.re/ketos.html

**Comment by mittagessen** [comment]
What he said.
