### ISSUE TITLE
Workstation Recommandations

### ISSUE THREAD

**Issue by Juliettejns** [mittagessen/kraken#347]
Hi, 

I am currently working on the OCRization of archives on behalf of Inserm, French NIH. I am taking the liberty of contacting you following a couple questions that arose out.

We would like to train our own segmentation models in order to process our documents (medical reports containing graphs, tables, images…). In order to do that, we want to install eScriptorium and Kraken on a local workstation, with a GPU.
We do not have this material yet and therefore we are considering its purchase. Considering we did not found any information concerning the GPU in kraken’s documentation, I thus turn to you.

What would you recommend in term of: OS, GPU, Ram, Disc Type? We dispose of  15000 images for training our model. Each image is 300 Ko. We would like to train our model on 3000 images.

Thank you in advance for your help and attention.

Best, Juliette

**Comment by mittagessen** [comment]
Ah sorry for not answering your email from two weeks ago. I had a response typed out but must've forgotten sending it off.

For training any remotely recent system with 16Gb memory upwards should be sufficient but more is better especially if multiple users are supposed to use that system in parallel. 64-128Gb is probably best for a small installation were <10 users are regularly doing work in parallel. For the GPU side you should estimate at least 10Gb per training session for the segmenter, ~2Gb for the recognizer (although we're in the process of fiddling with the architecture so something like 4-6Gb is better long-term) so multiply those numbers by the number of parallel training processes you want to have available. There's not exactly a need for SSDs as the you can usually saturate the bus to the GPU from hard disks. You should keep in mind that there will be a couple of copies around of each image so keep enough spare space around. CPU doesn't matter that much, but more cores equal more or less linear speedup in inference and you'd need ~8 worker threads per training process to make optimal use of the GPU.

Depending on your budget and other requirements it might be easier to use our larger installation at the Paris observatory that has plenty of both storage space and training capability. It wouldn't be free but would absolve you of acquiring your own system.

**Comment by Juliettejns** [comment]
Thank you very much for that helpful answer and for your proposal of using your installation. We are going to contact the Paris observatory about that.

**Comment by dstoekl** [comment]
@Juliettejns pls contact me for that via email as I am one of the directors of this cluster, the observatory is only hosting us.
