### ISSUE TITLE
python dependency conflicts with pip and conda 

### ISSUE THREAD

**Issue by Oeconomo** [mittagessen/kraken#348]
Hello ! 
I've been trying for days now to install kraken on my intel 2020 macbook. I am fairly new to DH, but I learn quickly and have a feeling I am doing everything correctly. I've tried everything. I've tried with venv and virtualenv, also with conda, which I reinstalled twice. I've tried with python 3.7, 3.8 and 3.9. I then tried in an Ubuntu virtual machine, and with an M1 macbook 2022 macbook, and problems are exactly the same : 

- conda install in a conda environment (conda install -c conda-forge -c mittagessen kraken) : 
```
(kraken_conda) MacBook-Pro-de-Esteban:~ EstebanSanchez$ conda install -c conda-forge -c mittagessen kraken
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
```                                         

- conda install with the github repo and environment.yml. It just stays like this for hours : 
```
(base) MacBook-Pro-de-Esteban:kraken EstebanSanchez$ conda env create -f environment.yml

Collecting package metadata (repodata.json): done

Solving environment: |
```

- pip install : this actually works, but each time I use kraken commands, a warning says that there are dependency problems with torch and torchvision. I tried to manually downgrade these packages, but then kraken breaks : 
`WARNING:root:Torch version 1.11.0 has not been tested with coremltools. You may run into unexpected errors. Torch 1.10.2 is the most recent version that has been tested`

Could someone tell me what I am doing wrong, or if there is an external problem ?
Thanks !

**Comment by Oeconomo** [comment]
Hello, thank you for your response !

I don't know if M1 architecture would be the problem, as this happens on my 2020 intel macbook, and also on an ubuntu virtual machine (virtualbox), and on an M1 2022 mac.
On my intel 2020 mac : 
- the mamba installation of the dev version with environment.yml did work ! 
- the mamba installation of the stable version (mamba install -c conda-forge -c mittagessen kraken) shows the following error : 
```
(kraken_conda) MacBook-Pro-de-Esteban:kraken EstebanSanchez$ mamba install -c conda-forge -c mittagessen kraken

        [mamba logo]
        mamba (0.7.6) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

Looking for: ['kraken']

conda-forge/osx-64       Using cache
conda-forge/noarch       Using cache
pkgs/main/osx-64         [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/osx-64            [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
mittagessen/osx-64       [====================] (00m:00s) Done
mittagessen/noarch       [====================] (00m:00s) Done
Encountered problems while solving.
Problem: nothing provides cudatoolkit >=10.2 needed by kraken-4.1.2-0

(kraken_conda) MacBook-Pro-de-Esteban:kraken EstebanSanchez$ 
```
- So I ran the following command : `conda install -c anaconda cudatoolkit` , which installs version 9.0, but the same problem arises. A quick search seems to indicate that conda version of cudatoolkit for mac doesn't have a version greater than 9.0 : https://anaconda.org/anaconda/cudatoolkit
Is there a way to install version 10.2 for mac ?

- I also tried in ubuntu (virtualbox virtualmachine), but nor the conda installations, nor the mamba ones work. Mamba indicates other problems (for instance, it cannot find a python 3.1 version). There must be a problem with my virtual machine so I would have to create a new one in order to make sure it is clean.

Best regards,
Esteban

**Comment by mittagessen** [comment]
OK, that's probably the problem then. The pinned stable version of pytorch requires cuda 10.2 which is not available for MAC ARM (at least I don't see a release for it on anaconda.org). You can install through the environment file which only pins the minimum versions actually needed but to make the binary packages work I'd need to change how the build works as unpinned dependencies are too slow for the github CI.

For the ubuntu part, are you sure it is python 3.1 and not 3.10? Depending on how virtualbox is set up you might have a virtualization as ARM architecture and not full emulatio of x86 which runs into the same problems as your Mac OS X install as there aren't a lot of Linux ARM anaconda packages.
