### ISSUE TITLE
linegen: OpenType ligatures 

### ISSUE THREAD

**Issue by amitdo** [mittagessen/kraken#35]
https://github.com/tesseract-ocr/tesseract/pull/288

This PR is from Nick White, so I guess it's important for Ancient Greek.

**Comment by mittagessen** [comment]
Putting the ligatures explicitly in the text works just as well (there are code points for most "common" ligatures) and offers more direct control over the output. Let me see if there's a way to version check the existence of this function through ctypes.

AFAIK there aren't any ligatures in polytonic Greek typesetting although they are ubiquitous in most Latin texts of pre-20th century editions.
