### ISSUE TITLE
Support training recognition models with only line bounaries coordinates in Page XML or Alto input.

### ISSUE THREAD

**Issue by mohamed-ali** [mittagessen/kraken#352]
Hi,

 Thanks for building and maintaining Kraken. 

  I attempted to train a recognition model using the RASM2019 dataset available here https://www.primaresearch.org/RASM2019/. 
 This dataset provides the coordinates of line boundaries, but not the Baselines in Page XML format.
  Because Kraken skips lines where the baseline is missing, due to https://github.com/mittagessen/kraken/blob/master/kraken/lib/xml.py#L272, it leads to having an empty dataset, thus training fails to start.

 I understand the baseline is needed to train a segmentation model, but could you confirm if it is also needed to train a recognition model? 

-  If not, could you support training with a dataset that doesn't have the baselines?
-  If yes, are you aware of a method in Kraken or elsewhere that could add the baseline to the existing dataset to fit Kraken's requirement?  I am currently looking at this https://centerline.readthedocs.io/en/latest/ to attempt to infer the baseline from the boundaries polygon, but would appreciate suggestions if any.

Thanks.

**Comment by mittagessen** [comment]
Yes, the baseline is needed for recognition in addition to the bounding polygon as the text line has to be projected onto the plane to be able to feed a horizontal line into the recognizer. For simple texts (printed or straight and regular handwriting) it is easy to approximate one from the boundary but RASM is sufficiently complex that that doesn't work too well without a lot of fiddling around.

**Comment by mohamed-ali** [comment]
This paper claims it has used Kraken on the RASM2019 dataset, among others,: https://arxiv.org/abs/2112.08692 (see 5.1 Experimental Detail). 
But thanks for the insights.

**Comment by mittagessen** [comment]
We're working with the people responsible for that paper; IIRC one of the people in our group tried to approximate the baselines in RASM which worked for roughly ~90% of them. I can see if the data is still around.
