### ISSUE TITLE
Zero-width Non-joiner

### ISSUE THREAD

**Issue by ZahraSL** [mittagessen/kraken#355]
I am using a Persian-Arabic OCR model to OCR my dataset in escriptorium, but, the model does not recognize the ZWNJ well. I would like to know is there any way to improve model in recognizing ZWNJ, for example, fine-tune the model with more samples including ZWNJ? like when we want to improve the recognition of other characters?

**Comment by mittagessen** [comment]
The ZWNJ is a bit problematic as it isn't directly linked to a visual feature but only changes the surface forms of adjacent characters, making it harder for the model to learn than other features. By and large it should be learnable with sufficient examples though.

Depending on the purpose you want the OCRed text for you might not actually need the ZWNJ in there and could safely strip them out. Obviously it would be desirable for edition work but for most kinds of NLP they should be discardable without any issues further down the pipeline.
