### ISSUE TITLE
ketos --prefill not rendering the transcriptions in the HTML file

### ISSUE THREAD

**Issue by ljpetkovic** [mittagessen/kraken#359]
#### Describe the bug
The prefilled transcriptions (lines) do not appear when I open the HTML file in the browser.

#### Steps to reproduce 
```
!ketos transcribe -o material/test_prefill.html --prefill material/lectaurep_base.mlmodel img/M1119_03_R416_005r.jpg
```
#### Current behaviour (bug)
The prefilled transcriptions (lines) do not appear when I open the HTML file in the browser, even though the transcribed lines do exist in the HTML file, e.g.:
```
<li id="line_1" contenteditable="true" spellcheck="true" data-bbox="573, 144, 2520, 347" data-placeholder="Enter text for line 1">
Registre du Comité d Administration
</li>
```

#### Expected behaviour (correct)
The prefilled lines appear immediately in the browser.

#### Write here or upload an image/video
<img width="1190" alt="test" src="https://user-images.githubusercontent.com/42590315/169666075-727b4603-74f9-48d1-8c0b-2f5ad9e44d21.png">

#### Additional comments
Transcribed lines not rendering in Firefox, Safari and Chrome.

/label ~Bug

**Comment by mittagessen** [comment]
`ketos transcribe` tool is a legacy tool that only works with models trained on bounding box image data as it only supports the old non-trainable segmenter. You should see a warning to that notion when running the command. It is weird that it even outputs any text at all. I'd suggest using  [escriptorium](https://escriptorium.fr/) as it is much more suited for any work on handwritten material. I'll still look into the issue but it can take a couple of days as I'm on a deadline for an article.

**Comment by ljpetkovic** [comment]
Indeed, I have a couple of warnings when I run `ketos transcribe` that may explain the issue:
```
WARNING:root:scikit-learn version 1.0.2 is not supported. Minimum required version: 0.17. Maximum required version: 0.19.2. Disabling scikit-learn conversion API.
WARNING:root:TensorFlow version 2.8.0 has not been tested with coremltools. You may run into unexpected errors. TensorFlow 2.6.2 is the most recent version that has been tested.
WARNING:root:Keras version 2.8.0 has not been tested with coremltools. You may run into unexpected errors. Keras 2.6.0 is the most recent version that has been tested.
WARNING:root:Torch version 1.11.0+cu113 has not been tested with coremltools. You may run into unexpected errors. Torch 1.10.2 is the most recent version that has been tested.
Loading ANN✓
Reading images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00 0:01:22
Writing output ✓
```

I will definitely try to switch to escriptorium, thank you for the suggestion!

**Comment by ljpetkovic** [comment]
P.S. Same problem occurs in case of the typewritten docs.

**Comment by ljpetkovic** [comment]
However, the "invisible" lines become visible and are well extracted only when running `!ketos extract --output gt/ ./material/test_prefill.html`.
