### ISSUE TITLE
polygonization fails in a few cases

### ISSUE THREAD

**Issue by jjarosch** [mittagessen/kraken#360]
When repolygonizing from manually created baselines (using [contrib/repolygonize.py](../blob/master/kraken/contrib/repolygonize.py)) or when segmenting using a blla model, some line polygons extend way above or below the baseline:
![grafik](https://user-images.githubusercontent.com/23742686/170846954-04bd5b4e-46fb-4002-bc02-7b19c0a398da.png)

The `scale` parameter of `calculate_polygonal_environment` has some influence on the amount of errors – fewer with lower values. (The above example is with a `scale` value of 1300, reduced from the preset of 1800.)

I’ve mulled the occurrences of the error over and finally noticed a clustering: The errors all seem to occur when the baseline is around a y position divisible by 1000.
![grafik](https://user-images.githubusercontent.com/23742686/170846614-b421ada1-e733-45b2-97e4-80cb895085b2.png)

The repolygonized PAGE XML files are all available [here](https://gitlab.rlp.net/sahara/foucauld/kraken/-/tree/dev/input). The image files are not in the repo. Do you think this is connected to my particular scans – i.e. do I need to upload sample files for you?

**Comment by mittagessen** [comment]
Could you tell me which version of kraken you're running? There was a bugfix for overly large polygons like this in early April (release 4.1.2).

**Comment by jjarosch** [comment]
Looks like that’s it! The polygons I looked at yesterday were created by 4.0.0, I believe. I updated in the middle of trying various things.
I just re-created two files with 4.1.2 and they’re good now. I’ll re-run everything and look at the large scale (but that may take up to a few weeks).
Thanks!

**Comment by jjarosch** [comment]
I’ve re-run all relevant pages and it’s looking good. Baseline length and polygon area are now in a relatively clean linear relation to each other:
![grafik](https://user-images.githubusercontent.com/23742686/171066636-e7c40a6a-971a-4545-9784-462fd2fed4f4.png)
The segmented linear regression shown in red has, I think, reasonable residuals:
![grafik](https://user-images.githubusercontent.com/23742686/171066698-f9493c1a-ea4d-457a-9694-4a9a51b0ab92.png)
(The shift in the residuals after the first ca. 9000 data points exists because the polygons from segmentation are slightly different from those from repolygonization.)

The two clear outliers are completely unrelated to the issue described above. One of them might be worth showing (just as a digression):
![grafik](https://user-images.githubusercontent.com/23742686/171066767-a9ea5038-41da-4caa-b13c-0d972329e3f1.png)
The issue is resolved on my end, then. Thanks again!

**Comment by mittagessen** [comment]
The last one is still a bug (areas below/above an adjacent baseline should be masked out). I suspect that might be because the line below falls between the sampling intervals of the baseline to be polygonized but without the image and line data I can't really say.
