### ISSUE TITLE
masking of adjacent lines error

### ISSUE THREAD

**Issue by jjarosch** [mittagessen/kraken#362]
Since you mentioned some interest in this error, I’ll give full details here.

![grafik](https://user-images.githubusercontent.com/23742686/171066767-a9ea5038-41da-4caa-b13c-0d972329e3f1.png)

This is the result of a baseline segmentation using a custom model.

The image file is available [here](https://seafile.rlp.net/f/1b309bb526ce40b584cd/?dl=1) for the foreseeable future (but not permanently). The segmentation call is [here](https://gitlab.rlp.net/sahara/foucauld/kraken/-/blob/9ff7ff7214ec9f8bad59c5a5bd31d38adf791af4/segment.sh#L12), the model [here](https://gitlab.rlp.net/sahara/foucauld/kraken/-/blob/9ff7ff7214ec9f8bad59c5a5bd31d38adf791af4/models/model_blla_best.mlmodel) and the resulting PAGE XML [here](https://gitlab.rlp.net/sahara/foucauld/kraken/-/blob/9ff7ff7214ec9f8bad59c5a5bd31d38adf791af4/layouts/1958.xml).

Kraken version 4.1.2

**Comment by mittagessen** [comment]
Thanks. I'm on a deadline right now but will have a look in a couple of days.
