### ISSUE TITLE
Avoid having lines spanning over two regions ?

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#369]
Hey @mittagessen,

I had a look at the current segmentation system, and correct me if I am wrong, but currently, if a line spans over two regions, it's not cut in two. Is it intended ?

Example: 
![image](https://user-images.githubusercontent.com/1929830/177616780-f2b110ec-5772-46fe-9be0-9563559175ae.png)

**Comment by mittagessen** [comment]
Yes, regions are independent of line vectorization to allow detection of non-textual regions such as stamps that might overlay text lines. Without some heuristic it also can't easily be changed.

**Comment by PonteIneptique** [comment]
Thanks !
