### ISSUE TITLE
Got error during kraken recognize

### ISSUE THREAD

**Issue by stefanCCS** [mittagessen/kraken#377]
Hi,
I have made a fresh new installation of `kraken` on Ubuntu 22.04. (CPU-only VM).
My simple example does not run.
(I made the same some months ago on Ubuntu 20.04 with Python 3.8, there is has worked fine).
Maybe I need to "downgrade" to Python 3.8?
Or any other reason?
Please clarify...

```
(kraken_venv) krakadmin@kraken:~$ kraken  -i /mnt/OCRD/Calamari/test/FirstTest/00001-oneliner-gray.png /tmp/00001-oneliner-gray.txt binarize segment ocr -s -m en_best.mlmodel
WARNING:root:Torch version 1.11.0+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.10.2 is the most recent version that has been tested.
Loading ANN default     [libprotobuf ERROR google/protobuf/wire_format_lite.cc:581] String field 'clstm.NetworkProto.name' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:581] String field 'kraken.pyrnn.name' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
✗
(kraken_venv) krakadmin@kraken:~$ python --version
Python 3.10.4

```

**Comment by mittagessen** [comment]
You're protobuf version is probably too new as they broke backwards compatibility in their 4.x release. The source of this error is already fixed in main which I'll tag a new release for sometime this month.

PS: You don't need to run the `segment` subcommand if you set the `-s` switch on the OCR part.

**Comment by stefanCCS** [comment]
Many thanks for the information. Looking forward to the new Release.
