### ISSUE TITLE
font recognition?

### ISSUE THREAD

**Issue by jsbien** [mittagessen/kraken#378]
Do I guess correctly that kraken, similarily as the recent versions of tesseract, is unable to distinguish e.g. bold, roman and italics?

**Comment by mittagessen** [comment]
Out of the box that is indeed correct. Some people have trained models that do this kind of text style analysis in conjunction with text recognition and it works quite well but you'd have to prepare a dataset yourself for this purpose. The basic idea is to add an additional token for each style to be recognized and use them as markers in the ground truth. From others' experiments per-word style tokens seems to work best, e.g. for "sample **text** for _demonstration_" -> "sample $text for #demonstration".

**Comment by jsbien** [comment]
Thanks for your quick answer! Can you be more specific about "Some people"? :-)

**Comment by mittagessen** [comment]
@alix-tz was one of them if I remember correctly. There was also a Catalan dictionary project of whose results/approach I've heard only heard of indirectly (I can't find their name right now). I had a [poster](https://github.com/mittagessen/phd/blob/master/chapters/read/poster.pdf) a couple of years ago evaluating a basic duplication approach (one separate label for each character and its style variants) but for word-segmenting languages style-indicating markers on the word level seem to work better.

**Comment by jsbien** [comment]
Thanks again.

**Comment by PonteIneptique** [comment]
Hey,
@gabays cocreated a few datasets around this question. See
https://hal.archives-ouvertes.fr/hal-03355683

Le mar. 9 août 2022 à 6:20 AM, Janusz S. Bień ***@***.***> a
écrit :

**Comment by jsbien** [comment]
Thanks for the link!

**Comment by alix-tz** [comment]
Hi! 

I did use a special character to:
- markup underscored text in one case
- markup printed text in a mainly handwritten set of documents in another case

I don't have datasets handy because it was an experimentation and it was not implemented in the end. But it did work! 

![image](https://user-images.githubusercontent.com/33317799/183593780-86bfcae1-6571-4b36-a583-05c8cf6b96a2.png)

would be transcribed such as each word underscored is preceded with a "`_`". 
```
The quick _brown _fox _jumps _over the lazy dog
```

You also used "`^`" (although we will probably switch to another character) to markup superscripted texts, which in some way is an adaptation of this mechanism.

**Comment by jsbien** [comment]
Thanks for all the answers! Let me present briefly my motivation and limitations.
I would like to make some experiments with [Słownik Geograficzny Królestwa Polskiego](https://en.wikipedia.org/wiki/Geographical_Dictionary_of_the_Kingdom_of_Poland). Some small fragments has been already transcribed and can serve as Ground Truth. Actually my dream is to make high quality OCR of [Linde](https://en.wikipedia.org/wiki/Samuel_Linde)'s [dictionary](http://bc.klf.uw.edu.pl/324/1/JSB-JB_Linde12s.pdf) but this task is much more difficult because it is multilingual. In both dictionaries the information about font is very important. 
I retired several year ago so I have to work single-handed or to try to organize crowdsourcing. I'm not a programmer so I have to use the existing tools,
