### ISSUE TITLE
Kraken installation and training

### ISSUE THREAD

**Issue by christophered** [mittagessen/kraken#38]
Kraken guidance is unclear, there is an insisting need to provide a Video demonstrating the following:

- Installing csltm
- Installing kraken and it's dependencies
- Training kraken on some Arabic language text, both csltm and pyrnn 
- Using the trained model to recognize the image
- along with posting the example image used and it's trained model

@mittagessen Thank you for your hard work, I really hope that you create a Video guidance of the step-by-step process, since I am creating freely licensed models and training data for the Arabic language, but need your help.
Waiting for your reply

**Comment by bmwmy** [comment]
Hi 
This is ubuntu image on vmware with kraken installed 

[download](https://drive.google.com/file/d/0B1VYwsVK6DbgbS11WjNrbEt1MG8/view?usp=sharing)

**Comment by christophered** [comment]
Wow, Thanks @bmwmy your really helpful.
I have tested the ( samefont.tiff with the arabic.clstm ) which showed an error rate of 30%
My next step would be to train my own model and test the possibility of reaching the +90% recognition rate, but @mittagessen replies in the training matter are so confusing to me.
So @bmwmy can you provide an example and the steps to train a new model, and also explaing how to use the Kraken training interface.

![kraken training interface](https://cloud.githubusercontent.com/assets/16248376/25803079/f186ea00-33fd-11e7-9ea4-d64e3b1ddded.jpg)

**Comment by mittagessen** [comment]
First of the arabic-amiri (arabic.clstm) model is crap because it was trained on artificial training data a long time ago, so it is only there for historical interest. Try one of the other ones (arabic-*) and see if they work better.

Sorry I realize the documentation, especially for training, is lacking. Have a look at http://kraken.re/training for my attempt at a relatively low-level introduction to training. There is also an vagrant box with kraken and clstm that is probably different from @bmwmy's virtualbox.

**Comment by christophered** [comment]
@mittagessen here are the test results posted by @bmwmy and confirmed by me.
[Kraken_test_results.tar.gz](https://github.com/tesseract-ocr/tesseract/files/982008/Kraken_test_results.tar.gz)

I saw [the training documentation]( http://kraken.re/training) but still no luck and no cigar. I only managed to create an HTML transcription, but dont know how to train.

Once I train a new model, I am willing to help better document Kraken, but til then, @mittagessen I hope that you create a Video of step-by-step training an Arabic Model guide.

**Comment by mittagessen** [comment]
Honestly, I don't see myself getting around to make a video any time soon. I don't particularly like doing stuff like this and it would take at least a whole day out of my schedule.

**Comment by christophered** [comment]
@mittagessen I understand, but I'am only asking you to train a couple of lines, or at-least a guide of how to train using the extracted text from ketos.

**Comment by mittagessen** [comment]
That is all in the documentation I linked. You've run ``ketos transcrib`` to create the transcription interfaces, done some transcribing, now you have to run ``ketos extract`` as shown in the linked document to extract the line image text pairs from the HTML documents. After that just run the train.sh as shown in the documentation and wait. 

If you don't want to use the vagrant box the script is also available [here](https://raw.githubusercontent.com/mittagessen/kraken-vagrant/master/training/train.sh) but you'll have to adjust the path to clstmocrtrain.
