### ISSUE TITLE
Coloms

### ISSUE THREAD

**Issue by Hoekman57** [mittagessen/kraken#383]
I have document with 2 coloms I transcribe them in escriptorium I have Kraken 4 I export the documents into xml and image And then binarize, segment and train with ketos command QUESTION Is there a way to export OCR in the original 2 coloms? (txt or other textformat)?

**Comment by mittagessen** [comment]
Columns are a typographic feature that the segmenter doesn't really know about but the text blocks it output per default are often a good approximation. You could just extract the text block regions from the XML with your preferred XML processing tool and treat their contents as separate columns.
