### ISSUE TITLE
Can I provide a manifest file with path to .xml files to compile a binary dataset?

### ISSUE THREAD

**Issue by rohanchn** [mittagessen/kraken#384]
Can I provide a manifest file with path to .xml files to compile a binary dataset with ```ketos compile```?

**Comment by PonteIneptique** [comment]
Hi @rohanchn, while this is a feature that would me nice, my go-to command is the following:

`cat TEXT_FILE | xargs  -d '\n' ketos compile --ignore-splits -f alto -o train.arrow --workers 8`

xargs takes each line from TEXT_FILE and splits it into separate values. `-d '\n'` ensures that files containing spaces are not split (default behaviour)

**Comment by rohanchn** [comment]
Thank you!
