### ISSUE TITLE
Non-encodable sequence warning with binary dataset

### ISSUE THREAD

**Issue by rohanchn** [mittagessen/kraken#385]
I am using a binary dataset to train a recognition model for urdu (rtl) with ``` kraken==4.1.2 ``` and I think I am getting a similar ``` Non-encodable sequence ``` warning as #340. However, unlike #340, I don't specify normalization in my training command.

Can you please explain what this means for the resulting model?

**Comment by PonteIneptique** [comment]
Hey @rohanchn,
Again, I am not @mittagessen and I just have found myself having had to deal with these kind of issues here and there.
First, if it's on PyPi, you should try `4.2.0` (not tested yet) that has implemented some fixes for this.
Then, I'd recommend sharing the log of your issue :)

**Comment by rohanchn** [comment]
Okay, I think I am don't this warning after specifying normalization in the command. Still would love to know what was happening here.

**Comment by PonteIneptique** [comment]
@rohanchn Pretty sure the logs would help to reply to you ;)

**Comment by rohanchn** [comment]
Thank you. Here's the command: 
```ketos train --augment --workers 8 -d cuda:0 -f binary --base-dir R --min-epochs 20 -w 0 -s '[1,120,0,1 Cr3,13,32 Do0.1,2 Mp2,2 Cr3,13,32 Do0.1,2 Mp2,2 Cr3,9,64 Do0.1,2 Mp2,2 Cr3,9,64 Do0.1,2 S1(1x0)1,3 Lbx200 Do0.1,2 Lbx200 Do.1,2 Lbx200 Do]' -r 0.0001 -o models/bl/7_ur urdu.arrow```

Warning looked like this:
```stage 0/∞  ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5982/26481 0:11:14 0:04:05  early_stopping: 0/5 -inf[09/23/22 12:30:20] WARNING  Non-encodable sequence {ب اس... encountered. Advancing one code point.                                                                             codec.py:131
WARNING:kraken.lib.codec:Non-encodable sequence {ب اس... encountered. Advancing one code point.
stage 0/∞  ━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━ 13635/26481 0:06:33 0:08:03  early_stopping: 0/5 -inf[09/23/22 12:34:17] WARNING  Non-encodable sequence » و... encountered. Advancing one code point.                                                                                 codec.py:131
WARNING:kraken.lib.codec:Non-encodable sequence » و... encountered. Advancing one code point.
stage 0/∞  ━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━ 14631/26481 0:06:04 0:08:33  early_stopping: 0/5 -inf[09/23/22 12:34:48] WARNING  Non-encodable sequence <... encountered. Advancing one code point.                                                                                   codec.py:131
WARNING:kraken.lib.codec:Non-encodable sequence <... encountered. Advancing one code point.
stage 0/∞  ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 18388/26481 0:04:12 0:10:31  early_stopping: 0/5 -inf[09/23/22 12:36:45] WARNING  Non-encodable sequence { ینا... encountered. Advancing one code point.                                                                               codec.py:131
WARNING:kraken.lib.codec:Non-encodable sequence { ینا... encountered. Advancing one code point.
stage 0/∞  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26481/26481 0:00:00 0:17:28 val_accuracy: 0.76066  early_stopping: 0/5 0.76066```

**Comment by rohanchn** [comment]
I stopped training and used this command to start again: 
```ketos train --augment --workers 8 -d cuda:0 -f binary --base-dir R --normalization NFD --min-epochs 20 -w 0 -s '[1,120,0,1 Cr3,13,32 Do0.1,2 Mp2,2 Cr3,13,32 Do0.1,2 Mp2,2 Cr3,9,64 Do0.1,2 Mp2,2 Cr3,9,64 Do0.1,2 S1(1x0)1,3 Lbx200 Do0.1,2 Lbx200 Do.1,2 Lbx200 Do]' -r 0.0001 -o models/bl/7_ur urdu.arrow```

Now I don't have that warning and its working as expected. 

What was I doing wrong the previous time? Thanks.
