### ISSUE TITLE
More Installation Details

### ISSUE THREAD

**Issue by m00tpoint** [mittagessen/kraken#39]
For the documentation: On a clean install of Linux Mint the following were needed:

pip install -U pip setuptools
apt install build-essential python-dev

**Comment by christophered** [comment]
@m00tpoint can you create a video of training a new model  on arabic text and using it in recognition?

**Comment by mittagessen** [comment]
Are you sure that you need build-essential and python-dev? A recent version of pip should just install the binary wheels without compiling anything.

**Comment by m00tpoint** [comment]
This is what I did on a fresh Mint install before the install would complete.

**Comment by m00tpoint** [comment]
Not for Arabic since I am not conversant. Fractur is my current focus and maybe could help with that if needed

**Comment by christophered** [comment]
@m00tpoint do you how to train ?

**Comment by christophered** [comment]
@mittagessen close this topic
