### ISSUE TITLE
[ketos-compile] extract_polygons fails on empty sequence (master)

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#395]
When running ketos-compile, I run into this specific error on multiple file.

From eScriptorium viz or the XML, I can't catch what's wrong with this specific line.

Files attached to debug.

```python-tb
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/thibault/.kraken/lib/python3.8/site-packages/kraken/lib/arrow_dataset.py", line 54, in _extract_line
    line_im, line = next(extract_polygons(im, {**xml_record, seg_key: [rec]}))
  File "/home/thibault/.kraken/lib/python3.8/site-packages/kraken/lib/segmentation.py", line 1001, in extract_polygons
    line_idx, dist, intercept = min(((idx, line.project(point),
ValueError: min() arg is an empty sequence
``` 

Logs:
```
{'baseline': [(971, 1100)], 'boundary': [(963, 1123), (963, 1096), (970, 1036), (988, 1042), (971, 1099)], 'text': 'Caecilea', 'tags': {'type': 'default'}, 'split': None}
```

Failing code:

https://github.com/mittagessen/kraken/blob/126406400e118f747798785ea3206dd3c7bbb62b/kraken/lib/segmentation.py#L1001-L1003

Files:
[1880.zip](https://github.com/mittagessen/kraken/files/9752952/1880.zip)

**Comment by PonteIneptique** [comment]
Do you want me to propose at least a try/except to avoid crashing the compilation in a PR ?

**Comment by mittagessen** [comment]
Arrrgh, sorry. I must have forgotten about this one. I'll look into it tomorrow to see why it crashes. In principle the compilation should ignore broken line extraction but it only checks for 'expected' exceptions that are produced by `extract_polygons()`. It might be a good idea to change that.
