### ISSUE TITLE
ERROR    Failed processing test.pdf: cannot identify image file 'test.pdf'              kraken.py:402

### ISSUE THREAD

**Issue by ljpetkovic** [mittagessen/kraken#396]
**Problem**
Cannot run kraken on a PDF file using the [HTR-United-Manu_McFrench.mlmodel](https://zenodo.org/record/6657809#.Y0fZ_ErP3tg).

**Expected behaviour**
Producing an OCRised TXT file from a PDF file.
```
Loading ANN HTR-United-Manu_McFrench.mlmodel	✓
Binarizing	✓
Segmenting	✓
Processing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 28/28 0:00:00 0:00:05
Writing recognition results for test.pdf	✓
```
**Current behaviour**
The model does not produce the OCRised TXT file from the PDF file.
`ERROR    Failed processing test.pdf: cannot identify image file 'test.pdf'              kraken.py:402`

**Steps to reproduce the behaviour**
1. Installed kraken: `pip install kraken[pdf]`
2. Cloned the repo: `git clone git@github.com:mittagessen/kraken.git`
3. Placed the test file into the `/kraken/tests/resources/` directory
4. Downloaded the model: `kraken get 10.5281/zenodo.6657809`
5. Ran the model: 
* without the `-p` or `--pdf-format` flag: 
`kraken -i test.pdf test.txt binarize segment ocr -m HTR-United-Manu_McFrench.mlmodel`
* with the `-p` or `--pdf-format` flag: 
`kraken -p -i test.pdf test.txt binarize segment ocr -m HTR-United-Manu_McFrench.mlmodel`
`kraken --pdf-format -i test.pdf test.txt binarize segment ocr -m HTR-United-Manu_McFrench.mlmodel`

**Information about the Issue**
Kraken works on a JPG file:
```
Loading ANN HTR-United-Manu_McFrench.mlmodel	✓
Binarizing	✓
Segmenting	✓
Processing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 28/28 0:00:00 0:00:05
Writing recognition results for test.jpg	✓
```
**Specifications**
OS: Ubuntu 22.04.1 LTS (Linux)

**Comment by mittagessen** [comment]
There's a misunderstanding. The `--pdf-format` option isn't a flag but a formatting option that determines how the individual pages of the input document are mapped onto output files (per default `source.pdf -> source_000001.ext source_000002.ext ...`).

The select a PDF input file you need to set the `--format-type/-f` to `pdf`: 
```
kraken -f pdf -I test.pdf -o .txt segment -bl ocr -m HTR-United-Manu_McFrench.mlmodel
```

Binarization isn't any longer necessary.
