### ISSUE TITLE
Manual partition and binary format

### ISSUE THREAD

**Issue by matgille** [mittagessen/kraken#397]
Hi, 

Is it possible to train a model with a manual split between train and test data that has been compiled by ketos to speed up training ? 

Something like 

`ketos train -f binary -t ../../binary/train_set.arrow -e ../../binary/test_set.arrow other_args`

which raises `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 8: invalid start byte`

Actually what I want to do is to be able to reproduce my tests on the same test corpus used for training and I don't know how to use `ketos test` to do it. 

Am I missing something (a lot of things) ?

Thanks, 

Matthias

**Comment by mittagessen** [comment]
On 22/10/20 10:52AM, Matthias Gille Levenson wrote:
> Works like a charm with alto files.

Just like with alto files you need to give it a text file that contains
a list of binary files you want to use for training and validation
purposes.

> Actually what I want to do is to be able to reproduce my tests on the
> same test corpus used for training and I don't know how to use `ketos
> test` to do it. 

There are a couple of ways to go about this. You can compile a dataset
with a fixed training/validation/test split with e.g. `--random-split
0.8:0.1:0.1`. You can also transfer the splits defined inside PageXML
files into the binary files with `--save-splits` (by setting the
'custom' field of the text line to `split: [train|validation|test]`). Or
you keep everything in separate arrow files.

**Comment by matgille** [comment]
Noted, thank you for your answer !
