### ISSUE TITLE
Getting identical epoch numbers on recognition training

### ISSUE THREAD

**Issue by lauxley** [mittagessen/kraken#398]
When doing recognition training from escriptorium we receive the same epoch number multiple times. Seemingly depending on the size of the data, the more data, the more iterations on the same number (just a theory).  
This line is repeted in the logs:  
https://github.com/mittagessen/kraken/blob/75bcac9e57d9d7a5bf51b779c59ff28d44a31d20/kraken/lib/train.py#L125  
For example:   
```
esc-prod-worker-gpu-0-cuda-2.1.9o08kel4o27y@gpu0    | [2022-10-27 00:10:00,507: INFO/ForkPoolWorker-6] Saving to /usr/src/app/media/models/17d6446c/version_0
esc-prod-worker-gpu-0-cuda-2.1.9o08kel4o27y@gpu0    | [2022-10-27 00:11:25,699: INFO/ForkPoolWorker-6] Saving to /usr/src/app/media/models/17d6446c/version_0
esc-prod-worker-gpu-0-cuda-2.1.9o08kel4o27y@gpu0    | [2022-10-27 00:12:51,068: INFO/ForkPoolWorker-6] Saving to /usr/src/app/media/models/17d6446c/version_0
esc-prod-worker-gpu-0-cuda-2.1.9o08kel4o27y@gpu0    | [2022-10-27 00:14:15,928: INFO/ForkPoolWorker-6] Saving to /usr/src/app/media/models/17d6446c/version_0
esc-prod-worker-gpu-0-cuda-2.1.9o08kel4o27y@gpu0    | [2022-10-27 00:15:41,723: INFO/ForkPoolWorker-6] Saving to /usr/src/app/media/models/17d6446c/version_0
esc-prod-worker-gpu-0-cuda-2.1.9o08kel4o27y@gpu0    | [2022-10-27 00:17:06,429: INFO/ForkPoolWorker-6] Saving to /usr/src/app/media/models/17d6446c/version_0
esc-prod-worker-gpu-0-cuda-2.1.9o08kel4o27y@gpu0    | [2022-10-27 00:18:32,058: INFO/ForkPoolWorker-6] Saving to /usr/src/app/media/models/17d6446c/version_0
esc-prod-worker-gpu-0-cuda-2.1.9o08kel4o27y@gpu0    | [2022-10-27 00:19:56,777: INFO/ForkPoolWorker-6] Saving to /usr/src/app/media/models/17d6446c/version_0
esc-prod-worker-gpu-0-cuda-2.1.9o08kel4o27y@gpu0    | [2022-10-27 00:21:22,307: INFO/ForkPoolWorker-6] Saving to /usr/src/app/media/models/17d6446c/version_0
esc-prod-worker-gpu-0-cuda-2.1.9o08kel4o27y@gpu0    | [2022-10-27 00:22:47,080: INFO/ForkPoolWorker-6] Saving to /usr/src/app/media/models/17d6446c/version_0
esc-prod-worker-gpu-0-cuda-2.1.9o08kel4o27y@gpu0    | [2022-10-27 00:24:12,494: INFO/ForkPoolWorker-6] Saving to /usr/src/app/media/models/17d6446c/version_0
```

With very limited data (3 pages of 4-7 lines), I get about 15 times the same epoch then it moves on and repeat again for the next epoch and so on.   
According to @dstoekl it doesn't append from the command line so the API is probably called badly. The relevant escriptorium code is here, can't find an obvious mistake: https://gitlab.com/scripta/escriptorium/-/blob/develop/app/apps/core/tasks.py#L438.

Any ideas?

**Comment by mittagessen** [comment]
On 22/10/27 04:09AM, robin Tissot wrote:
> With very limited data (3 pages of 4-7 lines), I get about 15 times
> the same epoch then it moves on and repeat again for the next epoch
> and so on.   
> According to @dstoekl it doesn't append from the command line so the
> API is probably called badly. The relevant escriptorium code is here,
> can't find an obvious mistake:
> https://gitlab.com/scripta/escriptorium/-/blob/develop/app/apps/core/tasks.py#L438.

My immediate thought would be that the validation frequency is set below
1 epoch which would cause it to try to save slightly different models
with the same epoch number. But that isn't the case in the esc code so
I'm a bit at a loss.

**Comment by dstoekl** [comment]
this issue currently blocks training inside eScriptorium completely on my side.

**Comment by lauxley** [comment]
Changing the `KrakenTrainer` parameter `val_check_interval`to a float seems to have fixed it. Leaving the issue opened in case you want to add a sanity check or force cast it.
