### ISSUE TITLE
How to segment using the binarized image & ocr using the real image

### ISSUE THREAD

**Issue by pgirolami** [mittagessen/kraken#407]
Hi, I've got a case where the segmentation fails to properly include the whole line on the source image but the segmentation works fine on a binarized version. On the other hand, `ocr` works better on the original image than the binarized version.

I've tried finding a way to feed the output of `binarize segment` to `ocr` but I can't figure it out. Is it possible and if so can I get an example ?

**Comment by mittagessen** [comment]
Ah yes, it is fairly easy. First write out the segmentation as an ALTO or PageXML file:

```
kraken -i input.jpg output_seg.xml -a binarize segment -bl
```

and then just feed the XML output file as an input into the OCR:

```
kraken -i output_seg.xml output_ocr.xml -f xml -a ocr -m $model_file
```

Hope that helps.
