### ISSUE TITLE
cuda version installation issue

### ISSUE THREAD

**Issue by dstoekl** [mittagessen/kraken#412]
upon new install I get:
Torch version 1.13.0 has not been tested with coremltools. You may run into unexpected errors. Torch 1.12.1 is the most recent version that has been tested.
And subsequently on training attempt: MisconfigurationException: No supported gpu backend found!

**Comment by mittagessen** [comment]
The warning can safely be ignored because we don't use the pytorch conversion code of coreml.

The error you're getting is most likely caused by a pytorch installation without GPU support (or missing GPU drivers).
