### ISSUE TITLE
install contradiction

### ISSUE THREAD

**Issue by dstoekl** [mittagessen/kraken#413]
mamba env create -f environment_cuda.yml
--> leaves me with numpy 1.19.5 which in turn gives an error "RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd"
my attempts to update numpy failed as pip says : 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
qudida 0.0.4 requires opencv-python-headless>=4.0.1, which is not installed.
albumentations 1.3.0 requires opencv-python-headless>=4.1.1, which is not installed.
kraken 4.2.1.dev84 requires numpy<=1.23.0, but you have numpy 1.24.1 which is incompatible.
coremltools 4.1 requires numpy<1.20,>=1.14.5, but you have numpy 1.24.1 which is incompatible.

**Comment by rohanchn** [comment]
In `4.2.0`, I solved this by specifying the numpy version.

`python -m pip uninstall numpy`
`python -m pip install numpy==1.23.1`

**Comment by mittagessen** [comment]
It's fixed in master now.
