### ISSUE TITLE
use another model

### ISSUE THREAD

**Issue by MohandesaliRahnema** [mittagessen/kraken#42]
iget bellow error when i want to use another model 

my command is:  kraken -i en.png image.txt binarize segment ocr -m toy

Usage: kraken ocr [OPTIONS]

Error: Invalid value: No model found

**Comment by mittagessen** [comment]
Did you install the model through ```kraken get``` first?

**Comment by alirahnema** [comment]
yes i do it .... but i have this error

**Comment by mittagessen** [comment]
toy.clstm should work.

**Comment by bmwmy** [comment]
you could download toy.clstm and put it in the current folder which you run command from and give a try to this also:
kraken -i Pictures/bw.png  image.txt binarize segment ocr -m toy.clstm

**Comment by christophered** [comment]
@MohandesaliRahnema try this, I add .clstm
`kraken -i en.png image.txt binarize segment ocr -m toy.clstm`
