### ISSUE TITLE
Weird polygon shape with shapely>=2.0

### ISSUE THREAD

**Issue by colibrisson** [mittagessen/kraken#430]
When using `lib/segmentation/calculate_polygonal_environment` with shapely>=2.0, some of the polygons have a weird shape:

![Screenshot from 2023-02-07 11-23-26](https://user-images.githubusercontent.com/3318597/217220384-b1ae4b99-3d53-4cce-a7c7-6ae15991ed99.png)

As previously reported in https://github.com/mittagessen/kraken/issues/319, there is also a lot of `side location conflict` exceptions.

Downgrading shapely to 1.7.x solved the issue. Shouldn't shapely be pinned to 1.7?

**Comment by mittagessen** [comment]
Which kraken version are you using? master shouldn't even work with pre-2.0 versions anymore because of all the API changes.

**Comment by colibrisson** [comment]
I'm using master.

**Comment by mittagessen** [comment]
Urrrgh. Can you upload the source image and segmentation somewhere so I can look into it? It's probably something in GEOM, like a change in coordinate order returned by some function or something in that order.

**Comment by colibrisson** [comment]
@mittagessen I just sent you the dataset.

**Comment by mittagessen** [comment]
Can you tell me what exactly you're doing? I don't get any shapely warnings nor do the polygons look weird on current master with shapely 2.0.1 (when repolygonizing with `segmentation_overlay.py`).

**Comment by mittagessen** [comment]
I had a brain fart and the polygons are indeed broken. But I still don't see any of the warnings. From the looks of it, I assume the region of interest construction is broken somehow. Doing it symbolically with a library like GEOM that changes behavior every second release really screws up things...

**Comment by mittagessen** [comment]
I just pinned shapely to 1.8.4 because I wasn't able to figure out why exactly the ROI is wrong with 2.x. I still don't see any of the warnings and it was the last bit needed for a new release so it will have to do for now.

**Comment by bertsky** [comment]
@mittagessen any news on this in 5.0? I can still see Shapely pinned to pre-2...

**Comment by mittagessen** [comment]
On 24/04/08 08:56AM, Robert Sachunsky wrote:
> @mittagessen any news on this in 5.0? I can still see Shapely pinned to pre-2...

It's been low priority for now (and tracking it down is involved) and I
wanted to release the changes that accumulated for the last year first.

**Comment by bertsky** [comment]
Understood.

Note that Shapely 2.0 also makes life somewhat easier with these issues. I started using `set_precision` to tackle invalid paths after rounding. See [here](https://github.com/OCR-D/ocrd_segment/blob/b82b4fd444b97277fb3c693c5dc9c67252c8df2d/ocrd_segment/project.py#L155-L193) for a complete example. I have also spent a lot of time trying to make polygon handling more robust – let me know if you need help.

**Comment by mittagessen** [comment]
On 24/04/09 12:33AM, Robert Sachunsky wrote:
> Note that Shapely 2.0 also makes life somewhat easier with these
> issues. I started using `set_precision` to tackle invalid paths after
> rounding. See
> [here](https://github.com/OCR-D/ocrd_segment/blob/b82b4fd444b97277fb3c693c5dc9c67252c8df2d/ocrd_segment/project.py#L155-L193)
> for a complete example. I have also spent a lot of time trying to make
> polygon handling more robust – let me know if you need help.

Thanks. There's already quite a bit of code to work around corner cases
but the polygonizer runs into quite a few of them so changes in GEOS
library behavior can trigger crashes and vastly different output. As
this bug report shows.

I'll have a look at your code and probably write a couple of tests for
the polygonizer so we can start porting everything onto shapely 2.x.
