### ISSUE TITLE
ShapelyDeprecationWarning fails the processing systematically

### ISSUE THREAD

**Issue by lamaeldo** [mittagessen/kraken#431]
Hello,
I am working with the latest version of Kraken, and each time i try to run one of my files for recognition, it fails at the segmentation stage.
My command is quite basic
`kraken -i 0005.png  out.txt segment -bl ocr -m en_best.mlmodel`
The outcome is always the following: 
Segmenting	WARNING:py.warnings:/usr/local/lib/python3.8/dist-packages/kraken/lib/segmentation.py:354: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if boundaries.type == 'Polygon':
[02/07/23 23:34:21] ERROR    Failed processing

Another example

WARNING:py.warnings:/usr/local/lib/python3.8/dist-packages/kraken/lib/segmentation.py:234: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if l_point.type != 'Point':

Additional information, i'm usually working with fairly large files (50 Mb), but this also happens with smaller crops of them

**Comment by mittagessen** [comment]
It's not the DeprecationWarning that causes it to fail (it does what it says on the tin: note that kraken 4.2.0's use of the shapely API will not work anymore with newer versions of shapely).

Can you run the same command with `--raise-on-error`? Like this:

```
kraken --raise-on-error -i 0005.png ...
```

This should get you the full stack trace of whatever is causing the problem.

**Comment by lamaeldo** [comment]
Makes sense, unfortunately adding  `--raise-on-error` gives no additional information...
![image](https://user-images.githubusercontent.com/105922051/217496503-20cb1627-78d1-4057-aacc-e3cc8fb0e00c.png)

**Comment by lamaeldo** [comment]
Makes sense, this is the trace i get...

![signal-2023-02-08-101102_005](https://user-images.githubusercontent.com/105922051/217500390-6bba835a-462b-4b92-b111-8fafd33f6625.png)
![signal-2023-02-08-101102_004](https://user-images.githubusercontent.com/105922051/217500387-d735ea40-bce2-4a4b-9c2d-428f8b94aa28.png)
![signal-2023-02-08-101102_003](https://user-images.githubusercontent.com/105922051/217500383-cf32eaea-4778-4688-ac93-de2a9f0579fa.png)
![signal-2023-02-08-101102_002](https://user-images.githubusercontent.com/105922051/217500380-3c1cdb27-8f6f-4abf-ab4a-6e865c544134.png)

**Comment by mittagessen** [comment]
Hmm, the deprecation warnings indicate that you're running a shapely version <2.0 but that particular crash is caused by a shapely version >=2.0. I'm in the process of finishing a new release that includes shapely 2.x support but it will take a couple of days. I'd suggest to install from master for now which should resolve this issue.

**Comment by lamaeldo** [comment]
Ok great, thanks for the help!
