### ISSUE TITLE
Path split does not work with split containing `./` and `../`

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#433]
The current code will throw an error if it is used with something like `../image.png`

https://github.com/mittagessen/kraken/blob/911fcac6d5c02a34fcafa413becb327f889c16bf/kraken/lib/functional_im_transforms.py#L94-L95

I'd recommend:
```python
os.path.join(
    os.path.dirname(str(file)),
    os.path.basename(str(x)).split(extsep, 1)[0]
)
```

**Comment by colibrisson** [comment]
Switch to pathlib?

**Comment by mittagessen** [comment]
I was going to move to pathlib anyway. In fact, that's the one file I forgot to move over when fixing up the typing a couple of days ago.

**Comment by PonteIneptique** [comment]
I think, looking at where you use this function, doing `.replace(".gt.txt", ".png")` or the opposite would work at least as well...
