### ISSUE TITLE
Kraken website down

### ISSUE THREAD

**Issue by lamaeldo** [mittagessen/kraken#436]
By the looks of it, [kraken.re](url) is down, returning a 404 on all pages. Is that expected?

**Comment by mittagessen** [comment]
On 23/02/14 08:45AM, lamaeldo wrote:
> By the looks of it, [kraken.re](url) is down, returning a 404 on all pages. Is that expected?

Urrgh, it's a problem when the last commit is also a tag which results
in master (the default release) not being pushed as a gh page. I just
reran the latest non-tag commit actions which should fix it.
