### ISSUE TITLE
ketos train --help not working in v. 4.3.1/2/3

### ISSUE THREAD

**Issue by rohanchn** [mittagessen/kraken#437]
`ketos train --help` and `ketos segtrain --help` is yielding a type error for some reason in v 4.3.1/2/3.

**Comment by mittagessen** [comment]
On 23/02/14 10:05PM, Rohan Chauhan wrote:
> `ketos train --help` and `ketos segtrain --help` is yeilding a type error for some reason in v 4.3.1/2/3.

Thanks. I'll tag a hotfix release.

**Comment by PonteIneptique** [comment]
Just chiming in to say thank you for small, quick bugfix releases: it makes working with Kraken much easier than using master :)
