### ISSUE TITLE
how to use api

### ISSUE THREAD

**Issue by alirahnema** [mittagessen/kraken#45]
hi
do you have an api sample usage?
i tryed to use api in python but libraries was unknown?

**Comment by mittagessen** [comment]
The API is documented on the [web site](http://kraken.re/api.html). For usage examples it is probably easiest to just look at the [kraken.py](https://github.com/mittagessen/kraken/blob/master/kraken/kraken.py) CLI driver. By and large it consists of running ``binarize.nlbin``, ``pageseg.segment``, ``rpred.rpred``, and ``serialization.serialize`` in that order. If you don't need binarization or result serialization drop the first and/or last call respectively.
