### ISSUE TITLE
SUGG: Print Kraken version and List installed Models

### ISSUE THREAD

**Issue by christophered** [mittagessen/kraken#46]
Hi there,
@mittagessen Thank you for all your hard work, your amazing.

This is more of a suggestion than an issue:
1) Ability to print current Kraken version.
2) Ability to list current installed .clstm models and there location.

**Comment by mittagessen** [comment]
For the second one the ``-m`` parameter is just a path. If it isn't found directly it falls back first to the [app dir](http://click.pocoo.org/5/api/#click.get_app_dir) and then ``/usr/local/share/ocropus``. In that sense models aren't really installed but just a bunch of files that could be anywhere on the system.

**Comment by christophered** [comment]
@mittagessen i understand what you are saying, but "kraken get" stores the downloaded models in `~/.config/kraken`
it would be helpful if kraken can list the clstm/pyrnn models that were downloaded.

**Comment by mittagessen** [comment]
I'll keep it in mind as I was planning to rewrite the repository accessor anyway.

``kraken list`` uses the github API to parse the kraken-models repository.
