### ISSUE TITLE
How to segment into word bounding boxes

### ISSUE THREAD

**Issue by SB2020-eye** [mittagessen/kraken#461]
Hello.

Sorry, but despite my efforts, I have been unable to locate any information to help me segment text into word-level bounding boxes.

Could someone please either direct me to documentation of how to do this or else give an example command for doing this?

(Also, can kraken capture the coordinates for every word?)

**Comment by colibrisson** [comment]
The documentation refers to this as the [legacy segmenter](https://kraken.re/master/advanced.html#legacy-box-segmentation).

**Comment by mittagessen** [comment]
The segmenters (both trainable and legacy) work on the line level, the word bounding boxes in final output come from taking the CTC output layer activations from the recognition network. So there is no way to get to words without running recognition which is presumably what you want.
