### ISSUE TITLE
val_codec is not set when resuming training

### ISSUE THREAD

**Issue by notiho** [mittagessen/kraken#467]
When trying to resume training on a model using the `-i` switch, I got an error in train.py line 485 because `self.val_codec` is not set (`AttributeError: 'RecognitionModel' object has no attribute 'val_codec'`). I believe that this could be because some code paths in the `setup` method do indeed not set this member, e.g. when the `try` in line 523 goes through without producing an exception.

**Comment by jacoborrje** [comment]
I just got the same error, also when trying to resume training on a model.

**Comment by mittagessen** [comment]
I must have screwed up the 4.3.x merge. I'll take a look tomorrow.

**Comment by mittagessen** [comment]
It's fixed in master and I tagged a new hotfix release 4.3.7. The crash only happens when continuing training with exact splits, i.e. no difference in alphabets between training runs, which is a fairly uncommon occurrence which is why it didn't show up earlier.
