### ISSUE TITLE
Reorder and Normalize an already extracted .txt

### ISSUE THREAD

**Issue by christophered** [mittagessen/kraken#47]
Hi there,
I am training an .clstm module with 1,050 lines of Arabic Language, and [using the Arabic double-checked training data,](https://github.com/OpenArabic/OCR_GS_Data/tree/master/ara/book_Yacqubi.Tarikh/7_final)
They already extracted the .txt, the problem is that the text within it is in RTL.

How can I **Reorder** the text to LTR, and/or **Normalize** the already extracted .txt files?
Thank you @mittagessen for your hard work
Waiting for your reply

**Comment by mittagessen** [comment]
Weird, I thought I had reordered the text upon extraction back then. The text should already be normalized.

Anyway, here's a short script: [Link](https://gist.github.com/mittagessen/1cefa68d2903b1cd0758574aaa1dd9df). You hand it a directory containing *.txt files and it reorders them to display order writing the output to *.txt.re.

**Comment by christophered** [comment]
I trained the Arabic Data to 96,000 epochs into ~10 Hours, later-on notice the Error rate is 1 and the OUT is blank, Close but no Cigar :sunglasses:

![gene-wilder](https://user-images.githubusercontent.com/16248376/27150732-05c1dd34-5151-11e7-8ab9-0b7968607d01.jpg)

Anyways, in the train.sh clstmocrtrain, when should I change the learning rate or the target height?

**Comment by christophered** [comment]
I assume you based [your train.sh](https://github.com/mittagessen/kraken-vagrant/blob/master/training/train.sh) values on this PHD Thesis?
[`In summary, best parameters for hidden layer size and learning rate are found to be 100 and 0.0001 respectively`](https://kluedo.ub.uni-kl.de/files/4353/PhD_Thesis_Ul-Hasan.pdf) page 55+73

**Comment by mittagessen** [comment]
Nope. I believe they took the value from earlier work by Breuel et al. as he led the research group in the past (and those are the values in ocropy/clstm). I also did hyperparameter optimization using spearmint independently and actually got extremely similar values for both units in the hidden layer and learning rate. Overall, I believe that implementing adaptive gradient descent is probably going to be better than tinkering with the learning rate.

Target height is usually fine as it is; the hyperparameter optimization returned a slightly higher value (IIRC ~60) but the recognition accuracy is mostly unaffected by line height (above a sensible minimum).

**Comment by amitdo** [comment]
>Nope. I believe they took the value from earlier work by Breuel et al. as he led the research group in the past (and those are the values in ocropy/clstm).

Just to make it clear, the line height value in ocropy and clstm is 48.

**Comment by christophered** [comment]
Also, note that [000003.gt.txt](https://github.com/OpenArabic/OCR_GS_Data/blob/master/ara/book_Yacqubi.Tarikh/7_final/000003.gt.txt) is missing one word at the end, you published:
`وانظروا إلى طير السماء لا يزرعن ، و لا يحصدن ، و لا يجمعن في البيوت`

Is missing the last word:
`وانظروا إلى طير السماء لا يزرعن ، و لا يحصدن ، و لا يجمعن في البيوت ، فإن`

**Comment by christophered** [comment]
When the reorder.py script that you posted, I get an error message:
`$ python reorder.py`
```Traceback (most recent call last):
  File "reorder.py", line 8, in <module>
    for f in glob.glob(sys.argv[1] + '/*.txt'):
IndexError: list index out of range```

**Comment by mittagessen** [comment]
You have to run it with an input directory as the first argument.

**Comment by maximromanov** [comment]
@christophered, you can make corrections yourself and submit a pull request so that we incorporate that in our data. We will appreciate this a lot!

**Comment by christophered** [comment]
@maximromanov I will see what I can do, Which errors do you need me to correct?
I will make the corrections on [the z_*.html files ](https://github.com/OpenArabic/OCR_GS_Data/tree/master/ara)

- Inconsistencies: A certain word was given different spelling, example in z_ALL_book_IbnAthir_Kamil_000500.html and z_ALL_book_IbnAthir_Kamil_001000.html
![untitled](https://user-images.githubusercontent.com/16248376/27191244-e4aafeb4-51ff-11e7-8b73-f01a13e912d6.png)


- Segmentation errors: A letter/element was missing due to segmentation
example in z_ALL_book_IbnAthir_Kamil_001000.html
The segmentation removed the "hamza" , making the "أ" look like "ا", the transcription is correct as "أ", but due to the fact that the segmentation removed the Hamza, shouldn't the transcription also remove it?
![untitled2](https://user-images.githubusercontent.com/16248376/27191445-7773b326-5200-11e7-8e88-88fcfd6a8584.png)

- Missing words: Some words are not included in the transcription.
The example states in the post earlier.

- Spelling mistakes

**Comment by christophered** [comment]
@maximromanov Dr. Maxim can you send me an email at crytoy@hotmail.com
I would like to talk with you about a matter regarding your request.
Waiting for your reply

**Comment by christophered** [comment]
@mittagessen  how do I run it with an input directory as the first argument?
example

**Comment by mittagessen** [comment]
$ python reorder.py $gt_dir

**Comment by christophered** [comment]
@mittagessen I have made changes to [z_ALL_book_IbnQutayba_Adab_000500.html](https://github.com/OpenArabic/OCR_GS_Data/blob/master/ara/z_ALL_book_IbnQutayba_Adab_000500.html)
It was saved as corrected.html, along with a folder containing the images.
Since Ketos extract doesn't work on such html, How can I extract the the line/text pairs along with reordering and normalizing?
