### ISSUE TITLE
pytorch-lightning breaks ProgressBarBase import with 2.0.0

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#475]
Current release on pip is broken because of pytorch-lightning-2.0.0

**Comment by mittagessen** [comment]
On 23/03/15 09:50AM, Thibault Clérice wrote:
> Current release on pip is broken because of pytorch-lightning-2.0.0

Yes, I already saw that. I'm working on it.

**Comment by PonteIneptique** [comment]
👍

**Comment by mittagessen** [comment]
Master is 2.0 compatible now.
