### ISSUE TITLE
Error: Too many open files

### ISSUE THREAD

**Issue by christophered** [mittagessen/kraken#48]
I am trying to create a html for transcription of 1050 png images, but an error appears after my command:
`$ ketos transcrib -o output.html *.png`
`Reading images ?`
`Error: Could not open file 001020.png: Too many open files`

So I reducesed the number of images to 1019, the result was:
`$ ketos transcrib -o output.html *.png`
`Reading images	?`
`Writing output	?Error: Could not open file output.html: Too many open files`

So I divided the number of images to half in 2 folders, containing each about +500 png, and it worked and created an output.html.

What was the problem?
Is there a limit of the number of pages or number of .png files ketos transcrib can handel?

**Comment by mittagessen** [comment]
No there's a limit to the number of files you can open concurrently. On most systems that number is 1024 per default. I've added a line that closes unused file descriptors in the latest commit.

It is possible to put that many scanned page images into one transcription environment but I am fairly sure that it isn't a good idea. The HTML files will become huge and browsers aren't particularly memory-efficient.
