### ISSUE TITLE
Augmentation may distort too much

### ISSUE THREAD

**Issue by notiho** [mittagessen/kraken#482]
I just added a few lines to also log images using tensorboard, and I noticed that when using augmentation, sometimes the lines get rotated so much that most content gets lost towards the ends. I assume that this is too much to make sense? I have attached an example. I suspect that this is caused by `ElasticTransform` which also does an affine transformation. 
![皇帝陞壇上香行禮初獻奏時豐之章職事官獻帛爵](https://user-images.githubusercontent.com/5030701/229524744-3ac6a05e-685d-4545-87d6-d18b331018f2.png)

**Comment by bencomp** [comment]
Off-topic: I would like to see how you logged images to Tensorboard. Could you share the code for this?

More on-topic: it looks indeed like this much distortion is too much. I would think that to train a model to recognise text, it should be able to 'see' the text.

**Comment by notiho** [comment]
Sure, I made a pull request #485 in case this is useful for other people

**Comment by mittagessen** [comment]
I'm fairly sure we dialed in the values when we rewrote the augmentation a while ago but there's also a difference in the scale of the rotation between the different datasets as I just saw. What kind of training data are you using? In the line strip format the rotation can be quite high resulting in data like yours but otherwise it is fairly low at max 3 deg.

**Comment by notiho** [comment]
I was using arrow training data, so that should not have been the cause. I am also currently looking into this, I will probably to a PR later

**Comment by mittagessen** [comment]
OK, thanks. I've got a bunch on my plate so not having to track down bugs like this really helps.

**Comment by mittagessen** [comment]
Thanks, it's been merged.

**Comment by colibrisson** [comment]
@notiho I still have a few images that are too distorted:

![image](https://github.com/mittagessen/kraken/assets/3318597/e2ef25a8-a14d-4541-b209-e264e19345ef)

**Comment by notiho** [comment]
You are right, it looks like that for longer lines, a rotation of 3 degrees around the centre as is currently possible is already too much.
