### ISSUE TITLE
Trainable Reading Order

### ISSUE THREAD

**Issue by rohanchn** [mittagessen/kraken#484]
Hi @mittagessen! 

I am checking here for updates on trainable reading order. Has it been implemented? Is there some documentation on this that I can follow?

**Comment by rohanchn** [comment]
Okay, I checked the `reading_order` branch, and think will use that. Closing this for now.

**Comment by mittagessen** [comment]
There were a couple of things interceding the last weeks so I haven't had time to work a lot on it but the training side works (`ketos rotrain`). The new XML parser that extracts the reading order for training needs to be rewritten to work with complex orders though and the inference side is completely missing for now (there's a half-finished decoder in `lib/segmentation.py` but the model management around and all the data pathways to get the RO from segmentation to serialization are missing for now).

**Comment by rohanchn** [comment]
Thanks. I looked at the code but hit a brick wall as the bridge between `segtrain` and `rotrain` wasn't clear.

**Comment by mittagessen** [comment]
The trainable RO should be able to deal with something like your example even in the current state. When I'm talking about complex orders I mean deeply nested ones with unordered and ordered elements, elements on different levels (regions, lines, segments, characters), repeating elements. As long as your order is encoded in the implicit order of elements in the XML the current code should work well.

**Comment by rohanchn** [comment]
It does work well, except in cases I explained above. Plus, few elements I have do repeat. Perhaps, I need to label more examples. I'll report if this doesn't work. Thank you!
