### ISSUE TITLE
two tests in test_train are failing

### ISSUE THREAD

**Issue by notiho** [mittagessen/kraken#487]
When running `pytest` on the current main, two tests in `test_train` are failing.
```
_______________________________________________________________ TestKrakenTrainer.test_krakentrainer_rec_bl_load_add _______________________________________________________________

self = <test_train.TestKrakenTrainer testMethod=test_krakentrainer_rec_bl_load_add>

    def test_krakentrainer_rec_bl_load_add(self):
        training_data = [self.xml]
        evaluation_data = [self.xml]
        module = RecognitionModel(format_type='xml',
                                  model=self.model,
                                  training_data=training_data,
                                  evaluation_data=evaluation_data,
                                  resize='add')
        module.setup()
        self.assertEqual(module.nn.seg_type, 'baselines')
        self.assertIsInstance(module.train_set.dataset, kraken.lib.dataset.PolygonGTDataset)
        trainer = KrakenTrainer(max_steps=1)
>       self.assertEqual(module.nn.named_spec[-1].split("c")[-1], '60')
E       AssertionError: '4' != '60'
E       - 4
E       + 60

tests/test_train.py:128: AssertionError
-------------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------------
INFO     pytorch_lightning.utilities.rank_zero:rank_zero.py:48 GPU available: False, used: False
INFO     pytorch_lightning.utilities.rank_zero:rank_zero.py:48 TPU available: False, using: 0 TPU cores
INFO     pytorch_lightning.utilities.rank_zero:rank_zero.py:48 IPU available: False, using: 0 IPUs
INFO     pytorch_lightning.utilities.rank_zero:rank_zero.py:48 HPU available: False, using: 0 HPUs
______________________________________________________________ TestKrakenTrainer.test_krakentrainer_rec_box_load_add _______________________________________________________________

self = <test_train.TestKrakenTrainer testMethod=test_krakentrainer_rec_box_load_add>

    def test_krakentrainer_rec_box_load_add(self):
        """
        Tests that adaptation works in add mode.
        """
        training_data = self.box_lines
        evaluation_data = self.box_lines
        module = RecognitionModel(format_type='path',
                                  model=self.model,
                                  training_data=training_data,
                                  evaluation_data=evaluation_data,
                                  resize='add')
        module.setup()
        self.assertEqual(module.nn.seg_type, 'bbox')
        self.assertIsInstance(module.train_set.dataset, kraken.lib.dataset.GroundTruthDataset)
        trainer = KrakenTrainer(max_steps=1)
>       self.assertEqual(module.nn.named_spec[-1].split("c")[-1], '19')
E       AssertionError: '4' != '19'
E       - 4
E       + 19

tests/test_train.py:68: AssertionError
```

**Comment by PonteIneptique** [comment]
I am currently PRing for #478, I'll have a look :)

**Comment by PonteIneptique** [comment]
`nn_spec` does not seem to be updated at `fit()` call.

**Comment by PonteIneptique** [comment]
The issues seems to be a real bug, and not a simple spec not re-rewritten. The new codec resulting from `union` (former `add`) was not fed for resizing the output layer.

**Comment by notiho** [comment]
Nice, that fixes that.
For me it now works when testing just `test_train`, however, as soon as I also include merging (`pytest -k "merging or train"`) there are again two cases that fail: `test_krakentrainer_rec_bl_load_new` and `test_krakentrainer_rec_bl_load_union`

**Comment by PonteIneptique** [comment]
Nothing failed for me at the end with all pytest. That's weird

**Comment by notiho** [comment]
Hmm it looks like it should depend on the ordering of the tests, which might be different for you. I think the issue is that in the constructor of `RecognitionModel`, the global `default_specs.RECOGNITION_HYPER_PARAMS` can get updated, thus affecting later tests. For me, changing line 221 there to `hyper_params_ = default_specs.RECOGNITION_HYPER_PARAMS.copy()` fixed it. Could you add that to your PR maybe?

**Comment by PonteIneptique** [comment]
Ok, they do fail when running it this way (must have been doing something wrong)

The test assertion seems wrong.

@mittagessen I see 60 as expected here

https://github.com/PonteIneptique/kraken/blob/ad7685ed59a5bfd6ec4ce699cb328bba63127ebf/tests/test_train.py#L144

`union` and `new` should both have 57, as there are 56 different characters, and `a,b,c` are both in the input model and the training data, resulting with union and new having the same codec.

**Comment by PonteIneptique** [comment]
Done with both remarks, we'll see what @mittagessen says about the PR and this remark.

**Comment by notiho** [comment]
Are you sure that the original values in the tests were incorrect? Because now it is failing again for me.

**Comment by PonteIneptique** [comment]
This time I am pretty sure they pass here. This is weird.
Can you p ovide info about your env?

**Comment by notiho** [comment]
Well I have Ubuntu 22.04 and Python 3.10. For me, the file `170025120000003,0074.xml` appears to indeed have 59 different characters (`[' ', '$', ',', '-', '.', '3', '9', ':', ';', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'M', 'N', 'O', 'P', 'R', 'S', 'V', 'Y', '^', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'x', 'y', 'z', 'á', 'é', 'í', 'ñ', 'ó', 'ô', 'ÿ']`).  What happens when you do ```
from kraken.lib.xml import preparse_xml_data
sorted(list(set(c for l in preparse_xml_data(["170025120000003,0074.xml"]) for c in l["text"])))
```?

**Comment by PonteIneptique** [comment]
Ohh... I am wondering if this is nfd related...

**Comment by PonteIneptique** [comment]
I just forced push an update, as I had the same results as you this morning.
I heavily wonder if it wasn't an artefact of not using copy() before, which resulted in NFD somehow being used (somehow..). Because if you count the accents and remove the other letters, there would be 56...
