### ISSUE TITLE
How do you use the scripts in contrib/

### ISSUE THREAD

**Issue by alix-tz** [mittagessen/kraken#490]
Hello! 

This is a very "naive" question but here it is: I want to use some of the scripts in contrib/ (such extract_lines.py), is there anyway I can do it in the command line after installing kraken's library? If yes, what is the syntax?

Otherwise, should I just create my own python script and copy extract_lines.py?

**Comment by mittagessen** [comment]
They get installed in the package dir but aren't linked as entry points so you'd need to find the path yourself (`.../lib/python3.x/site-packages/kraken/contrib`). Otherwise copying them yourself also works.
