### ISSUE TITLE
[feature request] ketos compile -f xml -o dataset.arrow -b ListOfFiles

### ISSUE THREAD

**Issue by particitae** [mittagessen/kraken#493]
Hi
With a large list of files, it's difficult to use the function "ketos compile -f xml -o dataset.arrow file_1.xml file_2.xml".
Would it possible to add an option, by example compile -b --building-file FILE that contains all the files for a binary dataset (like --training-files, --evaluation-files)

Best regards

**Comment by mittagessen** [comment]
I've just quickly added a `-F/--files` option that does exactly what you want.
