### ISSUE TITLE
Missing time display during `ketos compile`

### ISSUE THREAD

**Issue by stweil** [mittagessen/kraken#504]
`ketos compile` does not show the used and estimated remaining time (like it is done for training and recognition):

```
Extracting lines ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   5% 3224/59851 -:--:-- -:--:--
```

**Comment by stweil** [comment]
I observe a rather smooth progress during the compile process, and the elapsed time does not depend on the variance at all. Therefore I assumed that the progress bar did not get any data from the compile process.

**Comment by colibrisson** [comment]
Same here, progression is very smooth but the progress bar display neither the remaining time nor elapsed time.
