### ISSUE TITLE
Training suggests to use `torch.set_float32_matmul_precision` for better performance

### ISSUE THREAD

**Issue by stweil** [mittagessen/kraken#505]
Training on GPU suggests a code modification to get improved performance:

```
You are using a CUDA device ('NVIDIA RTX A5000') that has Tensor Cores.
To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')`
which will trade-off precision for performance.
For more details, read
https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
```

Related URL:
https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision

**Comment by mittagessen** [comment]
I think we evaluated the performance impact of that setting and didn't see any difference . Could you run a quick test on your hardware and report back if you see any improvement? If yes, I'd enable it but otherwise I'm a bit loath to enable optimizations 'just because'.

**Comment by stweil** [comment]
I also did not see a difference with the default training settings, but still have to evaluate it with `ketos --precision 16`.

**Comment by colibrisson** [comment]
I noticed only minor performance improvement on Ampere GPU both with full
and half-precision. It would be interesting to see if it's also the case on
Ada GPU.

**Comment by PonteIneptique** [comment]
I don't know how you measure performance, but AFAIK, I did see what seems to be a large drop in GPU RAM usage, which allowed for larger batch consistently.

**Comment by colibrisson** [comment]
I was only talking about training speed.

**Comment by PonteIneptique** [comment]
(My apologies if I sounded aggressive, that was definitely not intended)

**Comment by rohanchn** [comment]
I am on Ampere GPU, and can confirm `--precision 16` improves training speed.
