### ISSUE TITLE
crappy segmentation

### ISSUE THREAD

**Issue by particitae** [mittagessen/kraken#507]
Hi
this segmentation is very crapy. Is there some tips to obtain better results ?
![Capture d’écran du 2023-05-25 12-54-46](https://github.com/mittagessen/kraken/assets/37141614/b92398b5-8924-4e54-ad24-990e05694c1f)

Kraken :  version 4.2.1.dev105 (blla.mlmodel)

**Comment by colibrisson** [comment]
Annotate a couple of images from your dataset and use it to fine-tune `blla.mlmodel`.
