### ISSUE TITLE
tags required or not?

### ISSUE THREAD

**Issue by bertsky** [mittagessen/kraken#512]
According to API docs, `tags` should be optional when passing data to the recognizer (both in `lines` and `boxes` format).

However, when I pass baseline data to `rpred`, I get this:
```
  File "/data/ocr-d/kraken/kraken/rpred.py", line 682, in rpred
    return mm_rpred(defaultdict(lambda: network), im, bounds, pad, bidi_reordering)
  File "/data/ocr-d/kraken/kraken/rpred.py", line 467, in __init__
    tags.update(x['tags'].values())
KeyError: 'tags'
```

It's also hard to find out just what exactly should be in there – a `dict`? (I can see that you annotate type/script and parse that from the XML formats, but lacking examples, it's not obvious to me.)

The code seems to require `tags` in various places:
https://github.com/mittagessen/kraken/blob/773cc00cc07df4b44056512a601f7bffba8f2ada/kraken/rpred.py#L467 (here we crashed)
https://github.com/mittagessen/kraken/blob/773cc00cc07df4b44056512a601f7bffba8f2ada/kraken/rpred.py#L580
https://github.com/mittagessen/kraken/blob/773cc00cc07df4b44056512a601f7bffba8f2ada/kraken/rpred.py#L582
https://github.com/mittagessen/kraken/blob/773cc00cc07df4b44056512a601f7bffba8f2ada/kraken/rpred.py#L474

The only robust spot is this:
https://github.com/mittagessen/kraken/blob/773cc00cc07df4b44056512a601f7bffba8f2ada/kraken/rpred.py#L146

But in the bbox case, there's a conversion that adds default tags:
https://github.com/mittagessen/kraken/blob/773cc00cc07df4b44056512a601f7bffba8f2ada/kraken/rpred.py#L679

So why not also add a default in the baseline case?

#318 is related IMO (which has **not** actually been fixed IIUC).

**Comment by mittagessen** [comment]
Yeah, the `tags` field is required for baseline data and contains a dict. Per default the typology of the segmenter is just dumped in there as the value of the `type` key.

I'm in the process of replacing all the random dicts with proper container classes for the merge of the trainable reading order and that's why the docs are a bit out of sync. Sorry for the confusion.

**Comment by bencomp** [comment]
> I'm in the process of replacing all the random dicts with proper container classes for the merge of the trainable reading order and that's why the docs are a bit out of sync. Sorry for the confusion.

That is good news! I had been thinking (when I sometimes explore the code) that having classes instead of dicts could make the code more readable and testable. Nice!
