### ISSUE TITLE
torch version compatibility

### ISSUE THREAD

**Issue by bertsky** [mittagessen/kraken#515]
Currently, there's only a narrow range of versions allowed for Pytorch: https://github.com/mittagessen/kraken/blob/773cc00cc07df4b44056512a601f7bffba8f2ada/setup.cfg#L56

What is the reason for this. Also, is there anything that would speak against 2.x in principle?

(I have tested prediction, for blla and rpred, but not training with 2.0.1 without problems.)

**Comment by mittagessen** [comment]
Lightning only supports 1.10 and above and IIRC there was some changed behavior in torch that precludes compatibility with 1.10 and 1.11+. And at least with the 2.0 torch release I had some weird crashes but if the release has stabilized I don't see any reason not to bump up the maximum version.

In general it will probably always stay in a fairly narrow range as they a) break backwards compatibility quite often and b) a lot of the dependencies are interdependent.

**Comment by stweil** [comment]
Related pull request: #518.
