### ISSUE TITLE
Tensorflow/keras support ?

### ISSUE THREAD

**Issue by fahd09** [mittagessen/kraken#52]
Hi there,

I just found this and I got really interested in such challenging task! I have some experience with RNNs and their implementation in Tensorflow library and I was wondering if Tensorflow models are supported here?  The reason I want to use Tensorflow is the ability to build on other models which may give a huge performance boost of kraken.

**Comment by mittagessen** [comment]
Unfortunately, only original pyrnn models from ocropus and CLSTM models are currently supported. I would like to include tensorflow support in the near future but there are still some obstacles I'd like to find solutions for, most importantly deserialization performance (models always compile for a few minutes and that's quite annoying).
