### ISSUE TITLE
Current Forced Alignement does not work when the model is trained on normalized data and not the transcription

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#521]
Whe using forced alignement on non normalized unicode with a NFKD model, I get:

```
Non-encodable sequence ãrvãn... encountered. Advancing one code point.
Non-encodable sequence ãns p... encountered. Advancing one code point.
Non-encodable sequence ãrvã... encountered. Advancing one code point.
Non-encodable sequence ãruã... encountered. Advancing one code point.
Non-encodable sequence ãrvã... encountered. Advancing one code point.
```

Unicode normalization should just be applied to the input.

**Comment by mittagessen** [comment]
That's somewhat expected as you can't align stuff the model can't predict. Adding a normalization switch to the alignment script is a decent solution though.

**Comment by PonteIneptique** [comment]
Oh, it's totally expected. But as eScriptorium does not offer to normalize the output, I assume it's expected as well to allow such micro-features to be put int ^^
