### ISSUE TITLE
Improve performance for OCR on CPU by avoiding OpenMP multithreading

### ISSUE THREAD

**Issue by stweil** [mittagessen/kraken#528]
The default settings for kraken use multithreading with OpenMP for the segmentation and OCR steps. By default OpenMP uses all available CPU cores. From Tesseract which also uses OpenMP we know that OpenMP's multithreading wastes a lot of CPU time. OCR with kraken on the CPU shows the same behaviour.

Here are some test results from a x86_64 Debian GNU Linux server with 24 cores / 48 threads which was running
`nice time kraken --alto -o .xml --batch-input "*.jpg" segment --model ubma_segmentation.mlmodel --baseline ocr --model desbillons.mlmodel` twice on 72 images:

```
# Times and resources with default settings (using multithreading).
13952.75user 31819.78system 1:44:45elapsed 728%CPU (0avgtext+0avgdata 3836268maxresident)k
64inputs+166344outputs (3major+2367393minor)pagefaults 0swaps

# Times and resources with environment OMP_NUM_THREADS=1 (single threaded).
6381.26user 33.77system 1:46:55elapsed 99%CPU (0avgtext+0avgdata 2979140maxresident)k
0inputs+168448outputs (23major+2723955minor)pagefaults 0swaps
```

With default settings kraken is 2 minutes (2 %) faster than the single threading variant, but wastes 31819 seconds for thread handling. It uses a total of 45772 seconds CPU time instead of 6415 seconds.

So by using more than 700 % of CPU resources we get a gain of only 2 % for the elapsed time. And while the default settings with multithreading use all CPU threads without leaving much room for additional tasks (only exceptions are the single threaded parts of the process like writing the result to disk), the single threaded variant allows running other single threaded kraken processes at the same time, thus allowing optimal usage of the available resources.

**Comment by stweil** [comment]
https://github.com/UB-Mannheim/digitue-gt/wiki documents a mass OCR on the same server where I had started with kraken running on the GPU, then switched to CPU with default settings, then used parallel running single threaded kraken processes. The best total throughput was achieved by using 48 single threaded processes on the 24 CPU cores, each thread running with 99...100 % CPU load.

![kraken process view](https://pbs.twimg.com/media/FbRt0vCWAAkN7Xo?format=png)

![OCR progress over time](https://pbs.twimg.com/media/FbRljzBXoAEFTm5?format=png)

**Comment by mittagessen** [comment]
This is weird because we set the number of OpenMP threads to 1 per default in the ocr subcommand of the CLI driver. I believe that in theory `torch.set_num_threads` should be equal to setting the environment variable but need to verify.

**Comment by colibrisson** [comment]
`torch.set_num_threads` defines the number of threads PyTorch uses but it doesn't affect the other numerical libraries like scikit.

> From Tesseract which also uses OpenMP we know that OpenMP's multithreading wastes a lot of CPU time.

It depends on the system you use. For a 6-core CPU laptop, multithreading is undoubtedly faster. In my opinion, these settings should not be hard coded.

**Comment by stweil** [comment]
Did you test that? My experience with Tesseract and a laptop with 2 cores / 4 threads is different. Did you mean 6 cores (which is unusual for a laptop) or 6 threads? I could run a kraken test on a desktop with 3 cores / 6 threads.

**Comment by mittagessen** [comment]
> In my opinion, these settings should not be hard coded.

They shouldn't be hard coded but should definitely default to single-thread operations. At least pytorch defaulted to all available cores in their OMP thread pool which tends to lock servers with lots of cores.

@stweil I'll see how to integrate threadpoolctl in the CLI drivers. That should handle all possible OMP pools that might hide in any library.

**Comment by stweil** [comment]
> At least pytorch defaulted to all available cores in their OMP thread pool which tends to lock servers with lots of cores.

Yes, that's what I observed on our eScriptorium server. It can run 64 threads and was configured with 8 celery worker threads. But as soon as several people used automated segmentation or transcription, each worker thread started 64 processing threads, resulting in several hundred threads which made everything extremely slow.

Setting OMP_NUM_THREADS for celery fixed that. If it's not already set on the French servers, it might help there, too.

**Comment by mittagessen** [comment]
> If it's not already set on the French servers, it might help there, too.

It was on a server with 192 cores running plain kraken a couple of years ago. No multiprocessing necessary to get everything to freeze up on that kind of hardware.

**Comment by colibrisson** [comment]
> Did you test that? 

Yes, I ran multiple tests with different number of threads: in a single process peak performance is between 5 and 10 threads.

> Did you mean 6 cores (which is unusual for a laptop) or 6 threads? 

I was thinking about the Ryzen5 7640U but it's true for any CPU.

**Comment by stweil** [comment]
Meanwhile I can show results with 6 threads:
```
# Times and resources with environment OMP_NUM_THREADS=6 (6 threads).
7087.45user 3818.91system 1:40:24elapsed 181%CPU (0avgtext+0avgdata 3110032maxresident)k
8inputs+166344outputs (29major+2755740minor)pagefaults 0swaps
```

This is a little bit (but not significantly) faster than 1:44:45 for the default (multithreaded) case and 1:46:55 for the single threaded case and still wastes a lot of resources. It is not a good setting for mass production.

**Comment by colibrisson** [comment]
> This is a little bit (but not significantly) faster

As far as I remember the difference was significant while enabling multithreading for Pytorch by setting `torch.num_threads` to the same value as `OMP_NUM_THREADS`.

> It is not a good setting for mass production.

I totally agree. My point is that single thread is not the best option for a single user running inference in a single process on a consumer-grade CPU.

**Comment by mittagessen** [comment]
I've pushed threadpool control into the CLI drivers in the reading order branch which I'm in the process of merging right now.
