### ISSUE TITLE
Colon in target label for --merge-regions

### ISSUE THREAD

**Issue by rohanchn** [mittagessen/kraken#532]
Hi @mittagessen!

I am working on a segmentation model where I am trying to use `--merge-regions`. I understand that the format for `--merge-regions` is `target:src`. 

But my target labels have a `:` like `MainZone:column#1` (SegmOnto) and I am getting an `Invalid value for '-mr'` error. 

Perhaps you have a suggestion to solve this?

**Comment by rohanchn** [comment]
So, my syntax was wrong as I was using `-mr` multiple times. This actually is not a problem! Closing this now.

**Comment by mittagessen** [comment]
It isn't possible on the command line as the parser of the mapping
doesn't support escaping colons. But you can create arbitrary mappings
when training with the API (or have dummy identifiers in your data and
after training just rename the identifiers in the model metadata).

**Comment by rohanchn** [comment]
I think I will try training with the API. I find the latter slightly tricky. Thank you!
