### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by bertsky** [mittagessen/kraken#537]
You just [dropped](https://github.com/mittagessen/kraken/commit/da04bb9a7f6380ef146b27650622bdc855fe67b6) 3.8 support, which broke when you [required scipy 1.11](https://github.com/mittagessen/kraken/commit/c985d5054006546941f6a969a94a7432a39ef0b1), which in turn [dropped Py38](https://github.com/scipy/scipy/issues/18366) due to Numpy's rather restrictive [version support windows](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table).

Since in OCR-D we rely on Py38 (as it is also the last release for which Nvidia provides Tensorflow 1.x wheels) and had a hard time recently deconflicting dependencies for that version already – is there a hard reason for Kraken to require scipy 1.11 and Python 3.8?

**Comment by mittagessen** [comment]
>  is there a hard reason for Kraken to require scipy 1.11 and Python 3.8?

The thing is that scikit-image doesn't pin their scipy dependencies while at the same time not going out of their way to ensure compatibility. So they're now pinned to versions I know that work. I can go back to pinning scipy 1.10 + scikit-image 0.19.x but we'd be stuck there, as I can't define multiple valid combinations. IIRC 1.10/0.19.x also breaks python 3.11 compatibility.

**Comment by bertsky** [comment]
Understood. Wow, what a(nother) nightmare.

Ok, so _Flucht nach vorne_ is the best solution, I agree. 

Next best alternative would be to maintain multiple branches of Kraken (each with their own pinned scipy/skimage versions) which would obviously be overkill.

So be it, thanks for clarifying!
