### ISSUE TITLE
UnpicklingError when running ketos rotrain

### ISSUE THREAD

**Issue by Svetlana-Yatsyk** [mittagessen/kraken#548]
Hello, first and foremost, thank you for this brunch !

I am trying to run ```ketos rotrain```, but I get UnpicklingError: invalid load key, '<'. Could you please help me understand why it's happening? My ground truth is in PAGE.

python version: 3.9.18
kraken version: 4.3.10.dev108

Here is my [Colab](https://colab.research.google.com/drive/1mAzFlNBIDEslgZl3ZlyB-ILxgjvIM9N6?usp=sharing), if needed.

**Comment by mittagessen** [comment]
On 23/10/17 02:58AM, Svetlana Yatsyk wrote:
> Hello, first and foremost, thank you for this brunch !
> 
> I am trying to run ```ketos rotrain```, but I get UnpicklingError: invalid load key, '<'. Could you please help me understand why it's happening? My ground truth is in PAGE.

You're trying to continue training using one of the XML files as a base
model. Remove the `-i` and it should work. Also you can leave the batch
size at the original value of 15000. The model is really small and so
are its input data so it can be trained with quite substantial batches.

**Comment by Svetlana-Yatsyk** [comment]
It works indeed! Thanks a lot.
