### ISSUE TITLE
[Main branch] `ketos compile` breaks on LXML being unpickable

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#566]
The current multi-worker is broken on mail for `ketos compile`, I had to write a work-around for a script. The error thrown is `lxml.etree.ElementTree is unpickable` at the imap call. The way I dealt with it is to have the parsing inside the pooled function, instead of before...

**Comment by mittagessen** [comment]
Are you sure? It works perfectly fine on my system and I don't see where it would transmit over an `ElementTree` into another process.
