### ISSUE TITLE
serialization / templates: prefer re-use of segment identifiers, if existing (from XML parser)

### ISSUE THREAD

**Issue by bertsky** [mittagessen/kraken#568]
When parsing ALTO or PAGE, you do already keep the identifiers of regions and lines. But the output throws this info away and generates vanilla block/line labels. It would be really useful if the normal behaviour would be idempotent regarding segment identifiers (so for example input and output, or GT and prediction can be easily compared).

**Comment by mittagessen** [comment]
It is an oversight on my part as it even throws away the automatically assigned UUIDs in the new container classes during serialization. I'll fix it but it will take a couple of weeks until I'll get to it.

**Comment by mittagessen** [comment]
5.0 preserves identifiers on the line and region levels now.

**Comment by bertsky** [comment]
Ah, there already _is_ a 5.0 release, just not on Github.
