### ISSUE TITLE
ketos train producing (near) infinite console output in Google Colab

### ISSUE THREAD

**Issue by katharinaost** [mittagessen/kraken#572]
I feel a bit stupid for complaining about such a silly issue, but its effects are super annoying:

The "ketos train" console output indicating training progress works fine in Google Colab until the first validation run starts. Thereafter, every update generates a new line (4-6 lines per second) which causes the memory usage of the web browser to balloon unless the Colab output is cleared manually every so often.

![GF56-5VW4AAPwVL](https://github.com/mittagessen/kraken/assets/86748002/fa01c341-c568-4a2d-b9d8-5e9c9feaede9)

I can't just send the output to /dev/null because I want to be kept informed about the results of the validation runs and the state of the early stopping counter.

The root of this problem may very well lie on the Colab end of things - and maybe ketos already has some kind of quiet mode that I have simply missed?

**Comment by mittagessen** [comment]
It seems that colab terminal doesn't know how to deal with rich's progress bar output after it folded out its weird secondary bar. What you could do is enable verbose mode (`ketos -v`) and redirect that output into a file instead of /dev/null.

I'm somewhat busy for the next two weeks but I can take a look to see what's the actual reason behind the rendering issue at the end of February.

**Comment by katharinaost** [comment]
Thank you for the fast reply! Just redirecting into a file works, even without -v. It doesn't attempt the continual updating, but writes to the file once after the validation step, giving me pretty much exactly what I want:

`stage 0/∞ ━━━━━━━━━━━━━━━━━ 869/869 0:04:23 • 0:00:00 3.44it/s val_accuracy:     early_stopping:    
                                                               0.984             0/10 0.98441       
                                                               val_word_accurac…                    
                                                               0.923                                
stage 1/∞ ━━━━━━━━━━━━━━━━━ 869/869 0:04:27 • 0:00:00 3.26it/s val_accuracy:     early_stopping:    
                                                               0.985             0/10 0.98489       
                                                               val_word_accurac…                    
                                                               0.926                                
`

Then one can check progress by downloading the output file (or, with a Colab subscription, by running tail on it from the terminal).
