### ISSUE TITLE
Bad Credentials

### ISSUE THREAD

**Issue by loranger** [mittagessen/kraken#58]
Hello, I tried to install kraken using pip3 and everything went fine, but I cannot use it.
As soon as I try to get default, I have the following error message 

```shell
$ kraken get default
Retrieving model	⣾Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kraken/kraken.py", line 346, in get
    partial(spin, 'Retrieving model'))
  File "/usr/local/lib/python3.6/site-packages/kraken/repo.py", line 46, in get_model
    raise KrakenRepoException(resp['message'])
kraken.lib.exceptions.KrakenRepoException: Bad credentials
```

I did remove kraken and tried with a pip2 install, but the result remains the same :
```shell
$ kraken get default
Retrieving model	⣾Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kraken/kraken.py", line 346, in get
    partial(spin, 'Retrieving model'))
  File "/usr/local/lib/python2.7/site-packages/kraken/repo.py", line 46, in get_model
    raise KrakenRepoException(resp['message'])
kraken.lib.exceptions.KrakenRepoException: Bad credentials
```

What did I miss ?
(I use a macOS 10.12.6, python 2.7 or 3.6)

**Comment by mittagessen** [comment]
kraken repo uses the github-API to just access the [kraken-models](http://github.com/mittagessen/kraken-models) repository. The API is rate-limited but the error message seems to be unrelated to that (at least according to the documentation). Did you try to do some other API calls before that, causing a lockout? Is the error gone now or have you tried running it from another IP address? 

I apologize for the inconvenience I've been planning to move all the repo stuff to zenodo which should fix most of the github-API related issues.

**Comment by loranger** [comment]
Thanks for your reply.

I haven't used github for the week-end.
Back to work this morning, I've updated my homebrew packages and that's all concerning github.

Now, I've just tried to get kraken defaults, but the error still remains :/

I also try to get my rate limit, and it seems there no issue on my side :

```shell
$ curl https://api.github.com/rate_limit
{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 57,
      "reset": 1500900274
    },
    "search": {
      "limit": 10,
      "remaining": 10,
      "reset": 1500900162
    },
    "graphql": {
      "limit": 0,
      "remaining": 0,
      "reset": 1500903702
    }
  },
  "rate": {
    "limit": 60,
    "remaining": 57,
    "reset": 1500900274
  }
}
```

**Comment by loranger** [comment]
I'm sorry, but as I said, the issue remains…

**Comment by mittagessen** [comment]
Ok, I've opened a github support request as I couldn't reproduce it and the documentation says such an error shouldn't happen for unauthenticated requests. I also don't have a Mac on hand, so I couldn't try that but there isn't an obvious reason why the Mac packages would emit authenticated requests when the Linux ones don't. Let's hope they have an answer, otherwise I'm truly at a loss here.

**Comment by loranger** [comment]
Thank you so much, I really hope I could close this issue soon

**Comment by mittagessen** [comment]
I've also just pushed some more verbose exceptions that also print the HTTP status to master. If you could run that and see if the error message becomes: ``403: Bad credentials`` it would at least confirm that error message and status code actually match.

**Comment by mittagessen** [comment]
They answered and don't know a reason why an unauthenticated request should result in a 401 either. If you could run the ``debug_logging`` branch and paste the output for ``kraken list`` somewhere so we can see what actually goes over the wire that would be swell.

**Comment by loranger** [comment]
Sorry for the delay : I tried to make a clean install in order to make it work, but it failed earlier: I can't [install clstm](https://github.com/tmbdev/clstm/issues/143) anymore.

I'm waiting for an issue answer to decide if I'll carry on or drop this project and stop bothering you.

Sorry for that

**Comment by loranger** [comment]
Thanks for your help on clstm 👍 !

I did get the `debug_logging` branch and installed, but I can't launch kraken. I get a `ModuleNotFoundError: No module named 'httplib'` error.

I tried to `pip install httplib` but it can"t find such a package…

**Comment by mittagessen** [comment]
Please pull again, I fucked up adding the python3 switch in the logger initialization. The shipped http libraries changed names between python2 and 3.

**Comment by loranger** [comment]
No problem, I did pull and install again. 

Here is the ouput of my `kraken list`:

```
kraken list
INFO:kraken.repo:Retrieving head of model repository
send: b'GET /repos/mittagessen/kraken-models/git/refs/heads/master HTTP/1.1\r\nHost: api.github.com\r\nUser-Agent: python-requests/2.18.4\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nAuthorization: Basic bG9yYW5nZXI6MmEzYWM3MjFmZWI0NjlmYjg0YTQ2NzFmNGI1ZjU3MGIyMGRjZTdjNw==\r\n\r\n'
reply: 'HTTP/1.1 401 Unauthorized\r\n'
header: Server header: Date header: Content-Type header: Content-Length header: Status header: X-GitHub-Media-Type header: X-RateLimit-Limit header: X-RateLimit-Remaining header: X-RateLimit-Reset header: Access-Control-Expose-Headers header: Access-Control-Allow-Origin header: Content-Security-Policy header: Strict-Transport-Security header: X-Content-Type-Options header: X-Frame-Options header: X-XSS-Protection header: X-RRetrieving model list-Gi⣾Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kraken/kraken.py", line 334, in list
    model_list = repo.get_listing(partial(spin, 'Retrieving model list'))
  File "/usr/local/lib/python3.6/site-packages/kraken/repo.py", line 126, in get_listing
    raise KrakenRepoException('{}: {}'.format(r.status_code, resp['message']))
kraken.lib.exceptions.KrakenRepoException: 401: Bad credentials
```

**Comment by mittagessen** [comment]
That is indeed an authenticated request. As kraken doesn't add authentication data and urllib3 doesn't know about authentication the reason is somewhere in the requests package. Rummaging through their source I couldn't find an obvious reason why authentication data might magically appear in HTTP requests so I've opened a [ticket](https://github.com/requests/requests/issues/4488). Let's hope they've got an answer.

**Comment by loranger** [comment]
I see…
Can I help you to debug deeper, maybe with outputing the full request or something ?

**Comment by mittagessen** [comment]
This:

```send: b'GET /repos/mittagessen/kraken-models/git/refs/heads/master HTTP/1.1\r\nHost: api.github.com\r\nUser-Agent: python-requests/2.18.4\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nAuthorization: Basic bG9yYW5nZXI6MmEzYWM3MjFmZWI0NjlmYjg0YTQ2NzFmNGI1ZjU3MGIyMGRjZTdjNw==\r\n\r\n'
```
is actually the whole request. Apart from the ``Authorization: ...`` part it also looks exactly like a request produced on my test machines. Something is adding authentication data that shouldn't be there.

It would help if you could run ``python -m requests.help`` and put that output as a comment into the linked issue.

**Comment by loranger** [comment]
I do.
For a reason I can't remember.

I disabled it, and of course everything works flawlessly.
Thanks @drpoggi & @mittagessen for you support !
