### ISSUE TITLE
(Apparent) Inconsistency in the expected version of scikit-learn

### ISSUE THREAD

**Issue by sdevaleriola** [mittagessen/kraken#584]
The https://github.com/mittagessen/kraken/blob/main/setup.cfg files says 
`scikit-learn~=1.2.1`
but when I run ketos train, I get the message 
`scikit-learn version 1.2.1 is not supported. Minimum required version: 0.17. Maximum required version: 1.1.2. Disabling scikit-learn conversion API.`
I am running the kraken v 5.0.0 on Windows, with Python 3.10.7.
Is there anything I'm not doing right?

**Comment by mittagessen** [comment]
That's a coremltools warning that I haven't figured out how to suppress. It concerns functionality we don't use so it can be safely ignored.

**Comment by sdevaleriola** [comment]
thanks for your rapid answer!
