### ISSUE TITLE
[Suggestion] Regarding ketos linegen

### ISSUE THREAD

**Issue by christophered** [mittagessen/kraken#59]
Peace be upon you
1. ketos linegen generates png/txt pairs but at finish, it doesn't generate manifest.txt

- Please allow linegen to auto generate the mainfest.txt, probably by:
`ls *.png > manifest.txt`

~~2. When using ketos linegen for the the Arabic language, the generated text in the txt files are in RTL, thus need to be reordered before using it in training.~~

~~- Please give ketos linegen the option of `--reorder` to reorder the text, instead of manually using [reorder.py](https://gist.github.com/mittagessen/1cefa68d2903b1cd0758574aaa1dd9df)~~

**Comment by amitdo** [comment]
Please give ketos linegen the option of --reorder to reorder the text, instead of manually using reorder.py

It already supports that option:
https://github.com/mittagessen/kraken/blob/0.9.4/kraken/ketos.py#L78

**Comment by christophered** [comment]
Sorry about that, I forgot to see the code :sunglasses: 
@amitdo When I use `ketos linegen` the generated png is noisy, example:
![000005](https://user-images.githubusercontent.com/16248376/28493351-0dea82aa-6f1e-11e7-9be7-13aab49e4acd.png)

Do you know how to generate regular png without the noisy stuff, like this:
![010002 bin](https://user-images.githubusercontent.com/16248376/28493357-293dbec8-6f1e-11e7-97d4-0778cbe2a2d9.png)

**Comment by amitdo** [comment]
try `--disable-degradation`

**Comment by christophered** [comment]
@amitdo Worked thanks,
I see that the options are in the code.
I am currently working on making a fool-proof documentation of kraken, if you have any suggestions, post on #57
