### ISSUE TITLE
Neural network has been trained on mode 1 images (not really an issue)

### ISSUE THREAD

**Issue by johnlockejrr** [mittagessen/kraken#595]
I'm fine-tuning a model with kraken and I get this warning at the beginning:
`[04/24/24 17:56:30] WARNING  Neural network has been trained on mode 1 images, training set contains mode L data. Consider setting 'force_binarization'`

Should I convert my groundtruth images to `mode 1`, `force_binarization` or just ignore?

**Comment by mittagessen** [comment]
On 24/04/24 10:58AM, johnlockejrr wrote:
> I'm fine-tuning a model with kraken and I get this warning at the beginning:
> `[04/24/24 17:56:30] WARNING  Neural network has been trained on mode 1 images, training set contains mode L data. Consider setting `force_binarization``
> 
> Should I convert my groundtruth images to `mode 1`, `force_binarization` or just ignore?

You should probably just ignore it, especially if the model has been
trained with a kraken version <5 which had a bug that caused the 1 byte
per channel mode not to be correctly promoted with multiple dataloader
threads.

If the model *has* indeed been trained on binarized only data the
fine-tuned one will not work well on binary data so depending on the
use-case you might consider binarization your training data. But there
isn't much reason nowadays for binarized-only models and it introduces
an additional processing step (and therefore error source) in the
pipeline.

**Comment by johnlockejrr** [comment]
Perfect! Thank you for clarification, I tested the model, works flawlessly.
