### ISSUE TITLE
set `torch.set_float32_matmul_precision('medium' | 'high')`

### ISSUE THREAD

**Issue by johnlockejrr** [mittagessen/kraken#596]
> You are using a CUDA device ('NVIDIA GeForce RTX 4070') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')`

Should this warning be ignored or there's an option to enable that option?

Using `bf16` precision in ketos would enable this option (`bf16` = `bfloat16` ?)?

**Comment by mittagessen** [comment]
On 24/04/25 11:42PM, johnlockejrr wrote:
> > You are using a CUDA device ('NVIDIA GeForce RTX 4070') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')`
> 
> Should this warning be ignored or there's an option to enable that option?

You can ignore this warning. With our current models it doesn't change
much and with the next generation recognizer where it causes a noticeable
speedup in the medium precision mode it seems to be slightly detrimental
to accuracy.

**Comment by johnlockejrr** [comment]
Perfect! I opt for accuracy instead speedup.
