### ISSUE TITLE
GPU parallelisation?

### ISSUE THREAD

**Issue by alexislitvine** [mittagessen/kraken#602]
@mittagessen - can we turn parallelisation with multiple GPUs on for training with Kraken?

**Comment by mittagessen** [comment]
It isn't supported as such but you could feasibly just use the basic pytorch lightning trainer to have multi-GPU training. On the other hand, it probably isn't worth it as you should be able to get ridiculous batch sizes (>1k) on a most single GPUs already, so unless you're training data sets are in the millions of lines it won't achieve anything.
