### ISSUE TITLE
kraken 5.2.4 on eScriptorium recognition artefacts

### ISSUE THREAD

**Issue by johnlockejrr** [mittagessen/kraken#605]
I'm not sure if is eScriptorium or kraken related, I just want to poin out, same model, same image on different installs:

1. **eScriptorium with kraken 4.3.13 (python 3.8)**

![esc-kraken-4](https://github.com/mittagessen/kraken/assets/16368414/f959e21b-e4d6-405f-ae0f-38ce2a73b8b9)

2. **eScriptorium with kraken 5.2.4 (python 3.10)**

![esc-kraken-5](https://github.com/mittagessen/kraken/assets/16368414/a71927dd-f91c-419a-9cb4-a785bf0e8298)

Both segmentation and recognition models were trained on kraken 5.2.4

**Comment by dstoekl** [comment]
looks like shapely

**Comment by dstoekl** [comment]
the polygon is too big and the recognizer wasn't trained on lines where the letters are only a quarter of the line height.

**Comment by johnlockejrr** [comment]
Here is on kraken 4.x, same model.

<img width="1210" alt="image" src="https://github.com/mittagessen/kraken/assets/16368414/2d4e775c-bc5c-4f5e-85a6-6092bcb6d49a">

**Comment by johnlockejrr** [comment]
The models I used in this test:
https://file.io/p2U9sSF34Rnz

**Comment by mittagessen** [comment]
It isn't a model issue but the polygonization is wrong. I'll have a look. The rotation code changed between 4.x and 5.x so it's either that or other shapely shenanigans.

**Comment by mittagessen** [comment]
Could you also send me the image file and any ALTO/PageXML you've got? It's difficult to debug without being able to run a test case.

**Comment by johnlockejrr** [comment]
[export_doc23_memar_marqah_mcdonald_alto_202405131147.zip](https://github.com/mittagessen/kraken/files/15293884/export_doc23_memar_marqah_mcdonald_alto_202405131147.zip)
Sure, here it is the image with ALTO (from 4.x)

**Comment by mittagessen** [comment]
Thanks. It's mostly so I can make sure the baselines are identical.

**Comment by johnlockejrr** [comment]
Any update on this matter?

**Comment by mittagessen** [comment]
Apparently, the error persists on some other image data.

**Comment by mittagessen** [comment]
Nope, not true after all. Just crappy output of the polygonizer.
