### ISSUE TITLE
problem with old Alto files

### ISSUE THREAD

**Issue by particitae** [mittagessen/kraken#609]
pip list

kraken                    5.2.5

Code 
  ```
  try:
        im= Image.open(Fichier) # load image. It can be any supported image format and mode
    except:
        logging.error( "Kraken Process : Echec du chargement de Image %s" % (Fichier))
    logging.info( "Kraken Process : Traitement pour Image %s" % (Fichier))
    FichierXml = Fichier.replace("jpg","xml")
    try:
        parsed_doc = xml.XMLPage(FichierXml)
    except:
        logging.error( "Kraken Process : Echec de Parsed_doc de PageXML %s" % (FichierXml))
    else:
        segmentation = parsed_doc.to_container()
        try:
            page = serialization.serialize(segmentation, image_size=im.size, template='pagexml')
        except:
            logging.error( "Kraken Process : Echec de la serialisation de PageXML %s" % (FichierXml))
        else:
            logging.info( "Kraken Process : Ecriture de la transcription de PageXML %s" % (FichierXml))
            FichierXml = FichierXml.replace("Alto","PageXml")
            PageXmlDir = os.path.dirname(os.path.abspath(FichierXml))
            if not os.path.isdir(PageXmlDir):
                os.mkdir(PageXmlDir)
            with open(FichierXml, 'w') as fp:
                fp.write(page)
```
the Serialization fails with the old files, does it possible to use old files ?

https://outils.lamop.fr/lamop/download/f183-rxd.xml KO with <softwareVersion>4.3.13</softwareVersion>
https://outils.lamop.fr/lamop/download/f183-alto.xml OK with                 <softwareVersion>5.2.5</softwareVersion>
with https://outils.lamop.fr/lamop/download/f183.jpg

**Comment by mittagessen** [comment]
It's a bug caused by the dummy regions without coordinates pre-5.x versions of kraken would produce. It's easily fixable.

**Comment by mittagessen** [comment]
BTW, for doing simple ALTO to Page conversion a tool like [page-to-alto](https://github.com/kba/page-to-alto) is quite a bit better. The kraken deserializer is not lossless and generally only keeps information potentially required in processing steps.
