### ISSUE TITLE
Ketos Linegen is randomizing the lines by default 

### ISSUE THREAD

**Issue by christophered** [mittagessen/kraken#61]
Peace Be upon you
@mittagessen  When running the command `ketos linegen ...... txtfile.txt`
it doesn't generate the lines according to their order in the txt file, meaning the first line in the .txt file is not   000000.png

**Comment by mittagessen** [comment]
``ketos linegen`` uses a set to filter out duplicate lines from input data. Sets are unordered so this behavior is to be expected. In addition, if `--maxlines`` is smaller than the text corpus lines get sampled from the corpus randomly.
