### ISSUE TITLE
It there a way to simply call kraken recognizer from code? 

### ISSUE THREAD

**Issue by dantetemplar** [mittagessen/kraken#615]
I would like to call kraken recognition from code and get hocr. However, just calling `kraken --hocr -i image.png image.txt binarize segment ocr --reorder` will initialize model on each image recognition. Also it will create file when I need pipe.

Kraken code with click is too tricky for reverse-engineering.

**Comment by mittagessen** [comment]
The [API tutorial](https://kraken.re/main/api.html) explains how to do it. It's fairly straightforward.
