### ISSUE TITLE
bad polygons

### ISSUE THREAD

**Issue by dstoekl** [mittagessen/kraken#619]
standard segmodel creates bad polygons on [standard layout and quality image](https://digi.vatlib.it/iiifimage/MSS_Reg.lat.10/Reg.lat.10_0023_fa_0010r.jp2/full/full/0/default.jpg) and leads to bad reco with [CATMUS recomodel](https://zenodo.org/records/10066219/files/CATMUS%20Medieval%201.0.0.mlmodel?download=1):
![image](https://github.com/mittagessen/kraken/assets/39535215/75764537-de88-4d36-8922-80096f3eabbe)
![image](https://github.com/mittagessen/kraken/assets/39535215/1d4da4d9-4fb9-40bf-87ed-8793e8ee0dba)
![image](https://github.com/mittagessen/kraken/assets/39535215/34063c62-301e-4db6-8c5c-c852d7b69997)
[export_doc73_vatreglat10_alto_202407050953.zip](https://github.com/user-attachments/files/16108220/export_doc73_vatreglat10_alto_202407050953.zip)

**Comment by dstoekl** [comment]
next line polygon is good and so is transcription: 
![image](https://github.com/mittagessen/kraken/assets/39535215/642d7570-29dd-4d9e-a1af-452b21c942e2)

**Comment by alexislitvine** [comment]
@mittagessen @dstoekl - I experience the same problem, too. As discussed in #544 I have been struggling a lot with polygonisation, adding many hours of work tweaking polygons manually. I have tried Transkribu tool for a comparison and theirs seem to be significantly more reliable. Can we do anything - relatively urgently - abou this? It is downgrading the quality of the output and making the production of annotations much more tedious.

**Comment by dstoekl** [comment]
As an immediate solution until a real one,I would suggest to use the API and values based on average line height and line distance.

**Comment by mittagessen** [comment]
On 24/07/11 03:28AM, Alexis Litvine wrote:
> @mittagessen @dstoekl - I experience the same problem, too. As
> discussed in #544 I have been struggling a lot with polygonisation,
> adding many hours of work tweaking polygons manually. I have tried
> Transkribu tool for a comparison and theirs seem to be significantly
> more reliable. Can we do anything - relatively urgently - abou this?
> It is downgrading the quality of the output and making the production
> of annotations much more tedious.

Sorry, I had a deadline today and got run over by a car last week. I'll
have to check out the pull request associated with masking issues and
see if that corrects the issues. Apart from that I can't really offer
any quick fixes, although I'm well aware that there's material where the
current polygonizer fails miserably. The plan is to get rid of
polygonization entirely over the next couple of months though.

**Comment by mabarber92** [comment]
@mittagessen With apologies for the delay (although I appreciate that this was probably not taking priority). Here are some examples of similar masking bugs from OpenITI:

![image](https://github.com/user-attachments/assets/9c435bf5-4487-4c93-90fa-38d81255ff82)

![image](https://github.com/user-attachments/assets/a7b2ab24-d7a8-44d5-b73a-42093d25fd39)

**Comment by alexislitvine** [comment]
@mittagessen - to add to this thread, there was huge downgrading of polygonisation quality with Kraken 5. See below the polygons produced for the same image with K4.3.12 and K5.2.5
![K5](https://github.com/user-attachments/assets/8fabe256-1fb1-4e83-9b68-da021e16d061)
![K4](https://github.com/user-attachments/assets/944169d1-3a5f-40f5-81a5-5eee256c564b)

**Comment by dstoekl** [comment]
at least the baselines are better. but is there any polygon detrimental beyond the single huge one?

**Comment by alexislitvine** [comment]
Oh YES!  all the polygons are completely messy; lines overlap, HTR quality goes down dramatically! K5 is not fit for purpose in this case.
![K4](https://github.com/user-attachments/assets/02f1ef5a-128f-40d0-9ef9-6e8fb9d9e4e0)
![K5](https://github.com/user-attachments/assets/7258c0d6-159c-4918-9375-e9b20f0aea8e)

**Comment by dstoekl** [comment]
are you using the same recognition model, the one trained on the k4 data?
it may make sense to train a new one.

**Comment by alexislitvine** [comment]
In this case I used the default model.
A
________________________________

**Comment by dstoekl** [comment]
recognition, not segmentation. the quality of the recognition depends on the segmentation it is used to. if you retrain or finetune your recognition model on the repolygonized data it may get more robust to more noise from above or below.

**Comment by alexislitvine** [comment]
@dstoekl - actually, the model was trained on k5 data - but still performs MUCH better on k4 polygons.

**Comment by alexislitvine** [comment]
also because of the bad polygonisation, the next line has no text (extremely thin polygon) or just bits of texts in it, and a large share of the data is lost.

**Comment by dstoekl** [comment]
interesting. can you post the whole page with the thin poly in original quality? might help ben to debug if you are using the default segmodel.

**Comment by alexislitvine** [comment]
Just a few examples of some problems I frequently see:

![image](https://github.com/user-attachments/assets/362d87cb-823c-43d6-9dc5-a60d5d61b6c5)
![image](https://github.com/user-attachments/assets/e355c199-aa22-42c3-a019-4f5360f1213b)
![image](https://github.com/user-attachments/assets/f7ab0f49-83ad-4615-8882-54d2f8439428)
![image](https://github.com/user-attachments/assets/7ac8f0ed-ca67-4381-a91e-785836107f81)

**Comment by dstoekl** [comment]
ok. @mittagessen can use them for debugging only if he gets the input before the segmentation process. (and if it is not the default segmodel but another model he also needs that segmodel)

how does the baseline on the last img look like? is it drawn below the actual letters? are these imgs binarized?

**Comment by alexislitvine** [comment]
![test_polygons](https://github.com/user-attachments/assets/b92f143d-cd7f-4af1-bc71-ce133ab04e49)
you can see what line 11 looks like with the default segmenter
![image](https://github.com/user-attachments/assets/644480a3-ebea-4fdd-819b-e6adf2c4c090)

**Comment by alexislitvine** [comment]
these are old photocopies, so yes originally binarised but uploaded as greyscale scans of the copies!

**Comment by dstoekl** [comment]
Tx. This line (18) with a polygon detached from the baseline is even more worrying and potentially of help in debugging: 
![image](https://github.com/user-attachments/assets/46af9973-a9e0-4c61-8e2a-b562f0aab2a4)
Check it out @mittagessen

**Comment by dstoekl** [comment]
19 is also detached in the beginning

**Comment by alexislitvine** [comment]
![image](https://github.com/user-attachments/assets/1e9074aa-aa1e-42e9-8fda-bb7b8b117f05)
![k5](https://github.com/user-attachments/assets/7f9cf3e0-8f3c-4d1b-b807-b63241be1e1d)
![k5-line](https://github.com/user-attachments/assets/2c188fc3-376d-42f2-9214-2c421158f58b)
![k4-line](https://github.com/user-attachments/assets/3e7f3877-66d2-4962-9c7a-3b83136001bb)
Some more examples for you...

**Comment by alexislitvine** [comment]
And the impact on transcription
1. with calculated mask
![image](https://github.com/user-attachments/assets/78a93bcc-5efc-4050-9e8a-128581267417)
2. with manually edited mask (no overlap)
![image](https://github.com/user-attachments/assets/a9a2c2bb-2344-4ea3-b999-9c8cc24aa9ac)

**Comment by katharinaost** [comment]
> Tx. This line (18) with a polygon detached from the baseline is even more worrying and potentially of help in debugging: ![image](https://private-user-images.githubusercontent.com/39535215/351420073-46af9973-a9e0-4c61-8e2a-b562f0aab2a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjI1NzgsIm5iZiI6MTcyMjE2MjI3OCwicGF0aCI6Ii8zOTUzNTIxNS8zNTE0MjAwNzMtNDZhZjk5NzMtYTllMC00YzYxLThlMmEtYjU2MmYwYWFiMmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDEwMjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NjMwNzhmYjQwOTBhN2MxMDM4NWNiYTdhNzc3NmVlYTczMDMxMGU2MDBkYjE0YmViNzAzNTNkOGM3ZDE3MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E9uAxEo1VqNWcT29C14QzNEREGsly0GMFx6pR8MqmNs) Check it out @mittagessen

I'm seeing detached polygons as well:

![image](https://github.com/user-attachments/assets/8881ea7b-06ef-4cc8-a5ce-79b1b599fa2d)

**Comment by dstoekl** [comment]
anybody in this issue: please post the model you used and one or several images with bad polygons with kraken5 and good ones with kraken4 here so we can build some kind of benchmarking system. tx.

**Comment by katharinaost** [comment]
[Link ](https://drive.google.com/file/d/11FK1XhmYrqnZ3H7ZMhgyB12nSBkZfo10/view?usp=sharing) to an example with bad polygons using the eScriptorium default layout model and kraken 5. I don't have a kraken 4 installation at the ready to do comparisons with, but this doesn't seem normal. 

![image](https://github.com/user-attachments/assets/6cc91788-6f85-4b0c-bfa0-3c3ee1e88061)

The bad polygons are surprisingly resistant to changes in the baseline.

**Comment by mittagessen** [comment]
Sorry, for the delay in getting this done. It was the small fix in the PR from July after all but for some reason I thought it was caused by something else. I'll tag a new release in a sec.
