### ISSUE TITLE
Cant use .png with transparency 

### ISSUE THREAD

**Issue by ghost** [mittagessen/kraken#62]
Peace be upon you
Original image:
![untitled-1](https://user-images.githubusercontent.com/16248376/29281535-102ea192-8128-11e7-9457-2351f4d811ab.png)

Using command `ketos transcrib -o output.html Untitled-1.png` the output.html result:
![untitled](https://user-images.githubusercontent.com/16248376/29281591-50359ba6-8128-11e7-8fd0-6cd5b50768a4.png)

**Comment by mittagessen** [comment]
Sorry I looked at this back in August but forgot to get back to this ticket. Unfortunately, there's no way to generically map an transparency channel to get a black and white image and a proper scan shouldn't have one in the first place.
