### ISSUE TITLE
Segment command with separate baseline and region models?

### ISSUE THREAD

**Issue by fattynoparents** [mittagessen/kraken#622]
I have trained two segmentation models separately (with --suppress-regions and --suppress-baselines parameters correspondingly), because it seems to give me more robust results than when I train one model for both purposes.

In eScriptorium it's possible to first segment a bunch of images with one model (f.ex.region), then run the Segment command again with the baseline model.

Is it possible to achive this in kraken? If so, how to use the `kraken segment` command to include both baseline and region models?

If this is not possible, which parameters can be adjusted in ketos segtrain command to improve the training process?

**Comment by fattynoparents** [comment]
If this is not possible, which parameters can be adjusted in `ketos segtrain` command to improve the training process?

**Comment by mittagessen** [comment]
The API already supports it but apparently I forgot to adapt the CLI interface to allow multiple segmentation models. I'll add it later today.

**Comment by fattynoparents** [comment]
Great, thanks a lot!

**Comment by fattynoparents** [comment]
Hi, any news on this?

**Comment by mittagessen** [comment]
Ah yeah, sorry. It works now.

**Comment by fattynoparents** [comment]
Thanks, as of dev version 5.2.9 I can now successfully run segmentation with this command:
```
kraken -d cuda:0 -x -I '/path/to/images/*.jpg' -o '.xml' segment -bl --model /path/to/baseline-only.mlmodel --model /path/to/region-only.mlmodel
```
