### ISSUE TITLE
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### ISSUE THREAD

**Issue by amaury-gau** [mittagessen/kraken#623]
When trying to install from the git repo with `pip install .`  on my MacOS-arm64, python version 3.12,  I got the following error. 

 _AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?_ 

I corrected it by downgrading my python version to 3.10. I also, on my environment.yml deleted the channel conda and changed the conda dependecies : 
- torchvision-cpu>=0.5.0
 - pytorch-cpu~=2.1.0

I don't know if any other information might be helpful for this issue.

**Comment by mittagessen** [comment]
kraken doesn't support python 3.12 and all the packaging tools restrict
it to 3.11 or below.  You should have seen a big fat red warning when
running `pip` as 3.12 is indeed not functional (yet). Anything between
3.9 and 3.11 works fine.
