### ISSUE TITLE
polygonisation for vertical writing systems

### ISSUE THREAD

**Issue by dstoekl** [mittagessen/kraken#625]
this was better in the past I believe. 
Lines were manually drawn and then subsequently drawn by kraken in eScr.
![image](https://github.com/user-attachments/assets/21f38123-148d-49a9-8339-2c122e08811b)

https://msia.escriptorium.fr/media/users/2/export_doc4710_trial_07_24_alto_202407181035.zip

**Comment by colibrisson** [comment]
Are you using center-line or baseline?

**Comment by dstoekl** [comment]
center-line !

**Comment by dstoekl** [comment]
Here is another very bad polygonisation: 
data: ![image](https://github.com/user-attachments/assets/139e60d3-7f23-4388-bca4-da3e19e589c4)
model: https://msia.escriptorium.fr/media/models/187ba3fc/jap_seg_no_aug_1.mlmodel

https://msia.escriptorium.fr/media/users/2/export_doc4710_trial_07_24_alto_202407190838.zip

**Comment by colibrisson** [comment]
I always get weird polygons with center-line. I have tried to fix this issue multiple times. 

It is odd thought because at the end center-line option don't do much: it only impact the offset of the baseline.

**Comment by dstoekl** [comment]
do the polygons always look as if the wind blows from the West (left)?

**Comment by colibrisson** [comment]
I think so.

**Comment by dstoekl** [comment]
west storm:
![image](https://github.com/user-attachments/assets/d65d8f7b-93ee-4ee2-b382-f9fffa8228c3)

**Comment by mittagessen** [comment]
The general fix for the polygonisation seems to address this as well.
