### ISSUE TITLE
No such option: --device , -d (how to switch between gpu and cpu computing?)

### ISSUE THREAD

**Issue by TutajITeraz** [mittagessen/kraken#629]
Hello!
I need to switch between gpu and cpu computing, so I read the Usage options (by typing kraken without parameters) and I saw this description:
```
  -d, --device TEXT               Select device to use (cpu, cuda:0, cuda:1,
                                  ...)  [default: cpu]
```

I have tried both -d and --device:

```
$ kraken -i results/8v_mod.jpg results/8v_mod.txt binarize segment -bl ocr -m cremma-generic-1.0.1.mlmodel -d gpu
Error: Invalid value for '-d' / '--text-direction': 'gpu' is not one of 'horizontal-tb', 'vertical-lr', 'vertical-rl'.
```

```
kraken -i results/8v_mod.jpg results/8v_mod.txt binarize segment -bl ocr -m cremma-generic-1.0.1.mlmodel --device cpu
Error: No such option: --device
```

How can i switch between this two?  Is help manual wrong?

Im using 
kraken==5.2.7 installed from pip
on 
Manjaro Linux. (Linux 5.15.160-1-MANJARO)

**Comment by PonteIneptique** [comment]
Hi tutajl. --device must come before the first processing command and the
kraken call, so here before binarize.
Note that binarization is useless nowadays and will break bl and htr i
believe

**Comment by TutajITeraz** [comment]
Thank you @PonteIneptique !
