### ISSUE TITLE
ketos transcrib Issue

### ISSUE THREAD

**Issue by agatho-daemon** [mittagessen/kraken#63]
Using `ketos transcrib` with a two column text doesn't give the desired result. Maybe a column recognition such as that in `segment` would help. It seems like there is an empty space threshold to separate text boxes into two columns as I have noticed.

**Comment by mittagessen** [comment]
``ketos transcrib`` uses the layout analysis of the segment subcommand and has the same ``maxcolseps`` parameter. You might try to set it to a fixed value of 1 but if the inter-column margins are small or there are lots of marginalia the detection will nevertheless fail. I'm working on a better solution for both line extraction and reading order determination but it will take a few more weeks/month.
