### ISSUE TITLE
access to kraken.re !

### ISSUE THREAD

**Issue by agnagay** [mittagessen/kraken#631]
Hi,
I can't reach the kraken.re docs web page. is it me ? or the url is broken ?

Thank you.

**Comment by dstoekl** [comment]
index seems broken (404) but here you can get to it: https://kraken.re/4.0/index.html

**Comment by dstoekl** [comment]
so the most recent is https://kraken.re/5.2/index.html

**Comment by mittagessen** [comment]
The tests broke just after the last tagged release so the default branch website wasn't pushed. It should work now.
