### ISSUE TITLE
Ketos Train Fails with PNG + TXT Input

### ISSUE THREAD

**Issue by jesusbft** [mittagessen/kraken#639]
I'm attempting to train a simple model for testing purposes, using a single PNG image (teste.png) containing the letter "O", paired with a corresponding TXT file (teste.txt) that contains the ground truth letter "O".

This is just a small-scale test before expanding the dataset to thousands of files. However, I’m encountering a recurring issue where Kraken/Ketos is unable to detect the ground truth text, and I consistently get the following error:

`KrakenInputException: No text for ground truth line teste.png.`

File Details:

`-rw-r--r-- 1 jesus jesus  802 Sep 15 21:38 teste.png
-rw-r--r-- 1 jesus jesus    2 Sep 15 21:39 teste.txt`

The content of the TXT file is simply:

`O`

Command Attempted:

`ketos -vvv train teste.png -f path`

I’ve also tried using various arguments and commands such as ketos compile, ketos pretrain, and ketos segtrain, but nothing seems to resolve the issue. Here are the results and error messages I’ve encountered.

Is there a specific configuration or approach I’m missing here? Any help or guidance would be appreciated!

**Comment by jesusbft** [comment]
The whole error:

jesus@DESKTOP-L6R8GTM:~/BRESSAY$ ketos -vvv train teste.png -f path
[09/15/24 22:43:29] INFO     Got 1 line strip images for training data                                                        train.py:303
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/jesus/.local/bin/ketos:8 in <module>                                                       │
│                                                                                                  │
│   5 from kraken.ketos import cli                                                                 │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(cli())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/click/core.py:1157 in __call__                   │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/click/core.py:1078 in main                       │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/click/core.py:1688 in invoke                     │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/click/core.py:1434 in invoke                     │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/click/core.py:783 in invoke                      │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/click/decorators.py:33 in new_func               │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/kraken/ketos/recognition.py:287 in train         │
│                                                                                                  │
│   284 │   else:                                                                                  │
│   285 │   │   val_check_interval = {'val_check_interval': hyper_params['freq']}                  │
│   286 │                                                                                          │
│ ❱ 287 │   model = RecognitionModel(hyper_params=hyper_params,                                    │
│   288 │   │   │   │   │   │   │    output=output,                                                │
│   289 │   │   │   │   │   │   │    spec=spec,                                                    │
│   290 │   │   │   │   │   │   │    append=append,                                                │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/kraken/lib/train.py:304 in __init__              │
│                                                                                                  │
│    301 │   │   │   │   logger.warning('Internal binary dataset splits are enabled but using non  │
│    302 │   │   │   │   binary_dataset_split = False                                              │
│    303 │   │   │   logger.info(f'Got {len(training_data)} line strip images for training data')  │
│ ❱  304 │   │   │   training_data = [{'line': parse_gt_path(im)} for im in training_data]         │
│    305 │   │   │   if evaluation_data:                                                           │
│    306 │   │   │   │   logger.info(f'Got {len(evaluation_data)} line strip images for validatio  │
│    307 │   │   │   │   evaluation_data = [{'line': parse_gt_path(im)} for im in evaluation_data  │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/kraken/lib/train.py:304 in <listcomp>            │
│                                                                                                  │
│    301 │   │   │   │   logger.warning('Internal binary dataset splits are enabled but using non  │
│    302 │   │   │   │   binary_dataset_split = False                                              │
│    303 │   │   │   logger.info(f'Got {len(training_data)} line strip images for training data')  │
│ ❱  304 │   │   │   training_data = [{'line': parse_gt_path(im)} for im in training_data]         │
│    305 │   │   │   if evaluation_data:                                                           │
│    306 │   │   │   │   logger.info(f'Got {len(evaluation_data)} line strip images for validatio  │
│    307 │   │   │   │   evaluation_data = [{'line': parse_gt_path(im)} for im in evaluation_data  │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/kraken/lib/util.py:139 in parse_gt_path          │
│                                                                                                  │
│   136 │   │   │   raise KrakenInputException(f'No text file found for ground truth line {path}   │
│   137 │                                                                                          │
│   138 │   if not gt and skip_empty_lines:                                                        │
│ ❱ 139 │   │   raise KrakenInputException(f'No text for ground truth line {path}.')               │
│   140 │                                                                                          │
│   141 │   return BBoxLine(id=uuid.uuid4(),                                                       │
│   142 │   │   │   │   │   bbox=((0, 0), (w, 0), (w, h), (0, h)),                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KrakenInputException: No text for ground truth line teste.png.

**Comment by jesusbft** [comment]
def parse_gt_path(path: Union[str, 'PathLike'],
                  suffix: str = '.gt.txt',
                  split: Callable[[Union['PathLike', str]], str] = F_t.default_split,
                  skip_empty_lines: bool = True,
                  base_dir: Optional[Literal['L', 'R']] = None,
                  text_direction: Literal['horizontal-lr', 'horizontal-rl', 'vertical-lr', 'vertical-rl'] = 'horizontal-lr') -> BBoxLine:
                  
Kraken expected a text with suffix .gt.txt and not .txt, like I did.


Now I have a different error. working in it:

`╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/jesus/.local/bin/ketos:8 in <module>                                                       │
│                                                                                                  │
│   5 from kraken.ketos import cli                                                                 │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(cli())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/click/core.py:1157 in __call__                   │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/click/core.py:1078 in main                       │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/click/core.py:1688 in invoke                     │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/click/core.py:1434 in invoke                     │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/click/core.py:783 in invoke                      │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/click/decorators.py:33 in new_func               │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/kraken/ketos/recognition.py:287 in train         │
│                                                                                                  │
│   284 │   else:                                                                                  │
│   285 │   │   val_check_interval = {'val_check_interval': hyper_params['freq']}                  │
│   286 │                                                                                          │
│ ❱ 287 │   model = RecognitionModel(hyper_params=hyper_params,                                    │
│   288 │   │   │   │   │   │   │    output=output,                                                │
│   289 │   │   │   │   │   │   │    spec=spec,                                                    │
│   290 │   │   │   │   │   │   │    append=append,                                                │
│                                                                                                  │
│ /home/jesus/.local/lib/python3.10/site-packages/kraken/lib/train.py:407 in __init__              │
│                                                                                                  │
│    404 │   │   │   self.train_set, self.val_set = random_split(train_set, (train_len, val_len))  │
│    405 │   │                                                                                     │
│    406 │   │   if len(self.train_set) == 0 or len(self.val_set) == 0:                            │
│ ❱  407 │   │   │   raise ValueError('No valid training data was provided to the train '          │
│    408 │   │   │   │   │   │   │    'command. Please add valid XML, line, or binary data.')      │
│    409 │   │                                                                                     │
│    410 │   │   if format_type == 'binary':                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: No valid training data was provided to the train command. Please add valid XML, line, or binary data.`

**Comment by mittagessen** [comment]
You need at least two lines, one for training, one for validation. May I
ask why you're using the box format? The baseline segmenter is much more
capable (plus trainable) and everything related to the old line strip
data model is kinda legacy.

**Comment by jesusbft** [comment]
> You need at least two lines, one for training, one for validation. May I ask why you're using the box format? The baseline segmenter is much more capable (plus trainable) and everything related to the old line strip data model is kinda legacy.

Sure. I have a dataset separate in words, lines, paragraphs and pages. My plan for now is run the data for words, and increase it latter to lines, paragraphs and pages.

For specific words, I think don't make sense train in baseline instead box format. Let me know if I'm wrong or have better approuch here.

By the way, I tested before with a single file for try understand what's happening. I running with a bigger database now.

**Comment by mittagessen** [comment]
On 24/09/16 08:08AM, Weslley Oliveira wrote:
> Sure. I have a dataset separate in words, lines, paragraphs and pages.
> My plan for now is run the data for words, and increase it latter to
> lines, paragraphs and pages.

Hm, if everything is already segmented then it doesn't make any
difference.

> For specific words, I think don't make sense train in baseline instead
> box format. Let me know if I'm wrong or have better approuch here.

Don't run on single words. The recognizer performs better with more
context so just feed in whole lines.

**Comment by jesusbft** [comment]
> On 24/09/16 08:08AM, Weslley Oliveira wrote: Sure. I have a dataset separate in words, lines, paragraphs and pages. My plan for now is run the data for words, and increase it latter to lines, paragraphs and pages.
> Hm, if everything is already segmented then it doesn't make any difference.
> For specific words, I think don't make sense train in baseline instead box format. Let me know if I'm wrong or have better approuch here.
> Don't run on single words. The recognizer performs better with more context so just feed in whole lines.

Ok, Thank you for let me know, I'll try it!
