### ISSUE TITLE
Faulty line segmentation

### ISSUE THREAD

**Issue by andbue** [mittagessen/kraken#65]
Hi mittagessen,

I have a tiny little problem with kraken-pageseg: in some cases (eg. the first two lines of the attached paragraph image), it reverses the order of lines for no obvious reason. Maybe it's because of left_of (and not right_of) in pageseg.reading_order?
My first try was to switch of column detection by setting maxcolseps=0, but this doesn't change anything. I made some additions to switch of columns and reordering if maxcolseps=0 in https://github.com/andbue/kraken/commit/69c8009a722c78dfcf6c4b890feb5e8b0a7170b0. This fixes the issue for me, my pages are pre-segmented using LAREX anyway, but that doesn't solve the general problem here.

Cheers,
Andreas

![0121_004_paragraph](https://user-images.githubusercontent.com/4848677/31338859-2bd2c2c0-ad01-11e7-9164-0b48996461cc.png)

**Comment by mittagessen** [comment]
Thanks, that is an obvious bug. I'll add 'horizontal-rtl/-ltr' values to the text direction field switching horizontal line ordering from ltr to rtl. It might be advantageous to disable the horizontal ordering in ``reading_order()`` for single-column inputs but I'll have to see if there are any edge cases where it is still necessary.
