### ISSUE TITLE
Is there a published trained recognition model I can use for Japanese documents?

### ISSUE THREAD

**Issue by BingWangEd** [mittagessen/kraken#652]
The default model is for english and I have checked the list of available models, but I don't think I found anything for recognition of Japanese documents? Do I have to train my model? Thanks

**Comment by mittagessen** [comment]
On 24/10/15 06:30PM, Bing Wang wrote:
> The default model is for english and I have checked the list of
> available models, but I don't think I found anything for recognition
> of Japanese documents? Do I have to train my model? Thanks

Unfortunately not. We've got a dataset of traditional Chinese that I can
quickly train a model on and which can serve as a base for finetuning
but nothing for Japanese directly. It would obviously not know at all
about the syllabaries so you'd need to teach it that from scratch.

**Comment by dstoekl** [comment]
well we do have a model trained on kuzushiji if that is what you need. about 96% accuracy if I remember correctly.

**Comment by mittagessen** [comment]
I forgot that the models for Chinese are already publicly available. You
can find them here [0]. Maybe they'll be helpful.

[0] https://github.com/colibrisson/CHAT_models
