### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by whanley** [mittagessen/kraken#66]
I haven't used VirtualBox before, and may be making some basic error, but I keep stumbling at the same spot. I followed the installation guide, got everything running and ran kraken on some images successfully. Then I started getting an API rate limit exceeded error. The only way I could get around it was to uninstall and reinstall. Then things would be fine for a while, then the error would return.

<img width="805" alt="screen shot 2017-10-22 at 8 51 47 am" src="https://user-images.githubusercontent.com/7728326/31862108-c36de416-b706-11e7-8b01-9318cb2d2c9d.png">

I realize the problem is likely on my end, but I'd be grateful for advice. I'm on OSX.

**Comment by mittagessen** [comment]
It isn't an error on your end, the model repository is just a github repository and the ``kraken show/get/list`` commands use the github API which is rate-limited to fetch information. You can clone [kraken-models](https://github.com/mittagessen/kraken-models) to just download everything. Sorry for the inconvenience, the models are going to move to Zenodo reasonably soon whose API is less restrictively rate-limited.

**Comment by whanley** [comment]
Thanks. How do I point the vagrant machine to the models I've downloaded?

**Comment by kba** [comment]
kraken looks for models using [click.get_app_dir](http://click.pocoo.org/5/api/#click.get_app_dir). In OSX this will be `$HOME/Library/Application Support/kraken`, in Linux it's `$HOME/.config/kraken`.
