### ISSUE TITLE
Error using --spec and --append with exist model

### ISSUE THREAD

**Issue by jesusbft** [mittagessen/kraken#663]
I encountered an issue while attempting to train a model in Kraken using the -i and -a options to load an existing model and append a new VGSL spec.

My code:

`ketos train --augment --workers 12 --threads 6 --batch-size 32 -d cuda:0 --precision 16 --epochs 300 --quit fixed -u NFD --normalize-whitespace --log-dir models/ -a 0 -s '[1,120,0,1 Cr{C_0}3,13,32 Do{Do_1}0.1,2 Mp{Mp_2}2,2 Cr{C_3}3,13,32 Do{Do_4}0.1,2 Mp{Mp_5}2,2 Cr{C_6}3,9,64 Do{Do_7}0.1,2 Mp{Mp_8}2,2 Cr{C_9}3,9,64 Do{Do_10}0.1,2 S{S_11}1(1x0)1,3 Lbx{L_12}400 Do{Do_13}0.1,2 Lbx{L_14}400 Do{Do_15}0.1,2 Lbx{L_16}400 Do{Do_17} O{O_18}1c131]' -i /home/jesus/.config/kraken/McCATMuS_nfd_nofix_V1.mlmodel --resize add -o models/brasil.mlmodel -f binary cajaseiras.arrow`

The exist model McCATMuS_nfd_nofix_V1.mlmodel have the LSTM Layers Lbx200, but I want to test my models with Lbx300 and Lbx400.

However, when I try specify my spec (-s 'VGSL') and use the option append (-a 0), the kraken still using the original spec with Lbx200.

If I use different number than 0, like "-a 2", I have the follow error:

`TypeError: TorchVGSLModel.build_ro() got an unexpected keyword argument 'target_output_shape'`

Any ideia that what I doing wrong here?

**Comment by mittagessen** [comment]
On 24/11/27 12:26AM, Weslley Oliveira wrote:
> I encountered an issue while attempting to train a model in Kraken using the -i and -a options to load an existing model and append a new VGSL spec.
> 
> My code:
> 
> `ketos train --augment --workers 12 --threads 6 --batch-size 32 -d cuda:0 --precision 16 --epochs 300 --quit fixed -u NFD --normalize-whitespace --log-dir models/ -a 0 -s '[1,120,0,1 Cr{C_0}3,13,32 Do{Do_1}0.1,2 Mp{Mp_2}2,2 Cr{C_3}3,13,32 Do{Do_4}0.1,2 Mp{Mp_5}2,2 Cr{C_6}3,9,64 Do{Do_7}0.1,2 Mp{Mp_8}2,2 Cr{C_9}3,9,64 Do{Do_10}0.1,2 S{S_11}1(1x0)1,3 Lbx{L_12}400 Do{Do_13}0.1,2 Lbx{L_14}400 Do{Do_15}0.1,2 Lbx{L_16}400 Do{Do_17} O{O_18}1c131]' -i /home/jesus/.config/kraken/McCATMuS_nfd_nofix_V1.mlmodel --resize add -o models/brasil.mlmodel -f binary cajaseiras.arrow`
> 
> The exist model McCATMuS_nfd_nofix_V1.mlmodel have the LSTM Layers Lbx200, but I want to test my models with Lbx300 and Lbx400.
> 
> However, when I try specify my spec (-s 'VGSL') and use the option append (-a 0), the kraken still using the original spec with Lbx200.

Why do you append the whole network spec at position 0 to an existing
network? I've never tried it so no idea if it is going to work (append
mode is very rarely used in general) but it should be the equivalent of
training from scratch.

You can't really resize an internal layer. What you can do is insert
only the LSTM layers after the convolutional block:

```
ketos train -s 'Lbx{L_12}400 Do{Do_13}0.1,2 Lbx{L_14}400 Do{Do_15}0.1,2 Lbx{L_16}400 Do{Do_17} O{O_18}1c131]' -a 12 ....
```

should work.

> `TypeError: TorchVGSLModel.build_ro() got an unexpected keyword argument 'target_output_shape'`

That's a bug I need to track down. But I'm going to be extremely busy
the next two weeks, so I can't promise a timely resolution.

**Comment by jesusbft** [comment]
> Why do you append the whole network spec at position 0 to an existing network? I've never tried it so no idea if it is going to work (append mode is very rarely used in general) but it should be the equivalent of training from scratch. You can't really resize an internal layer. What you can do is insert only the LSTM layers after the convolutional block: ``` ketos train -s 'Lbx{L_12}400 Do{Do_13}0.1,2 Lbx{L_14}400 Do{Do_15}0.1,2 Lbx{L_16}400 Do{Do_17} O{O_18}1c131]' -a 12 .... ``` should work.

Got it!

I think I didn't understand hot to use this argument, I'll try and I'll come back here as soon as I can.

> `TypeError: TorchVGSLModel.build_ro() got an unexpected keyword argument 'target_output_shape'`
> That's a bug I need to track down. But I'm going to be extremely busy the next two weeks, so I can't promise a timely resolution.

Probaly the error message is because I duplicate the whole thing.

**Comment by jesusbft** [comment]
Yes, worked great:

```
 INFO     Appending [Lbx{L_12}400 Do{Do_13}0.1,2 Lbx{L_14}400 Do{Do_15}0.1,2 Lbx{L_16}400 Do{Do_17} O{O_18}1c131 O1c90] to existing model [1,120,0,1 Cr{C_0}3,13,32 Do{Do_1}0.1,2  train.py:553
                             Mp{Mp_2}2,2 Cr{C_3}3,13,32 Do{Do_4}0.1,2 Mp{Mp_5}2,2 Cr{C_6}3,9,64 Do{Do_7}0.1,2 Mp{Mp_8}2,2 Cr{C_9}3,9,64 Do{Do_10}0.1,2 S{S_11}1(1x0)1,3 Lbx{L_12}200 Do{Do_13}0.1,2
                             Lbx{L_14}200 Do{Do_15}0.1,2 Lbx{L_16}200 Do{Do_17} O{O_18}1c117] after 12
                    INFO     Assembled model spec: [1,120,0,1 Cr{C_0}3,13,32 Do{Do_1}0.1,2 Mp{Mp_2}2,2 Cr{C_3}3,13,32 Do{Do_4}0.1,2 Mp{Mp_5}2,2 Cr{C_6}3,9,64 Do{Do_7}0.1,2 Mp{Mp_8}2,2 Cr{C_9}3,9,64 train.py:556
                             Do{Do_10}0.1,2 S{S_11}1(1x0)1,3 Lbx{L_12}400 Do{Do_13}0.1,2 Lbx{L_14}400 Do{Do_15}0.1,2 Lbx{L_16}400 Do{Do_17} O{O_18}1c131 O{O_19}1c90]
```
                             
One tip, the spec have to start with brackets, like:
`ketos train -s '[Lbx{L_12}400 Do{Do_13}0.1,2 Lbx{L_14}400 Do{Do_15}0.1,2 Lbx{L_16}400 Do{Do_17} O{O_18}1c131]' -a 12`
