### ISSUE TITLE
Regarding the clstm bindings commit

### ISSUE THREAD

**Issue by christophered** [mittagessen/kraken#68]
Hi there,
I have noticed that you have added the clstm bindings commit, does that mean if I want to train a new model I can use "ketos train" ? or that it automatically install clstm along with "clstmocrtrain" ?
Because I just installed kraken using pip, but when running "clstmocrtrain" to train a new model, it says the command not recognized....
Should I build clstm from source then install kraken from pip?
Waiting for your reply
@mittagessen

**Comment by mittagessen** [comment]
The clstm bindings package contains only the bindings, not the clstmocrtrain binary, as it is impossible to install non-python executables in a generic path using pip/setuptools. It is only a stopgap so people don't have to compile ancient library versions with syntax incompatible with new compilers until we can switch everything over to pytorch (old models will remain usable) which will happen as soon as getting CTC loss in there is less of a harrowing compilation experience. Training with ``ketos`` directly will work as soon as that is finished.

**Comment by amitdo** [comment]
https://github.com/tmbdev/cctc

Is it usable right now?

**Comment by mittagessen** [comment]
I'm working on porting that implementation/clstm ctc directly into the pytorch THNN library to get it merged into mainline. I've resolved most of the C++ indirection but it still lacks the actual loss and gradient calculation. If I'm not entirely mistaken it should be fairly easy to add these but I'll have to read through the Graves paper again to be sure.
