### ISSUE TITLE
Processing empty run. Skipping.

### ISSUE THREAD

**Issue by iShinJini** [mittagessen/kraken#74]
![image](https://user-images.githubusercontent.com/37577105/39354619-83584f86-4a3d-11e8-9d82-c97fd93252b0.png)

I train my own model and test out the result and notice this empty run. Anyone came across this ?
While i was training the model, ALN and OUT matched perfectly but when i test out the result it like 0% accuracy.

Thanks

**Comment by mittagessen** [comment]
The segmentation contains an empty line, i.e. the script detection classified an empty part of the input as a particular script. I see that you're only using a single model, adding the ``-n`` switch to segment disables the script detection. If there is only a single line in your image it is best to create a json segmentation file containing a single line with the size of your image.

**Comment by iShinJini** [comment]
Thank you @mittagessen !
i will try again and my version is 9.16

**Comment by christophered** [comment]
@iShinJini please upgrade kraken to the latest version using source code, not pip. also have a look at  [issue 82](https://github.com/mittagessen/kraken/issues/82) explaining how to build kraken from source.
@iShinJini please close the topic

**Comment by iShinJini** [comment]
Thank you
