### ISSUE TITLE
ketos extract issue

### ISSUE THREAD

**Issue by akhlaghiandrew** [mittagessen/kraken#76]
I'm having an issue extracting the transcriptions from their filled environments through the vagrant virtual machine. I've save the files as .html and as .webarchive on my mac. When I run the ketos extract command, I get an empty file. Is it how I've saved the files?

**Comment by mittagessen** [comment]
You should save the filled transcriptions as HTML. Open the saved files in a web browser (or look for `<li id="line_...` parts with an editor) to see if the text is actually in there. You could also try updating the kraken version in the virtual machine; it is quite old as the main reason (clstm being hard to build) for packaging it in the first place is gone now.

**Comment by christophered** [comment]
@akhlaghiandrew 
My guess is that you didn't save the .html file correctly.
In order for us to have more insight on your problem, please attach the .html file that you used.

To create an html for transcription:
```
ketos transcribe -o output.html yourimage1.png yourimage2.png ......
```
Then you open the output.html which you just have created, and transcribe each line.
Once you have finished, you click `Ctrl+s` to save the transcribed .html.
Finally, you use ketos extract yourhtmlfile.html

**Comment by MrOCR** [comment]
@akhlaghiandrew can you update us regarding your progress with this issue.

**Comment by akhlaghiandrew** [comment]
Yes, that was exactly the issue. Sorry for not responding earlier.

**Comment by MrOCR** [comment]
@akhlaghiandrew then close this topic
