### ISSUE TITLE
some issues with six dependency

### ISSUE THREAD

**Issue by christophered** [mittagessen/kraken#78]
When installing requirements via `sudo pip install -r requirements.txt `
an error message in the end:
```
coremltools 0.8 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
```

**Comment by mittagessen** [comment]
Python packaging is still crap, so you should probably install everything in separate virtualenvs/conda environments or similar as dependencies of software frequently clashes. As kraken doesn't depend directly on six uninstalling it and then running ``pip install -r requirements.txt` should fix the issue.

In addition make sure to run the master branch under python 3, as we've dropped python 2 support with the new pytorch backend.

**Comment by christophered** [comment]
so I removed six using `sudo pip uninstall six`
and installed six 1.10 using `sudo pip install six==1.10.0`
later-on, trying to install kraken from source using `sudo pip install .` results in:
```
The directory '/home/home/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/home/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /home/home/Downloads/kraken-master
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-req-build-Zz3jhP/.eggs/pbr-4.1.0-py2.7.egg/pbr/core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-req-build-Zz3jhP/.eggs/pbr-4.1.0-py2.7.egg/pbr/util.py", line 259, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "/tmp/pip-req-build-Zz3jhP/.eggs/pbr-4.1.0-py2.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "/tmp/pip-req-build-Zz3jhP/.eggs/pbr-4.1.0-py2.7.egg/pbr/hooks/base.py", line 27, in run
        self.hook()
      File "/tmp/pip-req-build-Zz3jhP/.eggs/pbr-4.1.0-py2.7.egg/pbr/hooks/metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "/tmp/pip-req-build-Zz3jhP/.eggs/pbr-4.1.0-py2.7.egg/pbr/packaging.py", line 824, in get_version
        name=package_name))
    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name kraken was given, but was not able to be found.
    error in setup command: Error parsing /tmp/pip-req-build-Zz3jhP/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name kraken was given, but was not able to be found.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-Zz3jhP/

```

**Comment by mittagessen** [comment]
Just what it says on the tin. Install from the git repository of you want the latest master because otherwise pip is not able to determine the version number of the package automatically.

**Comment by christophered** [comment]
I have downloaded the latest master.
So I installed pip3 as you suggested using `sudo apt install python3-pip`
```
pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

```
Then installed the requirements without any problems.
Then `sudo pip3 install .` results in:
```
The directory '/home/home/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/home/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /home/home/.local/share/Trash/files/kraken-master
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-fqtw6mz3-build/.eggs/pbr-4.1.0-py3.6.egg/pbr/core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-fqtw6mz3-build/.eggs/pbr-4.1.0-py3.6.egg/pbr/util.py", line 259, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "/tmp/pip-fqtw6mz3-build/.eggs/pbr-4.1.0-py3.6.egg/pbr/hooks/__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "/tmp/pip-fqtw6mz3-build/.eggs/pbr-4.1.0-py3.6.egg/pbr/hooks/base.py", line 27, in run
        self.hook()
      File "/tmp/pip-fqtw6mz3-build/.eggs/pbr-4.1.0-py3.6.egg/pbr/hooks/metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "/tmp/pip-fqtw6mz3-build/.eggs/pbr-4.1.0-py3.6.egg/pbr/packaging.py", line 824, in get_version
        name=package_name))
    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name kraken was given, but was not able to be found.
    error in setup command: Error parsing /tmp/pip-fqtw6mz3-build/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name kraken was given, but was not able to be found.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-fqtw6mz3-build/
```

**Comment by christophered** [comment]
> And please, please, please don't install things globally. It will break your whole python installation sooner or later and will interfere with your distribution's packages

I have Timeshift in Linux Mint, so going back is one click away.

**Comment by christophered** [comment]
@mittagessen ok, I installed it by downloading `git clone ...` and kraken is working now.

**Comment by christophered** [comment]
@mittagessen how can I train now?

**Comment by mittagessen** [comment]
I've been holding off on writing documentation as there are still a few features I want to add before the next stable release but here it goes.

Run ``ketos train`` with a directory of text line-image pairs (dir/*.{png,tif,jpg}/{gt.txt}) will train with the defaults. That should give you a decent model after a few epochs of training. 

Now to all the fancy options available. Early stopping is enabled by default so training will stop automatically once the loss doesn't decrease anymore, if you don't want that set `-q` to `dumb` and `--epochs`to the desired number of epochs. 5% of the training set will be automatically split of as a validation set (use `-p` to adjust the ratio or feed a training and validation set explicitly from a manifest using `-t` and/or `-e`). Training set preloading into memory is enabled per default for sets with less than 2500 lines but if you don't have enough RAM can be disabled using `--no-preload`. 

To change the network's architecture you can use a VGSL network description with the `-s` option. Parallel layers aren't implemented yet but everything else should work. Don't include the output layer in the specification, it will be added automatically based on your training set.

It is possible to add a codec JSON file to the network with the `--codec` option which is just a dictionary of one or more output labels to a string of arbitrary length. You probably won't have to touch this of you don't want to do really weird stuff like automatic markup generation or large script recognition. 

You can start training from an existing model even if the training set alphabet doesn't match completely. Per default an error will be raised, but setting the `--resize` option to either `add ` or `both` will resize the original model's output layer and codec to either the union of the existing and new training data or retains every output in the old layer needed for the new training set and adds the ones needed by the new set.

Oh, and BiDi reordering is now done automatically by the `train` subcommand, so if you have an RTL data set already in reading order you have to add the `--no-reorder` option.

If/When anything breaks and goes up in flames please add a bug report and I'll hope to address it as soon as possible.

**Comment by amitdo** [comment]
@mittagessen

Meanwhile, the ocropus family keeps growing...
* ocropus (C++) -> [ocropy](https://github.com/tmbdev/ocropy)
* [clstm](https://github.com/tmbdev/clstm) (C++ again)
* [kraken](https://github.com/mittagessen/kraken)
* [Tesseract](https://github.com/tesseract-ocr/tesseract) 4.0.0 new LSTM engine. 
* [ocropy2](https://github.com/tmbdev/ocropy2)
* [ocropus3](https://github.com/NVLabs/ocropus3)
* [calamari](https://github.com/Calamari-OCR/calamari)

 Tesseract  4.0.0 new LSTM engine was ported from ocrooy. CNN was added (so it uses CNN+LSTM). 
 
Another one written by Ray Smith:
https://github.com/tensorflow/models/tree/master/research/street/python
