### ISSUE TITLE
protobuf.15.lib vs protobuf.16.lib

### ISSUE THREAD

**Issue by a-wendler** [mittagessen/kraken#80]
When trying to segment an image with script detection I get an error stating that protobuf.15.lib cannot be found. I have protobuf.16.lib on my system (comes with protobuf 3.6.0). Is there a way to use the .16.lib instead of .15 ?

(Hope the question’s not too stupid. Newbie here.)

**Comment by a-wendler** [comment]
Yes, I am on Mac OS X 10.13.6 High Sierra.

**Comment by mittagessen** [comment]
Sorry for the delayed answer, I've been on vacation. I can only recommend running everything on Linux for now. The clstm backend is gone in master and pytorch has official MacOS support so everything but the artificial line generator should work seamlessly as soon as the next pytorch stable release comes through.
