### ISSUE TITLE
Linegen is only using 1 cpu thread [Add multi-threads, or Parallel implementation] 

### ISSUE THREAD

**Issue by MrOCR** [mittagessen/kraken#81]
@mittagessen Thank you for your hard work.

Currently I started testing Kraken, and I noticed that when using `ketos linegen` it's only using 1 cpu at it's max while leaving the rest untouched, that might be enough if we are using `--disable-degradation`, but when using the default degradation filters it takes a long time to generate the sample lines.
My suggestion would be to add `--threads` option to `ketos linegen`.

Currently, I am able to work-around such problem by:

1)  Splitting each 100 lines into a separate `.txt` file:
```
awk '{filename = int((NR-1)/100) ".txt"; print >> filename}' input.txt
```
2) Then creating a list of all text files in the folder:
```
ls *.txt > list.txt
```
3) Then removing the `input.txt` line from the `list.txt`
```
sed -i '/input.txt/d' list.txt
```
4) Finally, using `Parallel` to run multiple instances of `ketos linegen`, I chose 3 threads:
```
parallel --a list.txt -j 3 'ketos linegen {} -o {.}'
```

This would speedup line generation by a multiple of the threads you set in `Parallel`, in my example it's 3 times faster than the default single thread. It would be even more helpful if you are using a Graphics Card.

Before:
![2](https://user-images.githubusercontent.com/33478216/44657993-9c629700-aa07-11e8-9fab-48701bbc8a80.jpg)

After:
![3](https://user-images.githubusercontent.com/33478216/44658003-a389a500-aa07-11e8-9c7b-84583d00d51e.jpg)

**Comment by QuLogic** [comment]
Maybe `concurrent.futures` with a thread pool? Can be easily switched to multi-process if it proves useful.

**Comment by mittagessen** [comment]
I guess multithreading should work in this case as it is mostly multidimensional filtering in numpy C code so the GIL might not screw everything up. With `multiprocessing` pickling everything introduces ridiculous overhead so I'd like to avoid that if possible.

**Comment by MrOCR** [comment]
@mittagessen recently, I installed Kraken using environment.yml for testing.
What did happen to **`ketos linegen`**? now it is very slow:
- Notice **`disk read`** & **`disk write`** is 26kps & 194kps.
- It's have high memory usage, about 2.5 GB.
- The CPU usage is 1 to 8 %.

![screenshot from 2018-11-27 19-10-54](https://user-images.githubusercontent.com/33478216/49096095-da778d00-f27a-11e8-91b6-0c99d2d98e1a.png)

![1](https://user-images.githubusercontent.com/33478216/49096080-d3e91580-f27a-11e8-8dfd-0bc3cb56dcda.jpg)

**Comment by mittagessen** [comment]
I literally didn't change anything. I'll add it to my to do list.
