### ISSUE TITLE
CTCLoss error when trying to Train [PyTorch version needs upgrade, & mention in README.rst]

### ISSUE THREAD

**Issue by christophered** [mittagessen/kraken#82]
@mittagessen Thank you for your hard work.

I have `kraken, version 0.10.1.dev147` which I installed initially from `git clone`.

After I generated the txt/ png pairs using `ketos linegen`, I created a list using:
```
ls *.png > manifest.txt
```
Then, I ran the training command:
```
ketos train -t manifest.txt
```
This results in this error:
```
Building training set  [####################################]  100%             
Building test set  [####################################]  100%             
Traceback (most recent call last):
  File "/usr/local/bin/ketos", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kraken/ketos.py", line 270, in train
    nn = vgsl.TorchVGSLModel(spec)
  File "/usr/local/lib/python3.6/dist-packages/kraken/lib/vgsl.py", line 118, in __init__
    self._parse(self.input, blocks)
  File "/usr/local/lib/python3.6/dist-packages/kraken/lib/vgsl.py", line 129, in _parse
    oshape, name, layer = op(input, block)
  File "/usr/local/lib/python3.6/dist-packages/kraken/lib/vgsl.py", line 644, in build_output
    self.criterion = nn.CTCLoss()
AttributeError: module 'torch.nn' has no attribute 'CTCLoss'
```
Did I wrongly install kraken, or is it a current bug in kraken itself?
The folder is attached below.
[training_data.zip](https://github.com/mittagessen/kraken/files/2323748/training_data.zip)

**Comment by kba** [comment]
CTCLoss has only been merged in pytorch on July 31 (https://github.com/pytorch/pytorch/commit/685224aa14b59d011d0926d615846a60f138e4ba). The release might not contain it yet. You could try to install from current upstream master with `pip install -e git+https://github.com/pytorch/pytorch`.

Just a guess though, haven't tested it.

**Comment by christophered** [comment]
@kba You were right, the `torch` version that `kraken` is currently pulling `0.4.1` does not contain the `CTCLoss` function, thus it fails.
Building `torch` from source have solved the problem and now the training function works, thanks.

My guess is that mittagessen left `torch>=0.4.1` in the `requirements.txt` so that we could test the other functions of kraken, while waiting for that [pypi repo](https://pypi.org/project/torch/) to update their `torch` version.
@mittagessen the pip repo that kraken is depending on will update at the end of October, since they update every 3 months, meanwhile can you update the `README.rst` and include the last 6 commands below, so that others can overcome this problem?

It's weird, because mittagessen already seems to have a more updated version at his [`Conda` repository.](https://anaconda.org/mittagessen)


These are the commands that I used to fix the problem:
```
sudo pip3 install pip-autoremove

sudo pip-autoremove kraken -y
```
```
sudo pip3 install torchvision --no-deps

sudo pip3 install git+https://github.com/pytorch/pytorch

git clone https://github.com/mittagessen/kraken.git --recursive

cd kraken/

sed -i '/torch/d' requirements.txt

sudo pip3 install .

```

**Comment by christophered** [comment]
@mittagessen Please modify `README.rst` and close this topic.
Thanks

**Comment by mittagessen** [comment]
Sorry for the delay, I've been on vacation. You correctly identified that the native CTCLoss is not in any stable release of pytorch, yet. Installing pytorch through pip directly from git master is a bit finicky and will quite often break as source builds require specific toolchain versions that are older than ones in the repositories of most distros. The conda pytorch-master build is a binary package of the pytorch master branch in mid-August that contains the new CTC loss and should work without issues. I was planning to make the stable release concurrent with the pytorch 0.4.3 next month(-ish?).

**Comment by christophered** [comment]
@mittagessen Thank you man. For those who are trying to install kraken, don't build `pytorch` from direct master git, instead use an older master at 2018/8/10, the commands to build are below.
```
conda create -n python3 python=3.6 anaconda
source activate python3
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
conda install -c mingfeima mkldnn
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
git checkout `git rev-list -n 1 --before="2018-08-10 23:59" master`
git submodule update --init
sudo python3 setup.py install
```
```
git clone https://github.com/mittagessen/kraken.git --recursive

cd kraken/

sed -i '/torch/d' requirements.txt

sudo pip3 install .
```

**Comment by mittagessen** [comment]
You should be able to use master HEAD, the pytorch devs are better developers than I am and almost never break master.
