### ISSUE TITLE
[Rename the kraken repository to kraken-ocr]

### ISSUE THREAD

**Issue by christophered** [mittagessen/kraken#83]
@mittagessen 
- When searching kraken at Github, thousands of repositories show, and this one is hard to find.
We can't find this repo even if we type `kraken ocr` in the search.
So please rename this repo to `kraken-ocr`, it will make it easier to find.

**Comment by amitdo** [comment]
The reason you can't easily find kraken is because it's still a fork repo.

https://github.com/topics/ocr?o=desc&q=fork%3Aonly&s=stars

**Comment by christophered** [comment]
@mittagessen how about unforking this repo :sunglasses: 
You already rebuilt kraken code, does the `Apache License` still applies?

Or atleast change the repo name to `kraken-ocr`.

**Comment by mittagessen** [comment]
I asked github support to detach the fork which should fix the problem. It might take a few days until they get around to it.

**Comment by mittagessen** [comment]
They've just detached it. That was fast.

**Comment by amitdo** [comment]
Congrats! :-)
