### ISSUE TITLE
Model for Scheherazade?

### ISSUE THREAD

**Issue by sixtyfive** [mittagessen/kraken#86]
Hi! Is there by any chance a training model for Scheherazade (the SIL font) available somewhere already, to anyone's knowledge?

**Comment by mittagessen** [comment]
Sorry, I and everybody I know mostly deals with stuff that uses fonts carved by ancient hermits in the Lebanese mountains.

**Comment by sixtyfive** [comment]
Ancient hermits in the Lebanese mountains? Oh, you must mean Microsoft! In that case someone should do a model for their Traditional Arabic font. 

(Thanks for the answer!)
