### ISSUE TITLE
Sponsor URL linked to from README is broken

### ISSUE THREAD

**Issue by sixtyfive** [mittagessen/kraken#87]
Expected result: click on [link](http://ephe.fr/), see École Pratique des Hautes Études - Université PSL's website.

Actual result: clicked on that link and got DNS resolution error. Also cf. [dfeojm](https://downforeveryoneorjustme.com/ephe.fr).

**Comment by mittagessen** [comment]
Thanks, apparently firefox does automatic `www.` augmentation now.
