### ISSUE TITLE
Unable to train data on kraken

### ISSUE THREAD

**Issue by Usamamalik007** [mittagessen/kraken#93]
Can someone guide me? The documentation is unclear?
Plus if can someone tell me if I can train a model from scratch?

**Comment by mittagessen** [comment]
I've updated the [training manual](https://github.com/mittagessen/kraken/blob/master/docs/training.rst) to reflect the last week's changes and added what I believe to be the least troublesome way to install kraken and dependencies in one go. If you think anything concrete is missing in there I'd like to hear about it.

**Comment by MrOCR** [comment]
@mittagessen please close this issue.
