### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#99]
Hey there,
Looking at Kraken right now and following the tutorial. In it, you have http://kraken.re/training.html#evaluation-and-validation . Unfortunately, I can't find a trace of this file (nor can I find it there https://github.com/mittagessen/kraken-vagrant/ ). Any place I did not look at potentially ?

**Comment by mittagessen** [comment]
The documentation is for the last stable release only, as I wasn't able to convince the versioned sphinx code to do what it says on its tin.

If you're using the master branch (conda installation), ketos ships with an own `ketos test` command that has better Unicode support than the ISRI evaluation tools the eval script uses. It is vastly easier to train, produces better accuracy, is faster, and the models it produces can be easily retrained even with mismatching alphabets.

**Comment by PonteIneptique** [comment]
Closing then :)
